from pathlib import Path
import json, re

ROOT = Path('.')

def read(path):
    return (ROOT / path).read_text(encoding='utf-8')

def write(path, text):
    (ROOT / path).write_text(text, encoding='utf-8')

def replace(path, old, new, count=1):
    text = read(path)
    if old not in text:
        raise SystemExit(f'Missing expected text in {path}: {old[:100]!r}')
    text = text.replace(old, new, count)
    write(path, text)

def regex_replace(path, pattern, replacement, count=1):
    text = read(path)
    new, n = re.subn(pattern, replacement, text, count=count, flags=re.S)
    if n != count:
        raise SystemExit(f'Expected {count} regex replacement(s) in {path}, got {n}: {pattern}')
    write(path, new)

# One canonical catalog for App, dashboard, workflows and QA.
write('src/tool-catalog.ts', """import { categories, tools as baseTools } from './data-tools'\nimport { productivityTools } from './productivity-tools'\nimport { featurePackTools } from './feature-pack-tools'\n\nconst featuredOverrides = {\n  'video-compressor': { name:'Video Compressor', desc:'Make video files smaller directly in your browser with quality and resolution controls.', badge:'Featured' },\n  'video-trim': { name:'Video Trimmer', desc:'Cut the exact start and end of a video with a built-in playback preview.', badge:'Featured' },\n  'video-speed': { name:'Video Playback Speed', desc:'Create slow-motion or fast-motion video with presets from 0.25× to 4×.', badge:'Featured' },\n}\n\nconst enhancedBaseTools = baseTools.map(t => featuredOverrides[t.id] ? { ...t, ...featuredOverrides[t.id] } : t)\nexport { categories }\nexport const tools = [...enhancedBaseTools, ...productivityTools, ...featurePackTools]\nexport const toolMap = Object.fromEntries(tools.map(t => [t.id, t]))\nexport const featuredVideoIds = ['video-compressor','video-trim','video-speed']\n""")

# App uses canonical catalog; IT tools become normal /tools pages.
replace('src/App.tsx', "import { categories, tools as baseTools } from './data-tools'\nimport { productivityTools } from './productivity-tools'\nimport { featurePackTools } from './feature-pack-tools'", "import { categories, tools, toolMap, featuredVideoIds } from './tool-catalog'\nimport { productivityTools } from './productivity-tools'\nimport { featurePackTools } from './feature-pack-tools'")
replace('src/App.tsx', "import { ImageCropRotate, DocumentEnhancer, PhotoSheet, PosterSplitter, TextToolkit, JsonCsv, XmlTools, RegexTester, JwtDecoder, UrlTools, TimestampConverter, UuidGenerator, ImageBase64, MacFormatter, FileSizeConverter, UnitConverter, DateCalculator, PercentageCalculator, ListRandomizer, ColorConverter, CsvColumnTool, WifiQr, NumberToolkit, TextExtractor } from './tools/FeaturePack'", "import { ImageCropRotate, DocumentEnhancer, PhotoSheet, PosterSplitter, TextToolkit, JsonCsv, XmlTools, RegexTester, JwtDecoder, UrlTools, TimestampConverter, UuidGenerator, ImageBase64, MacFormatter, FileSizeConverter, UnitConverter, DateCalculator, PercentageCalculator, ListRandomizer, ColorConverter, CsvColumnTool, WifiQr, NumberToolkit, TextExtractor } from './tools/FeaturePack'\nimport { itToolsV2 } from './it-tools-pack-v2'\nimport { ITToolEngine } from './tools/ITToolsV2'")
regex_replace('src/App.tsx', r"\nconst featuredOverrides=\{[\s\S]*?const featuredVideoIds=\['video-compressor','video-trim','video-speed'\]\n", "\n")
replace('src/App.tsx', 'const toolComponents={', 'const toolComponents: Record<string, any>={')
replace('src/App.tsx', "  'photo-sheet':PhotoSheet,'poster-splitter':PosterSplitter,'text-toolkit':TextToolkit,'json-csv':JsonCsv,'xml-tools':XmlTools,'regex-tester':RegexTester,'jwt-decoder':JwtDecoder,'url-tools':UrlTools,'timestamp-converter':TimestampConverter,'uuid-generator':UuidGenerator,'image-base64':ImageBase64,'mac-formatter':MacFormatter,'file-size-converter':FileSizeConverter,'unit-converter':UnitConverter,'date-calculator':DateCalculator,'percentage-calculator':PercentageCalculator,'list-randomizer':ListRandomizer,'color-converter':ColorConverter,'csv-column-tool':CsvColumnTool,'wifi-qr':WifiQr,'number-tools':NumberToolkit,'text-extractor':TextExtractor,\n}\n\nfunction Brand", "  'photo-sheet':PhotoSheet,'poster-splitter':PosterSplitter,'text-toolkit':TextToolkit,'json-csv':JsonCsv,'xml-tools':XmlTools,'regex-tester':RegexTester,'jwt-decoder':JwtDecoder,'url-tools':UrlTools,'timestamp-converter':TimestampConverter,'uuid-generator':UuidGenerator,'image-base64':ImageBase64,'mac-formatter':MacFormatter,'file-size-converter':FileSizeConverter,'unit-converter':UnitConverter,'date-calculator':DateCalculator,'percentage-calculator':PercentageCalculator,'list-randomizer':ListRandomizer,'color-converter':ColorConverter,'csv-column-tool':CsvColumnTool,'wifi-qr':WifiQr,'number-tools':NumberToolkit,'text-extractor':TextExtractor,\n}\nitToolsV2.forEach(t=>{toolComponents[t.id]=ITToolEngine})\n\nfunction Brand")

# Remove the separate IT-page shell; keep only legacy redirect and developer credit.
write('src/EnhancedITApp.tsx', """import { Navigate, useLocation } from 'react-router-dom'\nimport App from './App'\n\nfunction Credit(){return <div className=\"deskora-dev-credit\">Developed by <a href=\"https://jmqbataller.vercel.app/\" target=\"_blank\" rel=\"noreferrer\">John Mark Bataller</a></div>}\n\nexport default function EnhancedITApp(){\n  const {pathname,search}=useLocation()\n  if(pathname==='/it-tools'||pathname.startsWith('/it-tools/'))return <Navigate to=\"/tools?category=it\" replace/>\n  // Keying the library by query keeps category filters synced when navigating between ?category= links.\n  return <><App key={pathname==='/tools'?search:'deskora'}/><Credit/></>\n}\n""")

# Newer tools must resolve inside dashboard/workflow lists too.
replace('src/tools/ProductivitySuite.tsx', "import { toolMap, tools } from '../data-tools'", "import { toolMap, tools } from '../tool-catalog'")
replace('src/tools/WorkspaceTools.tsx', "import { tools } from '../data-tools'", "import { tools } from '../tool-catalog'")

# Harden the secondary FFmpeg engine used by resize/GIF/audio/watermark tools.
media_engine = """let ff\nlet mediaProgressHandler\nlet latestMediaLog=''\nasync function engine(onProgress){\n  mediaProgressHandler=onProgress\n  if(!ff){\n    const instance=new FFmpeg()\n    instance.on('progress',({progress})=>mediaProgressHandler?.(Math.max(0,Math.min(100,Math.round(progress*100)))))\n    instance.on('log',({message})=>{if(message)latestMediaLog=message})\n    try{await instance.load({coreURL:'/ffmpeg/ffmpeg-core.js',wasmURL:'/ffmpeg/ffmpeg-core.wasm'});ff=instance}catch(error){ff=null;throw error}\n  }\n  return ff\n}\nasync function safeDelete(f,name){try{await f.deleteFile(name)}catch{}}\nfunction mediaError(error,fallback='FFmpeg could not process this media file.'){if(error instanceof Error&&error.message)return error.message;if(typeof error==='string'&&error.trim())return error;if(latestMediaLog.trim())return latestMediaLog;return fallback}\nasync function runFfmpeg(file,args,out,onProgress,extra=[]){\n  const f=await engine(onProgress),ext=(file.name.split('.').pop()||'mp4').toLowerCase(),input=`input-${Date.now()}.${ext}`\n  latestMediaLog=''\n  try{\n    await f.writeFile(input,await fetchFile(file))\n    for(const x of extra)await f.writeFile(x.name,await fetchFile(x.file))\n    const finalArgs=args.map(x=>x==='$IN'?input:x),exitCode=await f.exec(finalArgs)\n    if(exitCode!==0)throw new Error(latestMediaLog||`FFmpeg exited with code ${exitCode}`)\n    const data=await f.readFile(out)\n    if(typeof data==='string')throw new Error('FFmpeg returned text instead of a media file.')\n    return new Blob([data.buffer])\n  }finally{\n    await safeDelete(f,input);await safeDelete(f,out);for(const x of extra)await safeDelete(f,x.name)\n  }\n}\nasync function mergeAudio(files,onProgress){\n  const f=await engine(onProgress),names=[],out='deskora-audio-merged.mp3';latestMediaLog=''\n  try{\n    for(let i=0;i<files.length;i++){const ext=(files[i].name.split('.').pop()||'mp3').toLowerCase(),name=`merge-${Date.now()}-${i}.${ext}`;names.push(name);await f.writeFile(name,await fetchFile(files[i]))}\n    const args=[];names.forEach(n=>args.push('-i',n));const inputs=names.map((_,i)=>`[${i}:a]`).join('');args.push('-filter_complex',`${inputs}concat=n=${names.length}:v=0:a=1[a]`,'-map','[a]','-codec:a','libmp3lame','-q:a','2',out)\n    const exitCode=await f.exec(args);if(exitCode!==0)throw new Error(latestMediaLog||`FFmpeg exited with code ${exitCode}`)\n    const data=await f.readFile(out);if(typeof data==='string')throw new Error('FFmpeg returned text instead of audio.');return new Blob([data.buffer],{type:'audio/mpeg'})\n  }finally{for(const n of names)await safeDelete(f,n);await safeDelete(f,out)}\n}\n\nexport function VideoSocialResize"""
regex_replace('src/tools/MediaExpansion.tsx', r"let ff[\s\S]*?export function VideoSocialResize", media_engine)
text = read('src/tools/MediaExpansion.tsx').replace('catch(e){setMsg(e.message)}', 'catch(e){setMsg(mediaError(e))}')
text = text.replace("function load(f){setFile(f);setPreview(URL.createObjectURL(f));setMsg('Move the video to the frame you want, then capture it.')}", "function load(f){setFile(f);if(preview)URL.revokeObjectURL(preview);setPreview(URL.createObjectURL(f));setMsg('Move the video to the frame you want, then capture it.')}")
write('src/tools/MediaExpansion.tsx', text)

# Image compression must always use an encoding the canvas can actually produce.
replace('src/tools/ImageTools.tsx', "const type=file.type==='image/png'?'image/webp':(file.type||'image/jpeg');const blob=await renderImage(file,{type,quality:Number(quality)});const ext=type==='image/webp'?'webp':'jpg'", "const type=file.type==='image/png'||file.type==='image/webp'?'image/webp':'image/jpeg';const blob=await renderImage(file,{type,quality:Number(quality)});const ext=type==='image/webp'?'webp':'jpg'")

# Utility fixes: usable /31-/32 ranges and digest-based compare for large files.
replace('src/tools/UtilityTools.tsx', "const[ab,bb]=await Promise.all([a.arrayBuffer(),b.arrayBuffer()]);const av=new Uint8Array(ab),bv=new Uint8Array(bb);let same=true;for(let i=0;i<av.length;i++){if(av[i]!==bv[i]){same=false;break}}setResult(same?'Identical — the files are byte-for-byte the same.':'Different — file contents do not match.')", "const[ah,bh]=await Promise.all([crypto.subtle.digest('SHA-256',await a.arrayBuffer()),crypto.subtle.digest('SHA-256',await b.arrayBuffer())]);const av=new Uint8Array(ah),bv=new Uint8Array(bh),same=av.every((v,i)=>v===bv[i]);setResult(same?'Identical — the files are byte-for-byte the same.':'Different — file contents do not match.')")
replace('src/tools/UtilityTools.tsx', "first:c>=31?'N/A':intToIp((network+1)>>>0),last:c>=31?'N/A':intToIp((broadcast-1)>>>0)", "first:c===32?intToIp(network):c===31?intToIp(network):intToIp((network+1)>>>0),last:c===32?intToIp(network):c===31?intToIp(broadcast):intToIp((broadcast-1)>>>0)")

# PDF metadata should really be cleared, not replaced with Deskora metadata.
replace('src/tools/DocumentExpansion.tsx', "pdf.setCreator('Deskora');pdf.setProducer('Deskora')", "pdf.setCreator('');pdf.setProducer('')")

# Generator download buttons should not export blank canvases before generation.
replace('src/tools/OfficeTools.tsx', '<button className="secondary" onClick={download}>Download PNG</button><Status>{msg}</Status></div>\n}\n\nexport function BarcodeGenerator', '<button className="secondary" disabled={!msg.includes(\'generated\')} onClick={download}>Download PNG</button><Status>{msg}</Status></div>\n}\n\nexport function BarcodeGenerator')
replace('src/tools/OfficeTools.tsx', '<button className="secondary" onClick={download}>Download PNG</button><Status>{msg}</Status></div>\n}', '<button className="secondary" disabled={!msg.includes(\'generated\')} onClick={download}>Download PNG</button><Status>{msg}</Status></div>\n}', 1)
replace('src/tools/OfficeTools.tsx', "const payload=mode==='wifi'?`WIFI:T:WPA;S:${ssid};P:${password};;`:value", "const esc=s=>String(s).replace(/([\\\\;,:\\"])/g,'\\\\$1');const payload=mode==='wifi'?`WIFI:T:WPA;S:${esc(ssid)};P:${esc(password)};;`:value")

# Spreadsheet splitter must report invalid input instead of throwing an unhandled promise rejection.
replace('src/tools/OfficeExpansion.tsx', "async function load(f){setFile(f);const wb=await readBook(f),r=rowsOf(wb);setRows(r);setColumn(Object.keys(r[0]||{})[0]||'')}", "async function load(f){setFile(f);setBusy(true);try{const wb=await readBook(f),r=rowsOf(wb);setRows(r);setColumn(Object.keys(r[0]||{})[0]||'');setMsg(`${r.length} rows loaded.`)}catch(e){setRows([]);setMsg(e instanceof Error?e.message:'Could not read this spreadsheet.')}finally{setBusy(false)}}")

# Developer/office edge cases.
replace('src/tools/FeaturePack.tsx', 'max=1600,scale=Math.min(1,max/img.naturalWidth)', 'max=1600,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight))')
regex_replace('src/tools/FeaturePack.tsx', r"export function TimestampConverter\(\)\{[\s\S]*?\n\nexport function UuidGenerator", """export function TimestampConverter(){const[unix,setUnix]=useState(()=>Math.floor(Date.now()/1000).toString()),[date,setDate]=useState(()=>new Date().toISOString().slice(0,16)),[result,setResult]=useState('');function fromUnix(){try{const n=Number(unix);if(!Number.isFinite(n))throw new Error('Enter a valid Unix timestamp.');const d=new Date(n>1e12?n:n*1000);if(!Number.isFinite(d.getTime()))throw new Error('Timestamp is outside the supported date range.');setResult(`Local: ${d.toLocaleString()}\\nUTC: ${d.toUTCString()}\\nISO: ${d.toISOString()}`)}catch(e){setResult(e instanceof Error?e.message:'Invalid timestamp.')}}function fromDate(){const ms=new Date(date).getTime();setResult(Number.isFinite(ms)?`Unix seconds: ${Math.floor(ms/1000)}\\nUnix milliseconds: ${ms}`:'Enter a valid date and time.')}return <div className=\"stack\"><div className=\"form-grid\"><label>Unix timestamp<input value={unix} onChange={e=>setUnix(e.target.value)}/><button className=\"secondary\" onClick={fromUnix}>Convert timestamp</button></label><label>Date & time<input type=\"datetime-local\" value={date} onChange={e=>setDate(e.target.value)}/><button className=\"secondary\" onClick={fromDate}>Convert date</button></label></div><div className=\"code-result pre\">{result||'Conversion result appears here.'}</div></div>}\n\nexport function UuidGenerator""")
regex_replace('src/tools/FeaturePack.tsx', r"export function ImageBase64\(\)\{[\s\S]*?\n\nexport function MacFormatter", """export function ImageBase64(){const[file,setFile]=useState(null),[text,setText]=useState(''),[msg,setMsg]=useState('');async function encode(f){if(!f)return;const reader=new FileReader();reader.onload=()=>{setFile(f);setText(String(reader.result));setMsg(`${formatBytes(f.size)} encoded.`)};reader.onerror=()=>setMsg('Could not read image.');reader.readAsDataURL(f)}function decode(){try{const raw=text.trim();if(!raw)throw new Error('Paste a data URL or Base64 image first.');const src=raw.startsWith('data:')?raw:`data:image/png;base64,${raw}`;const mime=src.match(/^data:(image\\/[a-z0-9.+-]+);base64,/i)?.[1]||'image/png';const ext=mime.includes('jpeg')?'jpg':mime.includes('webp')?'webp':mime.includes('gif')?'gif':'png';const a=document.createElement('a');a.href=src;a.download=`deskora-decoded-image.${ext}`;a.click();setMsg(`Decoded ${mime} download started.`)}catch(e){setMsg(e instanceof Error?e.message:'Invalid image Base64 input.')}}return <div className=\"stack\"><FileDrop accept=\"image/*\" onFiles={f=>encode(f[0])}/><label>Data URL / Base64<textarea rows=\"12\" value={text} onChange={e=>setText(e.target.value)}/></label><div className=\"button-row\"><button className=\"primary\" disabled={!text} onClick={()=>navigator.clipboard.writeText(text)}>Copy</button><button className=\"secondary\" disabled={!text} onClick={decode}>Decode to image</button></div><Status>{msg}</Status></div>}\n\nexport function MacFormatter""")
replace('src/tools/FeaturePack.tsx', "const groups=Array.from({length:Number(teams)},()=>[]);shuffle(items).forEach((v,i)=>groups[i%groups.length].push(v));", "const teamCount=clamp(Number(teams)||2,2,20),groups=Array.from({length:teamCount},()=>[]);shuffle(items).forEach((v,i)=>groups[i%groups.length].push(v));")
replace('src/tools/FeaturePack.tsx', "payload=`WIFI:T:${security};S:${esc(ssid)};P:${esc(password)};H:${hidden?'true':'false'};;`", "payload=security==='nopass'?`WIFI:T:nopass;S:${esc(ssid)};H:${hidden?'true':'false'};;`:`WIFI:T:${security};S:${esc(ssid)};P:${esc(password)};H:${hidden?'true':'false'};;`")
replace('src/tools/FeaturePack.tsx', "<strong>{nums.length?Math.min(...nums):'—'}</strong>", "<strong>{nums.length?nums.reduce((m,n)=>n<m?n:m,nums[0]):'—'}</strong>")
replace('src/tools/FeaturePack.tsx', "<strong>{nums.length?Math.max(...nums):'—'}</strong>", "<strong>{nums.length?nums.reduce((m,n)=>n>m?n:m,nums[0]):'—'}</strong>")
replace('src/feature-pack-tools.ts', "desc:'Select, rename or remove columns from CSV/Excel data and export a cleaned workbook.'", "desc:'Select or remove columns from CSV/Excel data and export a cleaned workbook.'")

# PDF Editor Pro: pointer events work on mouse, pen and touch; exported check mark matches preview.
replace('src/tools/PdfPro.tsx', "else if(a.type==='check')p.drawText('X',{x,y,size:24,font,color:rgb(.04,.45,.4)});", "else if(a.type==='check'){const c=rgb(.04,.45,.4);p.drawLine({start:{x,y:y-7},end:{x:x+7,y:y-15},thickness:3,color:c});p.drawLine({start:{x:x+7,y:y-15},end:{x:x+20,y:y+2},thickness:3,color:c})};")
replace('src/tools/PdfPro.tsx', '<canvas ref={canvas} onMouseDown={down} onMouseUp={up}/>', '<canvas ref={canvas} onPointerDown={down} onPointerUp={up}/>')

# Productivity suite: honor target-size preset and preserve selected image extension after a pipeline.
replace('src/tools/ProductivitySuite.tsx', "const[file,setFile]=useState(null),[target,setTarget]=useState(500),[unit,setUnit]=useState('KB'),[busy,setBusy]", "const params=new URLSearchParams(window.location.search),initialTarget=Number(params.get('target'))||500,initialUnit=params.get('unit')==='MB'?'MB':'KB';const[file,setFile]=useState(null),[target,setTarget]=useState(initialTarget),[unit,setUnit]=useState(initialUnit),[busy,setBusy]")
replace('src/tools/ProductivitySuite.tsx', "onClick={()=>downloadBlob(result,`${safeBaseName(file?.name)}-pipeline${isPdf?'.pdf':'.jpg'}`)}", "onClick={()=>{const fmt=steps.find(s=>s.type==='format')?.value,ext=isPdf?'pdf':fmt==='image/png'?'png':fmt==='image/webp'?'webp':'jpg';downloadBlob(result,`${safeBaseName(file?.name)}-pipeline.${ext}`)}}")

# IT tool catalog/engine wording and Wi-Fi open-network correctness.
replace('src/it-tools-pack-v2.ts', "desc:'Convert dotted IPv4 addresses to binary and back.'", "desc:'Convert dotted IPv4 addresses to binary notation.'")
replace('src/it-tools-pack-v2.ts', "desc:'Generate UUIDs, random hex strings, PINs and temporary tokens locally.'", "desc:'Generate UUIDs and cryptographically random hex tokens locally.'")
replace('src/tools/ITToolsV2.tsx', "const httpCodes=[['200','OK']", "const httpCodes=[['100','Continue'],['101','Switching Protocols'],['103','Early Hints'],['200','OK']")
replace('src/tools/ITToolsV2.tsx', "setData(await QRCode.toDataURL(`WIFI:T:${sec};S:${esc(ssid)};P:${esc(pass)};;`,{width:420,margin:2}))", "setData(await QRCode.toDataURL(sec==='nopass'?`WIFI:T:nopass;S:${esc(ssid)};;`:`WIFI:T:${sec};S:${esc(ssid)};P:${esc(pass)};;`,{width:420,margin:2}))")
replace('src/tools/ITToolsV2.tsx', "This utility is available from the IT Hub.", "This utility belongs to Deskora IT & Security.")

# Correct catalog QA parser and enforce it in CI.
write('scripts/qa-catalog.mjs', """import fs from 'node:fs'\n\nconst read = path => fs.readFileSync(path, 'utf8')\nconst ids = text => [...text.matchAll(/\\bid\\s*:\\s*['\"]([^'\"]+)['\"]/g)].map(m => m[1])\nconst arrayBlock = (text,name) => text.match(new RegExp(`export const ${name}\\\\s*=\\\\s*\\\\[([\\\\s\\\\S]*?)\\\\n\\\\]`))?.[1] || ''\n\nconst data = read('src/data-tools.ts')\nconst base = ids(arrayBlock(data,'tools'))\nconst productivity = ids(read('src/productivity-tools.ts'))\nconst featureUtility = ids(read('src/feature-pack-tools.ts'))\nconst it = ids(read('src/it-tools-pack-v2.ts'))\nconst all = [...base, ...productivity, ...featureUtility, ...it]\nconst duplicates = all.filter((id, i) => all.indexOf(id) !== i)\n\nconst app = read('src/App.tsx')\nconst componentBlock = app.match(/const toolComponents[^=]*=\\s*\\{([\\s\\S]*?)\\n\\}/)?.[1] || ''\nconst components = new Set([...componentBlock.matchAll(/['\"]([^'\"]+)['\"]\\s*:\\s*[A-Za-z_$][\\w$]*/g)].map(m => m[1]))\nconst nonIt = all.filter(id => !it.includes(id))\nconst missingComponents = nonIt.filter(id => !components.has(id))\n\nconst itEngine = read('src/tools/ITToolsV2.tsx')\nconst itCases = new Set([...itEngine.matchAll(/case\\s*['\"]([^'\"]+)['\"]/g)].map(m => m[1]))\nconst missingItCases = it.filter(id => !itCases.has(id))\nconst unknownItCases = [...itCases].filter(id => !it.includes(id))\n\nconst categories = new Set(ids(arrayBlock(data,'categories')))\nconst records = [arrayBlock(data,'tools'), read('src/productivity-tools.ts'), read('src/feature-pack-tools.ts'), read('src/it-tools-pack-v2.ts')].join('\\n')\nconst categoryRefs = [...records.matchAll(/\\bcategory\\s*:\\s*['\"]([^'\"]+)['\"]/g)].map(m => m[1])\nconst badCategories = [...new Set(categoryRefs.filter(c => !categories.has(c)))]\n\nconst failures = []\nif (duplicates.length) failures.push(`Duplicate tool IDs: ${[...new Set(duplicates)].join(', ')}`)\nif (missingComponents.length) failures.push(`Catalog tools missing normal handlers: ${missingComponents.join(', ')}`)\nif (missingItCases.length) failures.push(`IT tools missing ITToolEngine cases: ${missingItCases.join(', ')}`)\nif (unknownItCases.length) failures.push(`ITToolEngine cases missing from catalog: ${unknownItCases.join(', ')}`)\nif (badCategories.length) failures.push(`Unknown categories: ${badCategories.join(', ')}`)\nconsole.log(`Deskora catalog QA: ${all.length} unique tool registrations inspected.`)\nconsole.log(`Normal handlers: ${components.size}; IT engine cases: ${itCases.size}.`)\nif (failures.length) { console.error('\\n'+failures.map(x=>`- ${x}`).join('\\n')); process.exit(1) }\nconsole.log('PASS — catalog IDs, categories and handlers are consistent.')\n""")

pkg = json.loads(read('package.json'))
pkg['version'] = '1.5.2'
scripts = pkg.setdefault('scripts', {})
ordered = {}
for k,v in scripts.items():
    ordered[k]=v
    if k=='build': ordered['qa']='node scripts/qa-catalog.mjs'
if 'qa' not in ordered: ordered['qa']='node scripts/qa-catalog.mjs'
pkg['scripts']=ordered
write('package.json', json.dumps(pkg, indent=2, ensure_ascii=False)+'\n')

ci = read('.github/workflows/ci.yml')
if 'npm run qa' not in ci:
    ci = ci.replace('      - run: npm run build', '      - run: npm run qa\n      - run: npm run build')
write('.github/workflows/ci.yml', ci)

# Remove this one-shot migration machinery before committing the real patch.
Path('scripts/apply-qa-fixes.py').unlink(missing_ok=True)
Path('.github/workflows/apply-full-tool-qa.yml').unlink(missing_ok=True)
print('Deskora QA fixes applied.')
