import { useEffect, useMemo, useState } from 'react'
import { Link, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { ArrowRight, Check, ChevronRight, Files, Github, LockKeyhole, Menu, Search, ShieldCheck, Sparkles, X, Zap } from 'lucide-react'
import { categories, toolMap, tools } from './data-tools'
import ToolShell from './components/ToolShell'
import { PdfToImage, ImagesToPdf, MergePdf, SplitPdf, RotatePdf } from './tools/PdfTools'
import { ConvertImage, CompressImage, ResizeImage, BatchImages } from './tools/ImageTools'
import { VideoCompressor, VideoSpeed, VideoTrim, VideoAudio } from './tools/VideoTools'
import { CsvCleaner, TextCompare, EmailCleaner, QrGenerator, BarcodeGenerator } from './tools/OfficeTools'
import { ZipCreator, ZipExtractor, FileHash, FileCompare, SubnetCalculator, PasswordGenerator, JsonTools, Base64Tools, DpiCalculator, PaperSize } from './tools/UtilityTools'
import { CameraScanner, PdfEditor } from './tools/DeskoraExtras'
import { PdfOrganizer, PdfCompressor, OcrToText, ReceiptScanner, BusinessCardScanner, SearchablePdf, PdfToWordText, PdfMetadataCleaner, PdfRedactor, SignatureMaker, IdPictureMaker, DateStampGenerator, PdfPasswordTool } from './tools/DocumentExpansion'
import { SpreadsheetDuplicateFinder, SpreadsheetCompare, ExcelMerge, ExcelSplitter, SmartRename, BulkOrganizer, DuplicateFileFinder, ImageMetadataCleaner, NumberToWords, VatCalculator, WorkdaysCalculator, CodeScanner, MeetingTranscriber } from './tools/OfficeExpansion'
import { VideoSocialResize, VideoFrameExtractor, GifMaker, AudioStudio, WatermarkCenter } from './tools/MediaExpansion'
import { WorkflowBuilder, WorkspaceInfo } from './tools/WorkspaceTools'

const toolComponents={
  'pdf-to-image':PdfToImage,'edit-pdf':PdfEditor,'pdf-form-filler':PdfEditor,'pdf-organizer':PdfOrganizer,'pdf-compressor':PdfCompressor,'pdf-redactor':PdfRedactor,'pdf-to-word':PdfToWordText,'pdf-metadata':PdfMetadataCleaner,'pdf-password':PdfPasswordTool,'searchable-pdf':SearchablePdf,'images-to-pdf':ImagesToPdf,'merge-pdf':MergePdf,'split-pdf':SplitPdf,'rotate-pdf':RotatePdf,
  'convert-image':ConvertImage,'compress-image':CompressImage,'resize-image':ResizeImage,'batch-images':BatchImages,'image-metadata':ImageMetadataCleaner,'signature-maker':SignatureMaker,'watermark-center':WatermarkCenter,
  'video-compressor':VideoCompressor,'video-speed':VideoSpeed,'video-trim':VideoTrim,'video-audio':VideoAudio,'video-social-resize':VideoSocialResize,'video-frame':VideoFrameExtractor,'gif-maker':GifMaker,
  'audio-studio':AudioStudio,
  'camera-scanner':CameraScanner,'ocr-text':OcrToText,'receipt-scanner':ReceiptScanner,'business-card-scanner':BusinessCardScanner,'csv-cleaner':CsvCleaner,'spreadsheet-duplicates':SpreadsheetDuplicateFinder,'spreadsheet-compare':SpreadsheetCompare,'excel-merge':ExcelMerge,'excel-split':ExcelSplitter,'text-compare':TextCompare,'email-cleaner':EmailCleaner,'qr-generator':QrGenerator,'barcode-generator':BarcodeGenerator,'code-scanner':CodeScanner,'meeting-transcriber':MeetingTranscriber,'number-to-words':NumberToWords,'vat-calculator':VatCalculator,'workdays-calculator':WorkdaysCalculator,'workflow-builder':WorkflowBuilder,'workspace':WorkspaceInfo,
  'zip-creator':ZipCreator,'zip-extractor':ZipExtractor,'file-hash':FileHash,'file-compare':FileCompare,'smart-rename':SmartRename,'bulk-organizer':BulkOrganizer,'duplicate-files':DuplicateFileFinder,'subnet-calculator':SubnetCalculator,
  'password-generator':PasswordGenerator,'json-tools':JsonTools,'base64-tools':Base64Tools,'dpi-calculator':DpiCalculator,'paper-size':PaperSize,'id-picture':IdPictureMaker,'date-stamp':DateStampGenerator,
}

function Brand(){return <Link className="brand" to="/"><span className="brand-mark"><Files size={19}/></span><span>Deskora</span></Link>}

function InstallButton(){const[prompt,setPrompt]=useState(null);useEffect(()=>{const fn=e=>{e.preventDefault();setPrompt(e)};window.addEventListener('beforeinstallprompt',fn);return()=>window.removeEventListener('beforeinstallprompt',fn)},[]);if(!prompt)return null;return <button className="install-button" onClick={async()=>{await prompt.prompt();setPrompt(null)}}>Install app</button>}
function Header(){const[open,setOpen]=useState(false);return <header className="site-header"><div className="shell nav"><Brand/><nav className={open?'open':''}><Link to="/tools" onClick={()=>setOpen(false)}>All tools</Link><Link to="/tools/workspace" onClick={()=>setOpen(false)}>Workspace</Link><a href="/#categories" onClick={()=>setOpen(false)}>Categories</a><a href="/#privacy" onClick={()=>setOpen(false)}>Privacy</a><InstallButton/><a href="https://github.com/jmqbataller/deskora" target="_blank" rel="noreferrer"><Github size={17}/> GitHub</a></nav><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button></div></header>}

function ToolCard({tool}){const Icon=tool.icon,[fav,setFav]=useState(()=>{try{return JSON.parse(localStorage.getItem('deskora-favorites')||'[]').includes(tool.id)}catch{return false}});function toggle(e){e.preventDefault();e.stopPropagation();let list=[];try{list=JSON.parse(localStorage.getItem('deskora-favorites')||'[]')}catch{}list=fav?list.filter(x=>x!==tool.id):[tool.id,...list.filter(x=>x!==tool.id)].slice(0,24);localStorage.setItem('deskora-favorites',JSON.stringify(list));setFav(!fav)}return <div className="tool-card"><div className="tool-card-top"><span className="tool-icon"><Icon size={21}/></span><div className="card-actions">{tool.badge&&<span className="badge">{tool.badge}</span>}<button className={`favorite-button ${fav?'active':''}`} onClick={toggle} title="Favorite">★</button></div></div><Link className="tool-card-link" to={`/tools/${tool.id}`}><h3>{tool.name}</h3><p>{tool.desc}</p><span className="tool-open">Open tool <ChevronRight size={15}/></span></Link></div>}

function actionSet(file){const n=file?.name?.toLowerCase()||'',t=file?.type||'';if(t==='application/pdf'||n.endsWith('.pdf'))return[['Edit','edit-pdf'],['Compress','pdf-compressor'],['Organize','pdf-organizer'],['Redact','pdf-redactor'],['To images','pdf-to-image'],['Extract text','pdf-to-word']];if(t.startsWith('image/'))return[['Scan','camera-scanner'],['OCR','ocr-text'],['Compress','compress-image'],['To PDF','images-to-pdf'],['Strip metadata','image-metadata'],['ID sheet','id-picture']];if(t.startsWith('video/'))return[['Compress','video-compressor'],['Trim','video-trim'],['Resize social','video-social-resize'],['GIF','gif-maker'],['Capture frame','video-frame'],['Watermark','watermark-center']];if(/\.(xlsx?|csv)$/.test(n))return[['Clean','csv-cleaner'],['Duplicates','spreadsheet-duplicates'],['Compare','spreadsheet-compare'],['Merge','excel-merge'],['Split','excel-split']];if(n.endsWith('.zip'))return[['Extract ZIP','zip-extractor'],['Hash','file-hash']];return[['Hash','file-hash'],['Compare','file-compare'],['Rename','smart-rename']]}
function QuickDrop(){const[over,setOver]=useState(false),[file,setFile]=useState(null);function choose(f){if(f){window.__deskoraQuickFile=f;setFile(f)}}const actions=file?actionSet(file):[];return <div className="stack quick-action-stack"><div className={`quick-drop ${over?'is-over':''}`} onDragOver={e=>{e.preventDefault();setOver(true)}} onDragLeave={()=>setOver(false)} onDrop={e=>{e.preventDefault();setOver(false);choose(e.dataTransfer.files[0])}}><span className="quick-drop-icon"><Zap size={20}/></span><div><strong>Universal file actions</strong><span>{file?`${file.name} — choose what to do next.`:'Drop a file and Deskora will show compatible actions.'}</span></div><label className="browse-button">Choose file<input type="file" onChange={e=>choose(e.target.files[0])}/></label></div>{actions.length>0&&<div className="quick-actions">{actions.map(([label,id])=><Link key={id} className="secondary" to={`/tools/${id}`}>{label}</Link>)}</div>}</div>}

function CommandPalette(){const nav=useNavigate(),[open,setOpen]=useState(false),[q,setQ]=useState('');useEffect(()=>{const fn=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(v=>!v)}if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[]);const list=tools.filter(t=>(t.name+' '+t.desc).toLowerCase().includes(q.toLowerCase())).slice(0,12);if(!open)return <button className="command-trigger" onClick={()=>setOpen(true)}>⌘ / Ctrl K</button>;return <div className="command-overlay" onMouseDown={()=>setOpen(false)}><div className="command-box" onMouseDown={e=>e.stopPropagation()}><div className="search-box"><Search size={18}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search Deskora tools…"/></div><div className="command-results">{list.map(t=><button key={t.id} onClick={()=>{nav(`/tools/${t.id}`);setOpen(false);setQ('')}}><strong>{t.name}</strong><span>{t.category}</span></button>)}</div></div></div>}

function Home(){const [q,setQ]=useState('');const matches=useMemo(()=>q?tools.filter(t=>(t.name+' '+t.desc+' '+t.category).toLowerCase().includes(q.toLowerCase())).slice(0,8):tools.filter(t=>t.badge).slice(0,8),[q]);return <main>
  <section className="hero shell"><div className="hero-copy"><span className="hero-pill"><Sparkles size={15}/> Everyday tools for work</span><h1>One clean workspace for the files you deal with every day.</h1><p>Scan and edit documents, OCR paper files, compress media, clean spreadsheets, organize files, generate codes, and handle everyday IT tasks — directly in your browser.</p><div className="hero-actions"><Link className="primary large" to="/tools">Explore all tools <ArrowRight size={18}/></Link><Link className="secondary large" to="/tools/workflow-builder">Build a workflow</Link></div><div className="trust-row"><span><Check size={15}/> No account</span><span><Check size={15}/> No Deskora file storage</span><span><Check size={15}/> Browser-first</span></div></div>
  <div className="hero-panel"><div className="panel-top"><span>Find a tool</span><small>{tools.length} tools available</small></div><div className="search-box"><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search PDF, scanner, video, Excel, IP…"/></div><div className="mini-tools">{matches.map(t=>{const Icon=t.icon;return <Link key={t.id} to={`/tools/${t.id}`}><span className="tool-icon tiny"><Icon size={17}/></span><span><strong>{t.name}</strong><small>{t.category}</small></span><ChevronRight size={16}/></Link>})}</div></div></section>
  <div className="shell"><QuickDrop/></div>
  <section className="section shell" id="categories"><div className="section-heading"><div><span className="eyebrow">Built for real work</span><h2>Tools organized around your workflow</h2></div><Link to="/tools">View all tools <ArrowRight size={17}/></Link></div><div className="category-grid">{categories.map(c=>{const Icon=c.icon;const count=tools.filter(t=>t.category===c.id).length;return <Link to={`/tools?category=${c.id}`} className="category-card" key={c.id}><span className="category-icon"><Icon size={23}/></span><div><h3>{c.label}</h3><p>{count} tool{count===1?'':'s'}</p></div><ChevronRight size={18}/></Link>})}</div></section>
  <section className="section shell"><div className="section-heading"><div><span className="eyebrow">Popular</span><h2>Start with the essentials</h2></div></div><div className="tools-grid">{tools.filter(t=>t.badge).slice(0,12).map(t=><ToolCard key={t.id} tool={t}/>)}</div></section>
  <section className="privacy-section" id="privacy"><div className="shell privacy-grid"><div><span className="hero-pill"><ShieldCheck size={15}/> Privacy-first by design</span><h2>Your files stay on your device for supported tools.</h2><p>Deskora is designed around browser-side processing. Common PDF, scanner, image, media, file, office and utility tasks can run without sending your files to a Deskora storage server.</p></div><div className="privacy-cards"><div><LockKeyhole/><strong>Local processing</strong><span>Core file operations happen in your browser.</span></div><div><Zap/><strong>Workflow tools</strong><span>Favorites, recent tools and guided chains stay on this device.</span></div><div><ShieldCheck/><strong>No account needed</strong><span>Open a tool, process your file, download the result.</span></div></div></div></section>
  <section className="cta shell"><div><span className="eyebrow">Deskora workspace</span><h2>Replace scattered converter sites with one reliable toolkit.</h2><p>PDF, scanner, OCR, image, video, audio, office, file, IT, developer and printing utilities in one responsive interface.</p></div><Link className="primary large" to="/tools">Open Deskora <ArrowRight size={18}/></Link></section>
</main>}

function ToolsIndex(){const params=new URLSearchParams(window.location.search);const initial=params.get('category')||'all';const[cat,setCat]=useState(initial),[q,setQ]=useState('');const filtered=tools.filter(t=>(cat==='all'||t.category===cat)&&(!q||(t.name+' '+t.desc).toLowerCase().includes(q.toLowerCase())));return <main className="shell tools-page"><div className="page-heading"><span className="eyebrow">Tool library</span><h1>Everything in Deskora</h1><p>Choose a tool, favorite the ones you use often, or press Ctrl+K anywhere to jump directly to a tool.</p></div><div className="library-bar"><div className="search-box"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search tools…"/></div><div className="filter-row"><button className={cat==='all'?'active':''} onClick={()=>setCat('all')}>All</button>{categories.map(c=><button className={cat===c.id?'active':''} onClick={()=>setCat(c.id)} key={c.id}>{c.label}</button>)}</div></div><div className="tools-grid">{filtered.map(t=><ToolCard key={t.id} tool={t}/>)}</div>{!filtered.length&&<div className="empty-state">No tools match your search.</div>}</main>}

function ToolPage(){const{id}=useParams();const tool=toolMap[id],Comp=toolComponents[id];useEffect(()=>{if(!tool)return;let list=[];try{list=JSON.parse(localStorage.getItem('deskora-recent')||'[]')}catch{}list=[id,...list.filter(x=>x!==id)].slice(0,12);localStorage.setItem('deskora-recent',JSON.stringify(list))},[id,tool]);if(!tool||!Comp)return <main className="shell not-found"><h1>Tool not found</h1><Link className="primary" to="/tools">Back to tools</Link></main>;return <ToolShell tool={tool}><Comp/></ToolShell>}

function Footer(){return <footer><div className="shell footer-grid"><div><Brand/><p>Privacy-first everyday tools for work.</p></div><div><strong>Deskora</strong><Link to="/tools">All tools</Link><Link to="/tools/workspace">Workspace</Link><Link to="/tools/workflow-builder">Workflows</Link></div><div><strong>Project</strong><a href="https://github.com/jmqbataller/deskora" target="_blank" rel="noreferrer">GitHub</a><span>Built for Vercel</span></div></div><div className="shell footer-bottom">© {new Date().getFullYear()} Deskora. Files are processed locally where supported.</div></footer>}

export default function App(){return <><Header/><CommandPalette/><Routes><Route path="/" element={<Home/>}/><Route path="/tools" element={<ToolsIndex/>}/><Route path="/tools/:id" element={<ToolPage/>}/></Routes><Footer/></>}
