import { useEffect, useMemo, useState } from 'react'
import { Link, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { ArrowRight, Check, ChevronRight, Files, Github, LockKeyhole, Menu, Moon, Search, ShieldCheck, Sparkles, Sun, X, Zap } from 'lucide-react'
import { categories, toolMap as baseToolMap, tools as baseTools } from './data-tools'
import { productivityTools } from './productivity-tools'
import ToolShell from './components/ToolShell'
import { PdfToImage, ImagesToPdf, MergePdf, SplitPdf, RotatePdf } from './tools/PdfTools'
import { ConvertImage, CompressImage, ResizeImage, BatchImages } from './tools/ImageTools'
import { VideoCompressor, VideoSpeed, VideoTrim, VideoAudio } from './tools/VideoTools'
import { CsvCleaner, TextCompare, EmailCleaner, QrGenerator, BarcodeGenerator } from './tools/OfficeTools'
import { ZipCreator, ZipExtractor, FileHash, FileCompare, SubnetCalculator, PasswordGenerator, JsonTools, Base64Tools, DpiCalculator, PaperSize } from './tools/UtilityTools'
import { CameraScanner, PdfEditor } from './tools/DeskoraExtras'
import { PdfOrganizer, PdfCompressor, OcrToText, ReceiptScanner, BusinessCardScanner, SearchablePdf, PdfToWordText, PdfMetadataCleaner, PdfRedactor, SignatureMaker, IdPictureMaker, DateStampGenerator, PdfPasswordTool } from './tools/DocumentExpansion'
import { SpreadsheetDuplicateFinder, SpreadsheetCompare, ExcelMerge, ExcelSplitter, SmartRename, BulkOrganizer, DuplicateFileFinder, ImageMetadataCleaner, NumberToWords, VatCalculator, WorkdaysCalculator, CodeScanner, MeetingTranscriber } from './tools/OfficeExpansion'
import { VideoSocialResize, VideoFrameExtractor, GifMaker, AudioStudio, WatermarkCenter } from './tools/MediaExpansion'
import { WorkflowBuilder } from './tools/WorkspaceTools'
import { SmartDashboard, FileAnalyzer, TargetSizeCompressor, PipelineCenter, BatchProcessingCenter, OcrWorkspace, ExpenseWorkspace, AssetLabelGenerator, InventoryHelper, TemplateCenter, BatchPdfOperations, MultiFileWorkspace } from './tools/ProductivitySuite'

const tools=[...baseTools,...productivityTools]
const toolMap={...baseToolMap,...Object.fromEntries(productivityTools.map(t=>[t.id,t]))}

const toolComponents={
  'pdf-to-image':PdfToImage,'edit-pdf':PdfEditor,'pdf-form-filler':PdfEditor,'pdf-organizer':PdfOrganizer,'pdf-compressor':PdfCompressor,'pdf-redactor':PdfRedactor,'pdf-to-word':PdfToWordText,'pdf-metadata':PdfMetadataCleaner,'pdf-password':PdfPasswordTool,'searchable-pdf':SearchablePdf,'images-to-pdf':ImagesToPdf,'merge-pdf':MergePdf,'split-pdf':SplitPdf,'rotate-pdf':RotatePdf,
  'convert-image':ConvertImage,'compress-image':CompressImage,'resize-image':ResizeImage,'batch-images':BatchImages,'image-metadata':ImageMetadataCleaner,'signature-maker':SignatureMaker,'watermark-center':WatermarkCenter,
  'video-compressor':VideoCompressor,'video-speed':VideoSpeed,'video-trim':VideoTrim,'video-audio':VideoAudio,'video-social-resize':VideoSocialResize,'video-frame':VideoFrameExtractor,'gif-maker':GifMaker,'audio-studio':AudioStudio,
  'camera-scanner':CameraScanner,'ocr-text':OcrToText,'receipt-scanner':ReceiptScanner,'business-card-scanner':BusinessCardScanner,'csv-cleaner':CsvCleaner,'spreadsheet-duplicates':SpreadsheetDuplicateFinder,'spreadsheet-compare':SpreadsheetCompare,'excel-merge':ExcelMerge,'excel-split':ExcelSplitter,'text-compare':TextCompare,'email-cleaner':EmailCleaner,'qr-generator':QrGenerator,'barcode-generator':BarcodeGenerator,'code-scanner':CodeScanner,'meeting-transcriber':MeetingTranscriber,'number-to-words':NumberToWords,'vat-calculator':VatCalculator,'workdays-calculator':WorkdaysCalculator,'workflow-builder':WorkflowBuilder,'workspace':SmartDashboard,
  'zip-creator':ZipCreator,'zip-extractor':ZipExtractor,'file-hash':FileHash,'file-compare':FileCompare,'smart-rename':SmartRename,'bulk-organizer':BulkOrganizer,'duplicate-files':DuplicateFileFinder,'subnet-calculator':SubnetCalculator,
  'password-generator':PasswordGenerator,'json-tools':JsonTools,'base64-tools':Base64Tools,'dpi-calculator':DpiCalculator,'paper-size':PaperSize,'id-picture':IdPictureMaker,'date-stamp':DateStampGenerator,
  'file-analyzer':FileAnalyzer,'pipeline-center':PipelineCenter,'batch-center':BatchProcessingCenter,'target-compression':TargetSizeCompressor,'ocr-workspace':OcrWorkspace,'expense-workspace':ExpenseWorkspace,'asset-labels':AssetLabelGenerator,'inventory-helper':InventoryHelper,'template-center':TemplateCenter,'batch-pdf':BatchPdfOperations,'multi-file-workspace':MultiFileWorkspace,'smart-dashboard':SmartDashboard,
}

function Brand(){return <Link className="brand" to="/"><span className="brand-mark"><Files size={19}/></span><span>Deskora</span></Link>}

function InstallButton(){const[prompt,setPrompt]=useState(null);useEffect(()=>{const fn=e=>{e.preventDefault();setPrompt(e)};window.addEventListener('beforeinstallprompt',fn);return()=>window.removeEventListener('beforeinstallprompt',fn)},[]);if(!prompt)return null;return <button className="install-button" onClick={async()=>{await prompt.prompt();setPrompt(null)}}>Install app</button>}
function ThemeButton(){const[dark,setDark]=useState(()=>localStorage.getItem('deskora-theme')==='dark');useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('deskora-theme',dark?'dark':'light')},[dark]);return <button className="theme-button" onClick={()=>setDark(v=>!v)} aria-label="Toggle dark mode">{dark?<Sun size={15}/>:<Moon size={15}/>} {dark?'Light':'Dark'}</button>}
function Header(){const[open,setOpen]=useState(false);return <header className="site-header"><div className="shell nav"><Brand/><nav className={open?'open':''}><Link to="/tools" onClick={()=>setOpen(false)}>All tools</Link><Link to="/tools/workspace" onClick={()=>setOpen(false)}>Workspace</Link><Link to="/tools/template-center" onClick={()=>setOpen(false)}>Presets</Link><a href="/#categories" onClick={()=>setOpen(false)}>Categories</a><InstallButton/><ThemeButton/><a href="https://github.com/jmqbataller/deskora" target="_blank" rel="noreferrer"><Github size={17}/> GitHub</a></nav><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button></div></header>}

function UpdateNotice(){const[waiting,setWaiting]=useState(null);useEffect(()=>{if(!('serviceWorker'in navigator))return;navigator.serviceWorker.ready.then(reg=>{if(reg.waiting)setWaiting(reg.waiting);reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)setWaiting(w)})})}).catch(()=>{})},[]);if(!waiting)return null;return <div className="update-toast"><span>A new Deskora version is ready.</span><button onClick={()=>{waiting.postMessage({type:'SKIP_WAITING'});location.reload()}}>Update</button></div>}

function ToolCard({tool}){const Icon=tool.icon,[fav,setFav]=useState(()=>{try{return JSON.parse(localStorage.getItem('deskora-favorites')||'[]').includes(tool.id)}catch{return false}});function toggle(e){e.preventDefault();e.stopPropagation();let list=[];try{list=JSON.parse(localStorage.getItem('deskora-favorites')||'[]')}catch{}list=fav?list.filter(x=>x!==tool.id):[tool.id,...list.filter(x=>x!==tool.id)].slice(0,24);localStorage.setItem('deskora-favorites',JSON.stringify(list));setFav(!fav)}return <div className="tool-card"><div className="tool-card-top"><span className="tool-icon"><Icon size={21}/></span><div className="card-actions">{tool.badge&&<span className="badge">{tool.badge}</span>}<button className={`favorite-button ${fav?'active':''}`} onClick={toggle} title="Favorite">★</button></div></div><Link className="tool-card-link" to={`/tools/${tool.id}`}><h3>{tool.name}</h3><p>{tool.desc}</p><span className="tool-open">Open tool <ChevronRight size={15}/></span></Link></div>}

function actionSet(file){const n=file?.name?.toLowerCase()||'',t=file?.type||'';if(t==='application/pdf'||n.endsWith('.pdf'))return[['Analyze','file-analyzer'],['Target size','target-compression'],['Edit','edit-pdf'],['Batch PDF','batch-pdf'],['Organize','pdf-organizer'],['OCR','ocr-workspace']];if(t.startsWith('image/'))return[['Analyze','file-analyzer'],['Target size','target-compression'],['Scan','camera-scanner'],['OCR','ocr-workspace'],['To PDF','images-to-pdf'],['ID sheet','id-picture']];if(t.startsWith('video/'))return[['Analyze','file-analyzer'],['Compress','video-compressor'],['Trim','video-trim'],['Resize social','video-social-resize'],['GIF','gif-maker']];if(/\.(xlsx?|csv)$/.test(n))return[['Analyze','file-analyzer'],['Inventory','inventory-helper'],['Clean','csv-cleaner'],['Duplicates','spreadsheet-duplicates'],['Compare','spreadsheet-compare']];if(n.endsWith('.zip'))return[['Analyze','file-analyzer'],['Extract ZIP','zip-extractor'],['Hash','file-hash']];return[['Analyze','file-analyzer'],['Hash','file-hash'],['Compare','file-compare'],['Rename','smart-rename']]}
function QuickDrop(){const[over,setOver]=useState(false),[file,setFile]=useState(null);function choose(f){if(f){window.__deskoraQuickFile=f;setFile(f)}}const actions=file?actionSet(file):[];return <div className="stack quick-action-stack"><div className={`quick-drop ${over?'is-over':''}`} onDragOver={e=>{e.preventDefault();setOver(true)}} onDragLeave={()=>setOver(false)} onDrop={e=>{e.preventDefault();setOver(false);choose(e.dataTransfer.files[0])}}><span className="quick-drop-icon"><Zap size={20}/></span><div><strong>Universal file actions</strong><span>{file?`${file.name} — choose what to do next.`:'Drop a file and Deskora will show compatible actions.'}</span></div><label className="browse-button">Choose file<input type="file" onChange={e=>choose(e.target.files[0])}/></label></div>{actions.length>0&&<div className="quick-actions">{actions.map(([label,id])=><Link key={id} className="secondary" to={`/tools/${id}`}>{label}</Link>)}</div>}</div>}

const aliases={
 'compress pdf 5mb':'target-compression','compress pdf':'pdf-compressor','scan document':'camera-scanner','scan receipt':'expense-workspace','receipt expense':'expense-workspace','resize image':'resize-image','resize video':'video-social-resize','batch files':'batch-center','batch pdf':'batch-pdf','inventory labels':'inventory-helper','asset labels':'asset-labels','ocr':'ocr-workspace','dashboard':'smart-dashboard','workflow':'pipeline-center','analyze file':'file-analyzer','id photo':'id-picture'
}
function CommandPalette(){const nav=useNavigate(),[open,setOpen]=useState(false),[q,setQ]=useState('');useEffect(()=>{const fn=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(v=>!v)}if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[]);const clean=q.trim().toLowerCase(),direct=Object.entries(aliases).filter(([a])=>a.includes(clean)||clean.includes(a)).map(([,id])=>toolMap[id]).filter(Boolean),list=[...direct,...tools.filter(t=>(t.name+' '+t.desc+' '+t.category).toLowerCase().includes(clean))].filter((t,i,a)=>t&&a.findIndex(x=>x.id===t.id)===i).slice(0,12);if(!open)return <button className="command-trigger" onClick={()=>setOpen(true)}>⌘ / Ctrl K</button>;return <div className="command-overlay" onMouseDown={()=>setOpen(false)}><div className="command-box" onMouseDown={e=>e.stopPropagation()}><div className="search-box"><Search size={18}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Try: compress pdf 5mb, scan receipt, asset labels…"/></div><div className="command-results">{list.map(t=><button key={t.id} onClick={()=>{nav(`/tools/${t.id}`);setOpen(false);setQ('')}}><strong>{t.name}</strong><span>{t.category}</span></button>)}</div></div></div>}

function Home(){const[q,setQ]=useState('');const matches=useMemo(()=>q?tools.filter(t=>(t.name+' '+t.desc+' '+t.category).toLowerCase().includes(q.toLowerCase())).slice(0,8):tools.filter(t=>t.badge).slice(0,8),[q]);return <main>
  <section className="hero shell"><div className="hero-copy"><span className="hero-pill"><Sparkles size={15}/> Everyday tools for work</span><h1>One clean workspace for the files you deal with every day.</h1><p>Scan, edit, OCR, compress, batch-process and organize office files — with local workflows, presets and reusable shortcuts.</p><div className="hero-actions"><Link className="primary large" to="/tools">Explore all tools <ArrowRight size={18}/></Link><Link className="secondary large" to="/tools/pipeline-center">Run a workflow</Link><Link className="secondary large" to="/tools/smart-dashboard">Open dashboard</Link></div><div className="trust-row"><span><Check size={15}/> No account</span><span><Check size={15}/> No Deskora file storage</span><span><Check size={15}/> Browser-first</span></div></div>
  <div className="hero-panel"><div className="panel-top"><span>Find a tool</span><small>{tools.length} tools available</small></div><div className="search-box"><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search PDF, scanner, video, Excel, IP…"/></div><div className="mini-tools">{matches.map(t=>{const Icon=t.icon;return <Link key={t.id} to={`/tools/${t.id}`}><span className="tool-icon tiny"><Icon size={17}/></span><span><strong>{t.name}</strong><small>{t.category}</small></span><ChevronRight size={16}/></Link>})}</div></div></section>
  <div className="shell"><QuickDrop/></div>
  <section className="section shell" id="categories"><div className="section-heading"><div><span className="eyebrow">Built for real work</span><h2>Tools organized around your workflow</h2></div><Link to="/tools">View all tools <ArrowRight size={17}/></Link></div><div className="category-grid">{categories.map(c=>{const Icon=c.icon,count=tools.filter(t=>t.category===c.id).length;return <Link to={`/tools?category=${c.id}`} className="category-card" key={c.id}><span className="category-icon"><Icon size={23}/></span><div><h3>{c.label}</h3><p>{count} tool{count===1?'':'s'}</p></div><ChevronRight size={18}/></Link>})}</div></section>
  <section className="section shell"><div className="section-heading"><div><span className="eyebrow">Productivity suite</span><h2>Workflows, batches and office workspaces</h2></div></div><div className="tools-grid">{productivityTools.slice(0,12).map(t=><ToolCard key={t.id} tool={t}/>)}</div></section>
  <section className="privacy-section" id="privacy"><div className="shell privacy-grid"><div><span className="hero-pill"><ShieldCheck size={15}/> Privacy-first by design</span><h2>Your files stay on your device for supported tools.</h2><p>Deskora is designed around browser-side processing. Favorites, presets, history and workflow settings use local browser storage rather than a Deskora account database.</p></div><div className="privacy-cards"><div><LockKeyhole/><strong>Local processing</strong><span>Core file operations happen in your browser.</span></div><div><Zap/><strong>Productivity workflows</strong><span>Chain operations and batch compatible files without repeated uploads.</span></div><div><ShieldCheck/><strong>No account needed</strong><span>Open a tool, process your file, download the result.</span></div></div></div></section>
</main>}

function ToolsIndex(){const params=new URLSearchParams(window.location.search),initial=params.get('category')||'all';const[cat,setCat]=useState(initial),[q,setQ]=useState('');const filtered=tools.filter(t=>(cat==='all'||t.category===cat)&&(!q||(t.name+' '+t.desc).toLowerCase().includes(q.toLowerCase())));return <main className="shell tools-page"><div className="page-heading"><span className="eyebrow">Tool library</span><h1>Everything in Deskora</h1><p>Favorite tools, use presets, or press Ctrl+K and type what you want to do.</p></div><div className="library-bar"><div className="search-box"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search tools…"/></div><div className="filter-row"><button className={cat==='all'?'active':''} onClick={()=>setCat('all')}>All</button>{categories.map(c=><button className={cat===c.id?'active':''} onClick={()=>setCat(c.id)} key={c.id}>{c.label}</button>)}</div></div><div className="tools-grid">{filtered.map(t=><ToolCard key={t.id} tool={t}/>)}</div>{!filtered.length&&<div className="empty-state">No tools match your search.</div>}</main>}

function ToolPage(){const{id}=useParams(),tool=toolMap[id],Comp=toolComponents[id];useEffect(()=>{if(!tool)return;let list=[];try{list=JSON.parse(localStorage.getItem('deskora-recent')||'[]')}catch{}list=[id,...list.filter(x=>x!==id)].slice(0,12);localStorage.setItem('deskora-recent',JSON.stringify(list))},[id,tool]);if(!tool||!Comp)return <main className="shell not-found"><h1>Tool not found</h1><Link className="primary" to="/tools">Back to tools</Link></main>;return <ToolShell tool={tool}><Comp/></ToolShell>}

function Footer(){return <footer><div className="shell footer-grid"><div><Brand/><p>Privacy-first everyday tools for work.</p></div><div><strong>Deskora</strong><Link to="/tools">All tools</Link><Link to="/tools/smart-dashboard">Dashboard</Link><Link to="/tools/pipeline-center">Tool chaining</Link><Link to="/tools/template-center">Presets</Link></div><div><strong>Project</strong><a href="https://github.com/jmqbataller/deskora" target="_blank" rel="noreferrer">GitHub</a><span>Built for Vercel</span></div></div><div className="shell footer-bottom">© {new Date().getFullYear()} Deskora. Files are processed locally where supported.</div></footer>}

export default function App(){return <><Header/><CommandPalette/><UpdateNotice/><Routes><Route path="/" element={<Home/>}/><Route path="/tools" element={<ToolsIndex/>}/><Route path="/tools/:id" element={<ToolPage/>}/></Routes><Footer/></>}
