import { useMemo, useState } from 'react'
import { Link, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { ArrowRight, Check, ChevronRight, Files, Github, LockKeyhole, Menu, Search, ShieldCheck, Sparkles, X, Zap } from 'lucide-react'
import { categories, toolMap, tools } from './data-tools'
import ToolShell from './components/ToolShell'
import { PdfToImage, ImagesToPdf, MergePdf, SplitPdf, RotatePdf } from './tools/PdfTools'
import { ConvertImage, CompressImage, ResizeImage, BatchImages } from './tools/ImageTools'
import { VideoCompressor, VideoSpeed, VideoTrim, VideoAudio } from './tools/VideoTools'
import { CsvCleaner, TextCompare, EmailCleaner, QrGenerator, BarcodeGenerator } from './tools/OfficeTools'
import { ZipCreator, ZipExtractor, FileHash, FileCompare, SubnetCalculator, PasswordGenerator, JsonTools, Base64Tools, DpiCalculator, PaperSize } from './tools/UtilityTools'

const toolComponents={
  'pdf-to-image':PdfToImage,'images-to-pdf':ImagesToPdf,'merge-pdf':MergePdf,'split-pdf':SplitPdf,'rotate-pdf':RotatePdf,
  'convert-image':ConvertImage,'compress-image':CompressImage,'resize-image':ResizeImage,'batch-images':BatchImages,
  'video-compressor':VideoCompressor,'video-speed':VideoSpeed,'video-trim':VideoTrim,'video-audio':VideoAudio,
  'csv-cleaner':CsvCleaner,'text-compare':TextCompare,'email-cleaner':EmailCleaner,'qr-generator':QrGenerator,'barcode-generator':BarcodeGenerator,
  'zip-creator':ZipCreator,'zip-extractor':ZipExtractor,'file-hash':FileHash,'file-compare':FileCompare,'subnet-calculator':SubnetCalculator,
  'password-generator':PasswordGenerator,'json-tools':JsonTools,'base64-tools':Base64Tools,'dpi-calculator':DpiCalculator,'paper-size':PaperSize,
}

function Brand(){return <Link className="brand" to="/"><span className="brand-mark"><Files size={19}/></span><span>Deskora</span></Link>}

function Header(){const[open,setOpen]=useState(false);return <header className="site-header"><div className="shell nav"><Brand/><nav className={open?'open':''}><Link to="/tools" onClick={()=>setOpen(false)}>All tools</Link><a href="/#categories" onClick={()=>setOpen(false)}>Categories</a><a href="/#privacy" onClick={()=>setOpen(false)}>Privacy</a><a href="https://github.com/jmqbataller/deskora" target="_blank" rel="noreferrer"><Github size={17}/> GitHub</a></nav><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button></div></header>}

function ToolCard({tool}){const Icon=tool.icon;return <Link to={`/tools/${tool.id}`} className="tool-card"><div className="tool-card-top"><span className="tool-icon"><Icon size={21}/></span>{tool.badge&&<span className="badge">{tool.badge}</span>}</div><h3>{tool.name}</h3><p>{tool.desc}</p><span className="tool-open">Open tool <ChevronRight size={15}/></span></Link>}

function QuickDrop(){const nav=useNavigate();const[over,setOver]=useState(false);function route(file){if(!file)return;const n=file.name.toLowerCase(),t=file.type;if(t==='application/pdf'||n.endsWith('.pdf'))nav('/tools/pdf-to-image');else if(t.startsWith('image/'))nav('/tools/convert-image');else if(t.startsWith('video/'))nav('/tools/video-compressor');else if(n.endsWith('.zip'))nav('/tools/zip-extractor');else if(n.endsWith('.csv')||n.endsWith('.xlsx')||n.endsWith('.xls'))nav('/tools/csv-cleaner');else nav('/tools/file-hash')}return <div className={`quick-drop ${over?'is-over':''}`} onDragOver={e=>{e.preventDefault();setOver(true)}} onDragLeave={()=>setOver(false)} onDrop={e=>{e.preventDefault();setOver(false);route(e.dataTransfer.files[0])}}><span className="quick-drop-icon"><Zap size={20}/></span><div><strong>Quick action</strong><span>Drop a file here and Deskora will suggest the right tool.</span></div><label className="browse-button">Choose file<input type="file" onChange={e=>route(e.target.files[0])}/></label></div>}

function Home(){const [q,setQ]=useState('');const matches=useMemo(()=>q?tools.filter(t=>(t.name+' '+t.desc+' '+t.category).toLowerCase().includes(q.toLowerCase())).slice(0,8):tools.filter(t=>t.badge).slice(0,8),[q]);return <main>
  <section className="hero shell"><div className="hero-copy"><span className="hero-pill"><Sparkles size={15}/> Everyday tools for work</span><h1>One clean workspace for the files you deal with every day.</h1><p>Convert PDFs, compress videos, clean spreadsheets, generate QR codes, and handle everyday IT tasks — directly in your browser.</p><div className="hero-actions"><Link className="primary large" to="/tools">Explore all tools <ArrowRight size={18}/></Link><a className="secondary large" href="#categories">Browse categories</a></div><div className="trust-row"><span><Check size={15}/> No account</span><span><Check size={15}/> No file storage</span><span><Check size={15}/> Browser-first</span></div></div>
  <div className="hero-panel"><div className="panel-top"><span>Find a tool</span><small>{tools.length} tools available</small></div><div className="search-box"><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search PDF, video, IP, QR…"/></div><div className="mini-tools">{matches.map(t=>{const Icon=t.icon;return <Link key={t.id} to={`/tools/${t.id}`}><span className="tool-icon tiny"><Icon size={17}/></span><span><strong>{t.name}</strong><small>{t.category}</small></span><ChevronRight size={16}/></Link>})}</div></div></section>
  <div className="shell"><QuickDrop/></div>
  <section className="section shell" id="categories"><div className="section-heading"><div><span className="eyebrow">Built for real work</span><h2>Tools organized around your workflow</h2></div><Link to="/tools">View all tools <ArrowRight size={17}/></Link></div><div className="category-grid">{categories.map(c=>{const Icon=c.icon;const count=tools.filter(t=>t.category===c.id).length;return <Link to={`/tools?category=${c.id}`} className="category-card" key={c.id}><span className="category-icon"><Icon size={23}/></span><div><h3>{c.label}</h3><p>{count} tool{count===1?'':'s'}</p></div><ChevronRight size={18}/></Link>})}</div></section>
  <section className="section shell"><div className="section-heading"><div><span className="eyebrow">Popular</span><h2>Start with the essentials</h2></div></div><div className="tools-grid">{tools.filter(t=>t.badge).slice(0,8).map(t=><ToolCard key={t.id} tool={t}/>)}</div></section>
  <section className="privacy-section" id="privacy"><div className="shell privacy-grid"><div><span className="hero-pill"><ShieldCheck size={15}/> Privacy-first by design</span><h2>Your files stay on your device for supported tools.</h2><p>Deskora is designed around browser-side processing. That means common PDF, image, file, office and utility tasks can run without sending your files to a Deskora storage server.</p></div><div className="privacy-cards"><div><LockKeyhole/><strong>Local processing</strong><span>Core file operations happen in your browser.</span></div><div><Zap/><strong>Fast workflow</strong><span>No upload queue before common conversions.</span></div><div><ShieldCheck/><strong>No account needed</strong><span>Open a tool, process your file, download the result.</span></div></div></div></section>
  <section className="cta shell"><div><span className="eyebrow">Deskora workspace</span><h2>Replace scattered converter sites with one reliable toolkit.</h2><p>PDF, image, video, office, file, IT, developer and printing utilities in one responsive interface.</p></div><Link className="primary large" to="/tools">Open Deskora <ArrowRight size={18}/></Link></section>
</main>}

function ToolsIndex(){const params=new URLSearchParams(window.location.search);const initial=params.get('category')||'all';const[cat,setCat]=useState(initial),[q,setQ]=useState('');const filtered=tools.filter(t=>(cat==='all'||t.category===cat)&&(!q||(t.name+' '+t.desc).toLowerCase().includes(q.toLowerCase())));return <main className="shell tools-page"><div className="page-heading"><span className="eyebrow">Tool library</span><h1>Everything in Deskora</h1><p>Choose a tool and process your work directly from the browser.</p></div><div className="library-bar"><div className="search-box"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search tools…"/></div><div className="filter-row"><button className={cat==='all'?'active':''} onClick={()=>setCat('all')}>All</button>{categories.map(c=><button className={cat===c.id?'active':''} onClick={()=>setCat(c.id)} key={c.id}>{c.label}</button>)}</div></div><div className="tools-grid">{filtered.map(t=><ToolCard key={t.id} tool={t}/>)}</div>{!filtered.length&&<div className="empty-state">No tools match your search.</div>}</main>}

function ToolPage(){const{id}=useParams();const tool=toolMap[id],Comp=toolComponents[id];if(!tool||!Comp)return <main className="shell not-found"><h1>Tool not found</h1><Link className="primary" to="/tools">Back to tools</Link></main>;return <ToolShell tool={tool}><Comp/></ToolShell>}

function Footer(){return <footer><div className="shell footer-grid"><div><Brand/><p>Privacy-first everyday tools for work.</p></div><div><strong>Deskora</strong><Link to="/tools">All tools</Link><a href="/#privacy">Privacy</a></div><div><strong>Project</strong><a href="https://github.com/jmqbataller/deskora" target="_blank" rel="noreferrer">GitHub</a><span>Built for Vercel</span></div></div><div className="shell footer-bottom">© {new Date().getFullYear()} Deskora. Files are processed locally where supported.</div></footer>}

export default function App(){return <><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/tools" element={<ToolsIndex/>}/><Route path="/tools/:id" element={<ToolPage/>}/></Routes><Footer/></>}
