import { useMemo, useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { ArrowLeft, ChevronRight, Search, ShieldCheck, Wrench } from 'lucide-react'
import App from './App'
import { itToolsV2 } from './it-tools-pack-v2'
import { ITToolEngine } from './tools/ITToolsV2'

function Credit(){return <div className="deskora-dev-credit">Developed by <a href="https://jmqbataller.vercel.app/" target="_blank" rel="noreferrer">John Mark Bataller</a></div>}
function Brand(){return <Link className="itv2-brand" to="/"><img src="/deskora-icon.svg" alt="Deskora"/><span>Deskora</span></Link>}

function Hub(){const[q,setQ]=useState('');const list=useMemo(()=>itToolsV2.filter(t=>(t.name+' '+t.desc).toLowerCase().includes(q.toLowerCase())),[q]);return <main className="itv2-page"><header className="itv2-header"><div className="shell itv2-nav"><Brand/><div className="button-row compact"><Link className="secondary" to="/">Home</Link><Link className="secondary" to="/tools">All tools</Link></div></div></header><section className="shell itv2-hero"><span className="eyebrow">Deskora IT Hub</span><h1>Office IT, network and Windows support tools.</h1><p>Plan LANs, troubleshoot Windows PCs, build reviewed support commands, calculate network/storage/power requirements, and standardize common helpdesk work — all from one browser workspace.</p><div className="trust-row"><span><ShieldCheck size={15}/> Browser-first</span><span><ShieldCheck size={15}/> No account</span><span><ShieldCheck size={15}/> {itToolsV2.length} IT utilities</span></div><div className="itv2-search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search DHCP, DNS, printer, Wi-Fi, RDP, RAID…"/></div></section><section className="shell section"><div className="itv2-count">Showing <strong>{list.length}</strong> IT tools</div><div className="itv2-grid">{list.map(t=>{const Icon=t.icon;return <Link className="itv2-card" key={t.id} to={`/it-tools/${t.id}`}><div className="itv2-card-top"><span className="tool-icon"><Icon size={21}/></span>{t.badge&&<span className="badge">{t.badge}</span>}</div><h3>{t.name}</h3><p>{t.desc}</p><span className="tool-open">Open tool <ChevronRight size={15}/></span></Link>})}</div></section><Credit/></main>}

function ToolPage({id}){const tool=itToolsV2.find(t=>t.id===id);if(!tool)return <Hub/>;const Icon=tool.icon;return <main className="itv2-page"><header className="itv2-header"><div className="shell itv2-nav"><Brand/><div className="button-row compact"><Link className="secondary" to="/it-tools">IT Hub</Link><Link className="secondary" to="/tools">All tools</Link></div></div></header><section className="shell tool-page"><Link className="back-link" to="/it-tools"><ArrowLeft size={15}/> Back to IT Hub</Link><div className="tool-header"><span className="tool-icon large"><Icon size={28}/></span><div><span className="eyebrow">IT & Network</span><h1>{tool.name}</h1><p>{tool.desc}</p></div></div><div className="privacy-note"><ShieldCheck size={15}/> Runs locally where possible. Review generated commands and scripts before executing them.</div><div className="tool-workspace"><ITToolEngine/></div></section><Credit/></main>}

export default function EnhancedITApp(){const{pathname}=useLocation();if(pathname==='/it-tools')return <Hub/>;if(pathname.startsWith('/it-tools/'))return <ToolPage id={decodeURIComponent(pathname.split('/')[2]||'')}/>;return <><App/><Link className="itv2-launcher" to="/it-tools"><Wrench size={16}/> IT Tools</Link><Credit/></>}
