import { useMemo, useRef, useState } from 'react'
import { PDFDocument, StandardFonts, degrees, rgb } from 'pdf-lib'
import * as pdfjsLib from 'pdfjs-dist'
import pdfWorker from 'pdfjs-dist/build/pdf.worker.min.mjs?url'
import { createWorker } from 'tesseract.js'
import FileDrop from '../components/FileDrop'
import Status from '../components/Status'
import { downloadBlob, formatBytes, safeBaseName } from '../lib'

pdfjsLib.GlobalWorkerOptions.workerSrc = pdfWorker
const blobCanvas=(c,t='image/jpeg',q=.88)=>new Promise((r,j)=>c.toBlob(b=>b?r(b):j(new Error('Could not create image')),t,q))
const readUrl=f=>URL.createObjectURL(f)

async function renderPdfPage(doc,index,scale=1.45){const page=await doc.getPage(index+1),vp=page.getViewport({scale}),c=document.createElement('canvas');c.width=vp.width;c.height=vp.height;await page.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;return c}
async function ocrImage(input,lang='eng',onProgress){const worker=await createWorker(lang,1,{logger:m=>m.progress&&onProgress?.(Math.round(m.progress*100))});try{return (await worker.recognize(input)).data.text||''}finally{await worker.terminate()}}

export function PdfOrganizer(){
  const[file,setFile]=useState(null),[bytes,setBytes]=useState(null),[pages,setPages]=useState([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
  async function load(f){if(!f)return;setBusy(true);try{const b=await f.arrayBuffer(),pdf=await PDFDocument.load(b);setFile(f);setBytes(b);setPages(Array.from({length:pdf.getPageCount()},(_,i)=>({src:i,rot:0,key:`${i}-${Date.now()}-${Math.random()}`})));setMsg(`${pdf.getPageCount()} pages loaded.`)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
  const move=(i,d)=>setPages(p=>{const n=i+d;if(n<0||n>=p.length)return p;const x=[...p],[v]=x.splice(i,1);x.splice(n,0,v);return x})
  async function exportPdf(){setBusy(true);try{const src=await PDFDocument.load(bytes),out=await PDFDocument.create();for(const item of pages){const [p]=await out.copyPages(src,[item.src]);p.setRotation(degrees((p.getRotation().angle+item.rot)%360));out.addPage(p)}downloadBlob(new Blob([await out.save()],{type:'application/pdf'}),`${safeBaseName(file.name)}-organized.pdf`);setMsg('Organized PDF downloaded.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
  return <div className="stack"><FileDrop accept="application/pdf" onFiles={f=>load(f[0])}/>{file&&<div className="file-row"><span>{file.name}</span><small>{pages.length} pages</small></div>}<div className="organizer-list">{pages.map((p,i)=><div className="organizer-row" key={p.key}><strong>Page {p.src+1}</strong><span>{p.rot?`${p.rot}°`:''}</span><div className="button-row compact"><button className="mini" onClick={()=>move(i,-1)}>↑</button><button className="mini" onClick={()=>move(i,1)}>↓</button><button className="mini" onClick={()=>setPages(x=>x.map((v,n)=>n===i?{...v,rot:(v.rot+90)%360}:v))}>Rotate</button><button className="mini" onClick={()=>setPages(x=>{const y=[...x];y.splice(i+1,0,{...p,key:`dup-${Date.now()}-${Math.random()}`});return y})}>Duplicate</button><button className="mini danger" onClick={()=>setPages(x=>x.filter((_,n)=>n!==i))}>Delete</button></div></div>)}</div><button className="primary" disabled={!pages.length||busy} onClick={exportPdf}>{busy?'Working…':'Export organized PDF'}</button><Status>{msg}</Status></div>
}

export function PdfCompressor(){
  const[file,setFile]=useState(null),[quality,setQuality]=useState(.62),[scale,setScale]=useState(1.25),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[result,setResult]=useState(null)
  async function run(){setBusy(true);setMsg('Rasterizing pages for compression…');try{const source=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise,out=await PDFDocument.create();for(let i=0;i<source.numPages;i++){setMsg(`Compressing page ${i+1} of ${source.numPages}…`);const c=await renderPdfPage(source,i,Number(scale)),jpg=await blobCanvas(c,'image/jpeg',Number(quality)),img=await out.embedJpg(await jpg.arrayBuffer()),p=out.addPage([img.width,img.height]);p.drawImage(img,{x:0,y:0,width:img.width,height:img.height})}const blob=new Blob([await out.save()],{type:'application/pdf'});downloadBlob(blob,`${safeBaseName(file.name)}-compressed.pdf`);setResult(blob.size);setMsg('Compressed PDF downloaded. Note: this mode rasterizes pages, so original selectable text is flattened.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
  return <div className="stack"><FileDrop accept="application/pdf" onFiles={f=>setFile(f[0])}/>{file&&<div className="file-row"><span>{file.name}</span><small>{formatBytes(file.size)}</small></div>}<div className="form-grid"><label>Quality<select value={quality} onChange={e=>setQuality(e.target.value)}><option value=".82">High quality</option><option value=".62">Balanced</option><option value=".42">Maximum compression</option></select></label><label>Resolution<select value={scale} onChange={e=>setScale(e.target.value)}><option value="1">Smaller</option><option value="1.25">Balanced</option><option value="1.6">Sharper</option></select></label></div>{result&&file&&<div className="metric-grid"><div><strong>{formatBytes(file.size)}</strong><span>Original</span></div><div><strong>{formatBytes(result)}</strong><span>Output</span></div><div><strong>{Math.max(0,Math.round((1-result/file.size)*100))}%</strong><span>Saved</span></div></div>}<button className="primary" disabled={!file||busy} onClick={run}>{busy?'Compressing…':'Compress PDF'}</button><Status>{msg}</Status></div>
}

export function OcrToText({kind='document'}){
 const[file,setFile]=useState(null),[text,setText]=useState(''),[progress,setProgress]=useState(0),[busy,setBusy]=useState(false),[lang,setLang]=useState('eng'),[msg,setMsg]=useState('')
 async function run(){setBusy(true);setProgress(0);setMsg('Loading OCR engine…');try{let input=file;if(file.type==='application/pdf'){const doc=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise,parts=[];for(let i=0;i<doc.numPages;i++){const c=await renderPdfPage(doc,i,1.7);parts.push(await ocrImage(c,lang,setProgress))}setText(parts.join('\n\n--- Page ---\n\n'))}else setText(await ocrImage(file,lang,setProgress));setMsg('Text extraction complete.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 const extracted=useMemo(()=>{if(kind==='receipt'){const lines=text.split(/\n/).map(x=>x.trim()).filter(Boolean),money=lines.filter(x=>/(₱|php|total|amount|\d+[.,]\d{2})/i.test(x));return {summary:money.slice(-6).join('\n')}}if(kind==='card'){const email=text.match(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/)?.[0]||'',phone=text.match(/(?:\+?\d[\d\s()-]{7,}\d)/)?.[0]||'',url=text.match(/(?:https?:\/\/|www\.)\S+/i)?.[0]||'';return{summary:[email,phone,url].filter(Boolean).join('\n')}}return{summary:''}},[text,kind])
 return <div className="stack"><FileDrop accept="image/*,application/pdf" onFiles={f=>setFile(f[0])}/><label>OCR language<select value={lang} onChange={e=>setLang(e.target.value)}><option value="eng">English</option><option value="fil">Filipino / Tagalog</option></select></label>{busy&&<div className="progress"><span style={{width:`${progress}%`}}/></div>}<button className="primary" disabled={!file||busy} onClick={run}>{busy?`Reading ${progress}%`:'Extract text'}</button>{extracted.summary&&<div className="code-result pre">{extracted.summary}</div>}<label>Extracted text<textarea rows="14" value={text} onChange={e=>setText(e.target.value)} placeholder="Recognized text appears here…"/></label><div className="button-row"><button className="secondary" disabled={!text} onClick={()=>navigator.clipboard.writeText(text)}>Copy</button><button className="secondary" disabled={!text} onClick={()=>downloadBlob(new Blob([text],{type:'text/plain'}),`${safeBaseName(file?.name||'ocr')}.txt`)}>TXT</button></div><Status>{msg}</Status></div>
}
export const ReceiptScanner=()=> <OcrToText kind="receipt"/>
export const BusinessCardScanner=()=> <OcrToText kind="card"/>

export function SearchablePdf(){
 const[files,setFiles]=useState([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[msg,setMsg]=useState('')
 async function run(){setBusy(true);try{const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica);for(let i=0;i<files.length;i++){setMsg(`OCR page ${i+1} of ${files.length}…`);const f=files[i],url=readUrl(f),imgEl=await new Promise((r,j)=>{const im=new Image();im.onload=()=>r(im);im.onerror=j;im.src=url}),c=document.createElement('canvas');c.width=imgEl.naturalWidth;c.height=imgEl.naturalHeight;c.getContext('2d').drawImage(imgEl,0,0);URL.revokeObjectURL(url);const jpg=await blobCanvas(c,'image/jpeg',.9),img=await pdf.embedJpg(await jpg.arrayBuffer()),p=pdf.addPage([img.width,img.height]);p.drawImage(img,{x:0,y:0,width:img.width,height:img.height});const text=(await ocrImage(c,'eng',setProgress)).replace(/[^\x20-\x7E\n]/g,' ').slice(0,24000);if(text.trim())p.drawText(text,{x:2,y:2,size:1,font,color:rgb(1,1,1),opacity:.01,maxWidth:img.width-4,lineHeight:1})}downloadBlob(new Blob([await pdf.save()],{type:'application/pdf'}),'deskora-searchable-scan.pdf');setMsg('Searchable PDF created. OCR text is embedded as a near-invisible searchable layer.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <div className="stack"><FileDrop accept="image/*" multiple onFiles={setFiles}/>{files.length>0&&<div className="file-list">{files.map((f,i)=><div className="file-row" key={i}><span>{f.name}</span><small>{formatBytes(f.size)}</small></div>)}</div>}{busy&&<div className="progress"><span style={{width:`${progress}%`}}/></div>}<button className="primary" disabled={!files.length||busy} onClick={run}>{busy?'OCR processing…':'Create searchable PDF'}</button><Status>{msg}</Status></div>
}

export function PdfToWordText(){
 const[file,setFile]=useState(null),[text,setText]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 async function run(){setBusy(true);try{const doc=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise,parts=[];for(let i=1;i<=doc.numPages;i++){const p=await doc.getPage(i),tc=await p.getTextContent();parts.push(tc.items.map(x=>x.str).join(' '))}const t=parts.join('\n\n');setText(t);setMsg('Text extracted. Layout-heavy PDFs may need manual cleanup.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 function doc(){const html=`<html><body>${text.split('\n').map(x=>`<p>${x.replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}</p>`).join('')}</body></html>`;downloadBlob(new Blob([html],{type:'application/msword'}),`${safeBaseName(file.name)}.doc`)}
 return <div className="stack"><FileDrop accept="application/pdf" onFiles={f=>setFile(f[0])}/><button className="primary" disabled={!file||busy} onClick={run}>{busy?'Extracting…':'Extract PDF text'}</button><label>Editable text<textarea rows="14" value={text} onChange={e=>setText(e.target.value)}/></label><div className="button-row"><button className="secondary" disabled={!text} onClick={doc}>Download Word-compatible .doc</button><button className="secondary" disabled={!text} onClick={()=>downloadBlob(new Blob([text],{type:'text/plain'}),'deskora-pdf-text.txt')}>TXT</button></div><Status>{msg}</Status></div>
}

export function PdfMetadataCleaner(){
 const[file,setFile]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 async function run(){setBusy(true);try{const pdf=await PDFDocument.load(await file.arrayBuffer(),{updateMetadata:false});pdf.setTitle('');pdf.setAuthor('');pdf.setSubject('');pdf.setKeywords([]);pdf.setCreator('');pdf.setProducer('');downloadBlob(new Blob([await pdf.save()],{type:'application/pdf'}),`${safeBaseName(file.name)}-metadata-clean.pdf`);setMsg('Common PDF metadata fields were cleared.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <div className="stack"><FileDrop accept="application/pdf" onFiles={f=>setFile(f[0])}/><button className="primary" disabled={!file||busy} onClick={run}>{busy?'Cleaning…':'Remove PDF metadata'}</button><Status>{msg}</Status></div>
}

export function PdfRedactor(){
 const[file,setFile]=useState(null),[doc,setDoc]=useState(null),[page,setPage]=useState(0),[boxes,setBoxes]=useState({}),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),canvasRef=useRef(null),startRef=useRef(null)
 async function open(f){if(!f)return;setBusy(true);try{const d=await pdfjsLib.getDocument({data:await f.arrayBuffer()}).promise;setFile(f);setDoc(d);setPage(0);setBoxes({});setTimeout(()=>draw(d,0,{}),0);setMsg('Drag across sensitive content to mark permanent redaction areas.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function draw(d=doc,p=page,b=boxes){if(!d||!canvasRef.current)return;const c=await renderPdfPage(d,p,1.35),out=canvasRef.current;out.width=c.width;out.height=c.height;const x=out.getContext('2d');x.drawImage(c,0,0);x.fillStyle='#000';(b[p]||[]).forEach(r=>x.fillRect(r.x*out.width,r.y*out.height,r.w*out.width,r.h*out.height))}
 const pos=e=>{const r=canvasRef.current.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}
 function down(e){startRef.current=pos(e)}function up(e){if(!startRef.current)return;const a=startRef.current,z=pos(e),r={x:Math.min(a.x,z.x),y:Math.min(a.y,z.y),w:Math.abs(a.x-z.x),h:Math.abs(a.y-z.y)};startRef.current=null;if(r.w<.005||r.h<.005)return;setBoxes(v=>{const n={...v,[page]:[...(v[page]||[]),r]};draw(doc,page,n);return n})}
 async function exportPdf(){setBusy(true);try{const src=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise,out=await PDFDocument.create();for(let i=0;i<src.numPages;i++){const c=await renderPdfPage(src,i,1.55),ctx=c.getContext('2d');ctx.fillStyle='#000';(boxes[i]||[]).forEach(r=>ctx.fillRect(r.x*c.width,r.y*c.height,r.w*c.width,r.h*c.height));const jpg=await blobCanvas(c,'image/jpeg',.94),img=await out.embedJpg(await jpg.arrayBuffer()),p=out.addPage([img.width,img.height]);p.drawImage(img,{x:0,y:0,width:img.width,height:img.height})}downloadBlob(new Blob([await out.save()],{type:'application/pdf'}),`${safeBaseName(file.name)}-redacted.pdf`);setMsg('Redacted PDF exported as flattened pages, removing selectable underlying content.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <div className="stack"><FileDrop accept="application/pdf" onFiles={f=>open(f[0])}/>{doc&&<><div className="button-row"><button className="secondary" disabled={page===0} onClick={()=>{setPage(x=>x-1);setTimeout(()=>draw(doc,page-1,boxes),0)}}>Previous</button><span className="muted">Page {page+1} / {doc.numPages}</span><button className="secondary" disabled={page===doc.numPages-1} onClick={()=>{setPage(x=>x+1);setTimeout(()=>draw(doc,page+1,boxes),0)}}>Next</button><button className="secondary" onClick={()=>setBoxes(v=>{const n={...v,[page]:[]};draw(doc,page,n);return n})}>Clear page</button></div><div className="pdf-redact-stage"><canvas ref={canvasRef} onPointerDown={down} onPointerUp={up}/></div><button className="primary" disabled={busy} onClick={exportPdf}>Export permanently redacted PDF</button></>}<Status>{msg}</Status></div>
}

export function SignatureMaker(){
 const ref=useRef(null),drawing=useRef(false),[msg,setMsg]=useState('Draw your signature with a mouse, pen, or finger.')
 function p(e){const c=ref.current,r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}
 function down(e){drawing.current=true;const q=p(e),x=ref.current.getContext('2d');x.beginPath();x.moveTo(q.x,q.y);e.currentTarget.setPointerCapture?.(e.pointerId)}function move(e){if(!drawing.current)return;const q=p(e),x=ref.current.getContext('2d');x.lineWidth=3;x.lineCap='round';x.strokeStyle='#101827';x.lineTo(q.x,q.y);x.stroke()}function up(){drawing.current=false}
 return <div className="stack"><div className="signature-pad"><canvas ref={ref} width="1000" height="340" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerLeave={up}/></div><div className="button-row"><button className="secondary" onClick={()=>ref.current.getContext('2d').clearRect(0,0,1000,340)}>Clear</button><button className="primary" onClick={()=>ref.current.toBlob(b=>downloadBlob(b,'deskora-signature.png'))}>Download transparent PNG</button></div><Status>{msg}</Status></div>
}

export function IdPictureMaker(){
 const[file,setFile]=useState(null),[size,setSize]=useState('2x2'),[msg,setMsg]=useState(''),canvasRef=useRef(null)
 async function run(){const url=readUrl(file),im=await new Promise((r,j)=>{const x=new Image();x.onload=()=>r(x);x.onerror=j;x.src=url});URL.revokeObjectURL(url);const c=canvasRef.current;c.width=2480;c.height=3508;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);const inch=size==='1x1'?1:size==='passport'?1.38:2,w=Math.round(inch*300),h=size==='passport'?Math.round(1.77*300):w,g=34,cols=Math.max(1,Math.floor((c.width-160+g)/(w+g))),rows=Math.max(1,Math.floor((c.height-160+g)/(h+g))),s=Math.max(w/im.width,h/im.height),dw=im.width*s,dh=im.height*s;for(let r=0;r<rows;r++)for(let k=0;k<cols;k++){const px=80+k*(w+g),py=80+r*(h+g);x.save();x.beginPath();x.rect(px,py,w,h);x.clip();x.drawImage(im,px+(w-dw)/2,py+(h-dh)/2,dw,dh);x.restore();x.strokeStyle='#d7dce2';x.strokeRect(px,py,w,h)}setMsg(`A4 300-DPI sheet prepared with ${cols*rows} copies.`)}
 return <div className="stack"><FileDrop accept="image/*" onFiles={f=>setFile(f[0])}/><label>Photo size<select value={size} onChange={e=>setSize(e.target.value)}><option value="1x1">1 × 1 inch</option><option value="2x2">2 × 2 inch</option><option value="passport">Passport 35 × 45 mm</option></select></label><button className="primary" disabled={!file} onClick={run}>Create A4 print sheet</button><div className="canvas-wrap print-preview"><canvas ref={canvasRef}/></div><button className="secondary" disabled={!canvasRef.current?.width} onClick={()=>canvasRef.current.toBlob(b=>downloadBlob(b,'deskora-id-photo-sheet.png'))}>Download 300-DPI PNG</button><Status>{msg}</Status></div>
}

export function DateStampGenerator(){
 const[label,setLabel]=useState('RECEIVED'),[dept,setDept]=useState('OFFICE'),[date,setDate]=useState(new Date().toISOString().slice(0,10)),ref=useRef(null),[msg,setMsg]=useState('')
 function draw(){const c=ref.current;c.width=1200;c.height=650;const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.strokeStyle='#153c75';x.lineWidth=18;x.strokeRect(30,30,1140,590);x.fillStyle='#153c75';x.textAlign='center';x.font='bold 120px sans-serif';x.fillText(label.toUpperCase(),600,190);x.font='bold 78px sans-serif';x.fillText(new Date(date+'T00:00:00').toLocaleDateString(undefined,{year:'numeric',month:'short',day:'2-digit'}).toUpperCase(),600,330);x.font='bold 58px sans-serif';x.fillText(dept.toUpperCase(),600,470);setMsg('Transparent stamp generated.')}
 return <div className="stack"><div className="form-grid three"><label>Stamp<input value={label} onChange={e=>setLabel(e.target.value)}/></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Department<input value={dept} onChange={e=>setDept(e.target.value)}/></label></div><button className="primary" onClick={draw}>Generate stamp</button><div className="canvas-wrap"><canvas ref={ref}/></div><button className="secondary" onClick={()=>ref.current.toBlob(b=>downloadBlob(b,'deskora-date-stamp.png'))}>Download PNG</button><Status>{msg}</Status></div>
}

export function PdfPasswordTool(){return <div className="stack"><div className="status warn"><strong>Standard PDF encryption is not enabled in this browser-only build yet.</strong><br/>Deskora will not fake password protection by wrapping the file in a non-standard format. Use the metadata cleaner/redaction tools now; native encrypted-PDF output requires a dedicated audited PDF encryption engine before this control is enabled.</div></div>}
