import { useEffect, useMemo, useRef, useState } from 'react'
import { PDFDocument } from 'pdf-lib'
import * as XLSX from 'xlsx'
import QRCode from 'qrcode'
import FileDrop from '../components/FileDrop'
import Status from '../components/Status'
import { downloadBlob, formatBytes, safeBaseName } from '../lib'

const imageEl = file => new Promise((resolve,reject)=>{const url=URL.createObjectURL(file);const img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=e=>{URL.revokeObjectURL(url);reject(e)};img.src=url})
const canvasBlob=(canvas,type='image/png',quality=.92)=>new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Could not create output file.')),type,quality))
const saveText=(text,name,type='text/plain')=>downloadBlob(new Blob([text],{type}),name)
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n))

export function ImageCropRotate(){
  const[file,setFile]=useState(null),[meta,setMeta]=useState(null),[crop,setCrop]=useState({x:0,y:0,w:0,h:0}),[rotation,setRotation]=useState(0),[format,setFormat]=useState('image/png'),[msg,setMsg]=useState('')
  async function load(f){if(!f)return;try{const img=await imageEl(f);setFile(f);setMeta({w:img.naturalWidth,h:img.naturalHeight});setCrop({x:0,y:0,w:img.naturalWidth,h:img.naturalHeight});setMsg(`${img.naturalWidth} × ${img.naturalHeight}px loaded.`)}catch(e){setMsg(e.message)}}
  async function run(){try{const img=await imageEl(file),x=clamp(Number(crop.x)||0,0,img.naturalWidth-1),y=clamp(Number(crop.y)||0,0,img.naturalHeight-1),w=clamp(Number(crop.w)||img.naturalWidth,1,img.naturalWidth-x),h=clamp(Number(crop.h)||img.naturalHeight,1,img.naturalHeight-y),r=Number(rotation);const c=document.createElement('canvas');c.width=r%180===0?w:h;c.height=r%180===0?h:w;const ctx=c.getContext('2d');ctx.translate(c.width/2,c.height/2);ctx.rotate(r*Math.PI/180);ctx.drawImage(img,x,y,w,h,-w/2,-h/2,w,h);const blob=await canvasBlob(c,format,format==='image/jpeg'?.92:undefined);downloadBlob(blob,`${safeBaseName(file.name)}-edited.${format==='image/png'?'png':'jpg'}`);setMsg('Image exported.')}catch(e){setMsg(e.message)}}
  return <div className="stack"><FileDrop accept="image/*" onFiles={f=>load(f[0])}/>{meta&&<><div className="form-grid"><label>X<input type="number" value={crop.x} onChange={e=>setCrop(v=>({...v,x:e.target.value}))}/></label><label>Y<input type="number" value={crop.y} onChange={e=>setCrop(v=>({...v,y:e.target.value}))}/></label><label>Width<input type="number" value={crop.w} onChange={e=>setCrop(v=>({...v,w:e.target.value}))}/></label><label>Height<input type="number" value={crop.h} onChange={e=>setCrop(v=>({...v,h:e.target.value}))}/></label></div><div className="form-grid"><label>Rotate<select value={rotation} onChange={e=>setRotation(e.target.value)}><option value="0">0°</option><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></label><label>Output<select value={format} onChange={e=>setFormat(e.target.value)}><option value="image/png">PNG</option><option value="image/jpeg">JPG</option></select></label></div><button className="primary" onClick={run}>Crop / rotate & download</button></>}<Status>{msg}</Status></div>
}

export function DocumentEnhancer(){
  const[file,setFile]=useState(null),[mode,setMode]=useState('grayscale'),[contrast,setContrast]=useState(25),[brightness,setBrightness]=useState(5),[msg,setMsg]=useState(''),canvas=useRef(null)
  async function render(f=file){if(!f)return;try{const img=await imageEl(f),max=1600,scale=Math.min(1,max/img.naturalWidth),c=canvas.current;c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(img.naturalHeight*scale);const ctx=c.getContext('2d');ctx.drawImage(img,0,0,c.width,c.height);const data=ctx.getImageData(0,0,c.width,c.height),d=data.data,ct=(259*(Number(contrast)+255))/(255*(259-Number(contrast))),br=Number(brightness)*2.55;for(let i=0;i<d.length;i+=4){let r=clamp(ct*(d[i]-128)+128+br,0,255),g=clamp(ct*(d[i+1]-128)+128+br,0,255),b=clamp(ct*(d[i+2]-128)+128+br,0,255);const gray=.299*r+.587*g+.114*b;if(mode==='grayscale'){r=g=b=gray}else if(mode==='bw'){r=g=b=gray>155?255:0}else if(mode==='enhanced'){const lift=clamp((gray-35)*1.18,0,255);r=clamp(r+(lift-gray)*.35,0,255);g=clamp(g+(lift-gray)*.35,0,255);b=clamp(b+(lift-gray)*.35,0,255)}d[i]=r;d[i+1]=g;d[i+2]=b}ctx.putImageData(data,0,0);setMsg('Preview updated.')}catch(e){setMsg(e.message)}}
  useEffect(()=>{if(file)render()},[mode,contrast,brightness])
  async function save(){const blob=await canvasBlob(canvas.current,'image/jpeg',.94);downloadBlob(blob,`${safeBaseName(file.name)}-scan.jpg`)}
  return <div className="stack"><FileDrop accept="image/*" onFiles={f=>{setFile(f[0]);setTimeout(()=>render(f[0]),0)}}/><div className="form-grid"><label>Scan style<select value={mode} onChange={e=>setMode(e.target.value)}><option value="enhanced">Enhanced color</option><option value="grayscale">Grayscale</option><option value="bw">Black & white</option></select></label><label>Contrast {contrast}<input type="range" min="-30" max="80" value={contrast} onChange={e=>setContrast(e.target.value)}/></label><label>Brightness {brightness}<input type="range" min="-40" max="40" value={brightness} onChange={e=>setBrightness(e.target.value)}/></label></div><div className="canvas-wrap"><canvas ref={canvas}/></div><button className="primary" disabled={!file} onClick={save}>Download enhanced scan</button><Status>{msg}</Status></div>
}

export function PhotoSheet(){
  const[file,setFile]=useState(null),[copies,setCopies]=useState(12),[wmm,setWmm]=useState(35),[hmm,setHmm]=useState(45),[msg,setMsg]=useState('')
  async function run(){try{const img=await imageEl(file),dpi=300,mm= dpi/25.4,pageW=Math.round(210*mm),pageH=Math.round(297*mm),pw=Math.round(Number(wmm)*mm),ph=Math.round(Number(hmm)*mm),gap=Math.round(4*mm),margin=Math.round(10*mm),c=document.createElement('canvas');c.width=pageW;c.height=pageH;const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,pageW,pageH);const cols=Math.max(1,Math.floor((pageW-margin*2+gap)/(pw+gap)));for(let i=0;i<Number(copies);i++){const col=i%cols,row=Math.floor(i/cols),x=margin+col*(pw+gap),y=margin+row*(ph+gap);if(y+ph>pageH-margin)break;const ir=img.naturalWidth/img.naturalHeight,tr=pw/ph;let sx=0,sy=0,sw=img.naturalWidth,sh=img.naturalHeight;if(ir>tr){sw=img.naturalHeight*tr;sx=(img.naturalWidth-sw)/2}else{sh=img.naturalWidth/tr;sy=(img.naturalHeight-sh)/2}ctx.drawImage(img,sx,sy,sw,sh,x,y,pw,ph);ctx.strokeStyle='#d0d0d0';ctx.strokeRect(x,y,pw,ph)}const blob=await canvasBlob(c,'image/jpeg',.96);downloadBlob(blob,'deskora-photo-sheet-a4.jpg');setMsg('A4 300-DPI photo sheet downloaded.')}catch(e){setMsg(e.message)}}
  return <div className="stack"><FileDrop accept="image/*" onFiles={f=>setFile(f[0])}/><div className="form-grid three"><label>Copies<input type="number" min="1" max="60" value={copies} onChange={e=>setCopies(e.target.value)}/></label><label>Width (mm)<input type="number" value={wmm} onChange={e=>setWmm(e.target.value)}/></label><label>Height (mm)<input type="number" value={hmm} onChange={e=>setHmm(e.target.value)}/></label></div><button className="primary" disabled={!file} onClick={run}>Create A4 photo sheet</button><Status>{msg}</Status></div>
}

export function PosterSplitter(){
  const[file,setFile]=useState(null),[cols,setCols]=useState(2),[rows,setRows]=useState(2),[msg,setMsg]=useState('')
  async function run(){try{const img=await imageEl(file),pdf=await PDFDocument.create(),pageW=595.28,pageH=841.89;for(let row=0;row<Number(rows);row++)for(let col=0;col<Number(cols);col++){const sx=img.naturalWidth*col/cols,sy=img.naturalHeight*row/rows,sw=img.naturalWidth/cols,sh=img.naturalHeight/rows,c=document.createElement('canvas');c.width=Math.min(1800,Math.round(sw));c.height=Math.min(2500,Math.round(sh));c.getContext('2d').drawImage(img,sx,sy,sw,sh,0,0,c.width,c.height);const jpg=await canvasBlob(c,'image/jpeg',.94),embedded=await pdf.embedJpg(await jpg.arrayBuffer()),p=pdf.addPage([pageW,pageH]),scale=Math.min((pageW-30)/embedded.width,(pageH-30)/embedded.height),w=embedded.width*scale,h=embedded.height*scale;p.drawImage(embedded,{x:(pageW-w)/2,y:(pageH-h)/2,width:w,height:h})}downloadBlob(new Blob([await pdf.save()],{type:'application/pdf'}),`${safeBaseName(file.name)}-poster-${cols}x${rows}.pdf`);setMsg(`${Number(cols)*Number(rows)} printable A4 pages created.`)}catch(e){setMsg(e.message)}}
  return <div className="stack"><FileDrop accept="image/*" onFiles={f=>setFile(f[0])}/><div className="form-grid"><label>Columns<select value={cols} onChange={e=>setCols(e.target.value)}><option>2</option><option>3</option><option>4</option></select></label><label>Rows<select value={rows} onChange={e=>setRows(e.target.value)}><option>2</option><option>3</option><option>4</option></select></label></div><button className="primary" disabled={!file} onClick={run}>Create tiled A4 PDF</button><Status>{msg}</Status></div>
}

export function TextToolkit(){
  const[text,setText]=useState('')
  const stats=useMemo(()=>({characters:text.length,words:(text.trim().match(/\S+/g)||[]).length,lines:text?text.split(/\r?\n/).length:0,unique:new Set((text.trim().match(/\S+/g)||[]).map(x=>x.toLowerCase())).size}),[text])
  const apply=fn=>setText(fn(text))
  return <div className="stack"><label>Text<textarea rows="14" value={text} onChange={e=>setText(e.target.value)} placeholder="Paste text here…"/></label><div className="metric-grid"><div><strong>{stats.characters}</strong><span>Characters</span></div><div><strong>{stats.words}</strong><span>Words</span></div><div><strong>{stats.lines}</strong><span>Lines</span></div><div><strong>{stats.unique}</strong><span>Unique words</span></div></div><div className="button-row"><button className="secondary" onClick={()=>apply(t=>t.toUpperCase())}>UPPERCASE</button><button className="secondary" onClick={()=>apply(t=>t.toLowerCase())}>lowercase</button><button className="secondary" onClick={()=>apply(t=>t.toLowerCase().replace(/(^|\s)\S/g,m=>m.toUpperCase()))}>Title Case</button><button className="secondary" onClick={()=>apply(t=>t.replace(/[ \t]+/g,' ').replace(/^ +| +$/gm,''))}>Trim spaces</button><button className="secondary" onClick={()=>apply(t=>[...new Set(t.split(/\r?\n/))].join('\n'))}>Remove duplicate lines</button><button className="secondary" onClick={()=>apply(t=>t.split(/\r?\n/).filter(x=>x.trim()).sort((a,b)=>a.localeCompare(b)).join('\n'))}>Sort lines</button><button className="secondary" onClick={()=>apply(t=>t.replace(/\n{3,}/g,'\n\n'))}>Clean blank lines</button></div><div className="button-row"><button className="primary" disabled={!text} onClick={()=>navigator.clipboard.writeText(text)}>Copy text</button><button className="secondary" disabled={!text} onClick={()=>saveText(text,'deskora-clean-text.txt')}>Download TXT</button></div></div>
}

export function JsonCsv(){
 const[input,setInput]=useState(''),[output,setOutput]=useState(''),[msg,setMsg]=useState('')
 function jsonToCsv(){try{const data=JSON.parse(input),rows=Array.isArray(data)?data:[data],ws=XLSX.utils.json_to_sheet(rows);setOutput(XLSX.utils.sheet_to_csv(ws));setMsg('JSON converted to CSV.')}catch(e){setMsg(`Invalid JSON: ${e.message}`)}}
 function csvToJson(){try{const wb=XLSX.read(input,{type:'string'}),ws=wb.Sheets[wb.SheetNames[0]];setOutput(JSON.stringify(XLSX.utils.sheet_to_json(ws,{defval:''}),null,2));setMsg('CSV converted to JSON.')}catch(e){setMsg(e.message)}}
 return <div className="stack"><label>Input<textarea rows="12" value={input} onChange={e=>setInput(e.target.value)} placeholder="Paste JSON or CSV…"/></label><div className="button-row"><button className="primary" onClick={jsonToCsv}>JSON → CSV</button><button className="secondary" onClick={csvToJson}>CSV → JSON</button></div><label>Output<textarea rows="12" value={output} onChange={e=>setOutput(e.target.value)}/></label><button className="secondary" disabled={!output} onClick={()=>navigator.clipboard.writeText(output)}>Copy output</button><Status>{msg}</Status></div>
}

const formatXml=text=>{const compact=text.replace(/>\s*</g,'><').trim(),tokens=compact.replace(/</g,'\n<').trim().split('\n');let pad=0;return tokens.map(token=>{if(/^<\//.test(token))pad=Math.max(0,pad-1);const line='  '.repeat(pad)+token;if(/^<[^!?/][^>]*[^/]?>/.test(token)&&!/<\/[^>]+>$/.test(token))pad++;return line}).join('\n')}
export function XmlTools(){const[input,setInput]=useState(''),[output,setOutput]=useState(''),[msg,setMsg]=useState('');function run(compact=false){try{const doc=new DOMParser().parseFromString(input,'application/xml');const err=doc.querySelector('parsererror');if(err)throw new Error(err.textContent.split('\n')[0]);const raw=new XMLSerializer().serializeToString(doc);setOutput(compact?raw:formatXml(raw));setMsg('Valid XML.')}catch(e){setMsg(`XML error: ${e.message}`)}}return <div className="stack"><label>XML<textarea rows="12" value={input} onChange={e=>setInput(e.target.value)}/></label><div className="button-row"><button className="primary" onClick={()=>run(false)}>Format & validate</button><button className="secondary" onClick={()=>run(true)}>Compact</button></div><label>Output<textarea rows="12" value={output} onChange={e=>setOutput(e.target.value)}/></label><Status>{msg}</Status></div>}

export function RegexTester(){const[pattern,setPattern]=useState(''),[flags,setFlags]=useState('gi'),[text,setText]=useState(''),[msg,setMsg]=useState('');const result=useMemo(()=>{if(!pattern)return[];try{const f=flags.includes('g')?flags:flags+'g',r=new RegExp(pattern,f);return [...text.matchAll(r)].slice(0,250)}catch{return[]}},[pattern,flags,text]);useEffect(()=>{if(!pattern){setMsg('');return}try{new RegExp(pattern,flags);setMsg(`${result.length} match${result.length===1?'':'es'}.`)}catch(e){setMsg(e.message)}},[pattern,flags,text,result.length]);return <div className="stack"><div className="form-grid"><label>Pattern<input value={pattern} onChange={e=>setPattern(e.target.value)} placeholder="\b[A-Z]+\b"/></label><label>Flags<input value={flags} onChange={e=>setFlags(e.target.value)} placeholder="gi"/></label></div><label>Test text<textarea rows="12" value={text} onChange={e=>setText(e.target.value)}/></label><div className="code-result pre">{result.map((m,i)=>`#${i+1} [${m.index}] ${m[0]}`).join('\n')||'No matches.'}</div><Status>{msg}</Status></div>}

const decodeBase64Url=s=>decodeURIComponent(atob(s.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(s.length/4)*4,'=')).split('').map(c=>'%'+c.charCodeAt(0).toString(16).padStart(2,'0')).join(''))
export function JwtDecoder(){const[token,setToken]=useState(''),[header,setHeader]=useState(''),[payload,setPayload]=useState(''),[msg,setMsg]=useState('');function run(){try{const[p1,p2]=token.trim().split('.');if(!p1||!p2)throw new Error('JWT must contain at least header and payload sections.');setHeader(JSON.stringify(JSON.parse(decodeBase64Url(p1)),null,2));setPayload(JSON.stringify(JSON.parse(decodeBase64Url(p2)),null,2));setMsg('Decoded locally. Signature was not verified.')}catch(e){setMsg(e.message)}}return <div className="stack"><label>JWT<textarea rows="6" value={token} onChange={e=>setToken(e.target.value)} placeholder="eyJ…"/></label><button className="primary" onClick={run}>Decode JWT</button><div className="form-grid"><label>Header<textarea rows="10" value={header} readOnly/></label><label>Payload<textarea rows="10" value={payload} readOnly/></label></div><Status>{msg}</Status></div>}

export function UrlTools(){const[value,setValue]=useState(''),[output,setOutput]=useState(''),[msg,setMsg]=useState('');function parse(){try{const u=new URL(value),obj={protocol:u.protocol,host:u.host,hostname:u.hostname,port:u.port||'(default)',pathname:u.pathname,hash:u.hash,query:Object.fromEntries(u.searchParams.entries())};setOutput(JSON.stringify(obj,null,2));setMsg('URL parsed.')}catch(e){setMsg(e.message)}}return <div className="stack"><label>Text / URL<textarea rows="5" value={value} onChange={e=>setValue(e.target.value)}/></label><div className="button-row"><button className="secondary" onClick={()=>setOutput(encodeURIComponent(value))}>Encode component</button><button className="secondary" onClick={()=>{try{setOutput(decodeURIComponent(value));setMsg('Decoded.')}catch(e){setMsg(e.message)}}}>Decode component</button><button className="primary" onClick={parse}>Parse URL</button></div><label>Output<textarea rows="10" value={output} onChange={e=>setOutput(e.target.value)}/></label><Status>{msg}</Status></div>}

export function TimestampConverter(){const[unix,setUnix]=useState(()=>Math.floor(Date.now()/1000).toString()),[date,setDate]=useState(()=>new Date().toISOString().slice(0,16)),[result,setResult]=useState('');function fromUnix(){const n=Number(unix),d=new Date(n>1e12?n:n*1000);setResult(`Local: ${d.toLocaleString()}\nUTC: ${d.toUTCString()}\nISO: ${d.toISOString()}`)}function fromDate(){const ms=new Date(date).getTime();setResult(`Unix seconds: ${Math.floor(ms/1000)}\nUnix milliseconds: ${ms}`)}return <div className="stack"><div className="form-grid"><label>Unix timestamp<input value={unix} onChange={e=>setUnix(e.target.value)}/><button className="secondary" onClick={fromUnix}>Convert timestamp</button></label><label>Date & time<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/><button className="secondary" onClick={fromDate}>Convert date</button></label></div><div className="code-result pre">{result||'Conversion result appears here.'}</div></div>}

export function UuidGenerator(){const[count,setCount]=useState(5),[value,setValue]=useState('');function run(){setValue(Array.from({length:clamp(Number(count)||1,1,100)},()=>crypto.randomUUID()).join('\n'))}useEffect(()=>run(),[]);return <div className="stack"><label>How many UUIDs?<input type="number" min="1" max="100" value={count} onChange={e=>setCount(e.target.value)}/></label><button className="primary" onClick={run}>Generate UUID v4</button><textarea rows="12" value={value} readOnly/><button className="secondary" onClick={()=>navigator.clipboard.writeText(value)}>Copy all</button></div>}

export function ImageBase64(){const[file,setFile]=useState(null),[text,setText]=useState(''),[msg,setMsg]=useState('');async function encode(f){if(!f)return;const reader=new FileReader();reader.onload=()=>{setFile(f);setText(String(reader.result));setMsg(`${formatBytes(f.size)} encoded.`)};reader.onerror=()=>setMsg('Could not read image.');reader.readAsDataURL(f)}function decode(){try{const src=text.trim().startsWith('data:')?text.trim():`data:image/png;base64,${text.trim()}`,a=document.createElement('a');a.href=src;a.download='deskora-decoded-image.png';a.click();setMsg('Decoded image download started.')}catch(e){setMsg(e.message)}}return <div className="stack"><FileDrop accept="image/*" onFiles={f=>encode(f[0])}/><label>Data URL / Base64<textarea rows="12" value={text} onChange={e=>setText(e.target.value)}/></label><div className="button-row"><button className="primary" disabled={!text} onClick={()=>navigator.clipboard.writeText(text)}>Copy</button><button className="secondary" disabled={!text} onClick={decode}>Decode to image</button></div><Status>{msg}</Status></div>}

export function MacFormatter(){const[value,setValue]=useState(''),[style,setStyle]=useState('colon'),[msg,setMsg]=useState('');const clean=value.replace(/[^0-9a-f]/gi,'').toUpperCase();const valid=clean.length===12;const output=valid?(style==='cisco'?clean.match(/.{1,4}/g).join('.'):clean.match(/.{1,2}/g).join(style==='dash'?'-':':')):'';useEffect(()=>setMsg(value&&!valid?'Enter exactly 12 hexadecimal characters.':valid?'Valid MAC address.':''),[value,valid]);return <div className="stack"><label>MAC address<input value={value} onChange={e=>setValue(e.target.value)} placeholder="001122AABBCC"/></label><label>Format<select value={style} onChange={e=>setStyle(e.target.value)}><option value="colon">00:11:22:AA:BB:CC</option><option value="dash">00-11-22-AA-BB-CC</option><option value="cisco">0011.22AA.BBCC</option></select></label><div className="hero-result"><small>Formatted MAC</small><strong>{output||'—'}</strong></div><button className="secondary" disabled={!output} onClick={()=>navigator.clipboard.writeText(output)}>Copy</button><Status>{msg}</Status></div>}

export function FileSizeConverter(){const[value,setValue]=useState(1),[from,setFrom]=useState('MB'),[binary,setBinary]=useState(true);const base=binary?1024:1000,units=['B','KB','MB','GB','TB'],bytes=Number(value)*base**units.indexOf(from);return <div className="stack"><div className="form-grid"><label>Value<input type="number" value={value} onChange={e=>setValue(e.target.value)}/></label><label>From<select value={from} onChange={e=>setFrom(e.target.value)}>{units.map(u=><option key={u}>{u}</option>)}</select></label></div><label className="check-row"><input type="checkbox" checked={binary} onChange={e=>setBinary(e.target.checked)}/> Use binary units (1 KB = 1024 bytes)</label><div className="result-table">{units.map((u,i)=><div key={u}><span>{u}</span><strong>{Number.isFinite(bytes)?(bytes/base**i).toLocaleString(undefined,{maximumFractionDigits:6}):'—'}</strong></div>)}</div></div>}

const unitDefs={length:{m:1,km:1000,cm:.01,mm:.001,in:.0254,ft:.3048,yd:.9144,mi:1609.344},weight:{kg:1,g:.001,mg:.000001,lb:.45359237,oz:.028349523125},area:{'m²':1,'km²':1e6,'cm²':.0001,'ft²':.09290304,'in²':.00064516,ha:10000,acre:4046.8564224},storage:{B:1,KB:1024,MB:1024**2,GB:1024**3,TB:1024**4}}
export function UnitConverter(){const[cat,setCat]=useState('length'),[value,setValue]=useState(1),[from,setFrom]=useState('m'),[to,setTo]=useState('ft');useEffect(()=>{if(cat==='temperature'){setFrom('C');setTo('F')}else{const k=Object.keys(unitDefs[cat]);setFrom(k[0]);setTo(k[1])}},[cat]);let result;if(cat==='temperature'){const c=from==='C'?Number(value):from==='F'?(Number(value)-32)*5/9:Number(value)-273.15;result=to==='C'?c:to==='F'?c*9/5+32:c+273.15}else result=Number(value)*(unitDefs[cat]?.[from]||1)/(unitDefs[cat]?.[to]||1);const options=cat==='temperature'?['C','F','K']:Object.keys(unitDefs[cat]||{});return <div className="stack"><label>Category<select value={cat} onChange={e=>setCat(e.target.value)}><option value="length">Length</option><option value="weight">Weight</option><option value="temperature">Temperature</option><option value="area">Area</option><option value="storage">Storage</option></select></label><div className="form-grid three"><label>Value<input type="number" value={value} onChange={e=>setValue(e.target.value)}/></label><label>From<select value={from} onChange={e=>setFrom(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label><label>To<select value={to} onChange={e=>setTo(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="hero-result"><small>Converted value</small><strong>{Number.isFinite(result)?result.toLocaleString(undefined,{maximumFractionDigits:8}):'—'}</strong><span>{to}</span></div></div>}

export function DateCalculator(){const[start,setStart]=useState(()=>new Date().toISOString().slice(0,10)),[end,setEnd]=useState(()=>new Date(Date.now()+7*864e5).toISOString().slice(0,10)),[days,setDays]=useState(30);const diff=Math.round((new Date(end)-new Date(start))/864e5),added=new Date(new Date(start).getTime()+Number(days)*864e5);return <div className="stack"><div className="form-grid"><label>Start date<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End date<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><div className="metric-grid"><div><strong>{Number.isFinite(diff)?Math.abs(diff):0}</strong><span>Calendar days apart</span></div><div><strong>{Number.isFinite(diff)?Math.floor(Math.abs(diff)/7):0}</strong><span>Full weeks</span></div></div><label>Add / subtract days<input type="number" value={days} onChange={e=>setDays(e.target.value)}/></label><div className="hero-result"><small>{days>=0?'Result after adding':'Result after subtracting'} {Math.abs(days)} days</small><strong>{Number.isFinite(added.getTime())?added.toLocaleDateString():'—'}</strong></div></div>}

export function PercentageCalculator(){const[mode,setMode]=useState('percent'),[a,setA]=useState(100),[b,setB]=useState(20);let label='Result',result=0;if(mode==='percent'){label=`${b}% of ${a}`;result=a*b/100}else if(mode==='change'){label='Percent change';result=a===0?0:(b-a)/Math.abs(a)*100}else if(mode==='discount'){label='Price after discount';result=a*(1-b/100)}else if(mode==='markup'){label='Price after markup';result=a*(1+b/100)}else if(mode==='margin'){label='Selling price for target margin';result=b>=100?0:a/(1-b/100)}return <div className="stack"><label>Calculation<select value={mode} onChange={e=>setMode(e.target.value)}><option value="percent">Percent of number</option><option value="change">Percent change (A → B)</option><option value="discount">Discount</option><option value="markup">Markup</option><option value="margin">Target profit margin</option></select></label><div className="form-grid"><label>{mode==='change'?'Old value':'Amount / cost'}<input type="number" value={a} onChange={e=>setA(Number(e.target.value))}/></label><label>{mode==='change'?'New value':'Percent'}<input type="number" value={b} onChange={e=>setB(Number(e.target.value))}/></label></div><div className="hero-result"><small>{label}</small><strong>{Number.isFinite(result)?result.toLocaleString(undefined,{maximumFractionDigits:2}):'—'}{mode==='change'?'%':''}</strong></div></div>}

const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
export function ListRandomizer(){const[text,setText]=useState(''),[teams,setTeams]=useState(2),[output,setOutput]=useState('');const items=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);return <div className="stack"><label>One item per line<textarea rows="12" value={text} onChange={e=>setText(e.target.value)}/></label><div className="button-row"><button className="secondary" disabled={!items.length} onClick={()=>setOutput(shuffle(items).join('\n'))}>Shuffle list</button><button className="secondary" disabled={!items.length} onClick={()=>setOutput(items[Math.floor(Math.random()*items.length)]||'')}>Pick one</button></div><label>Number of teams<input type="number" min="2" max="20" value={teams} onChange={e=>setTeams(e.target.value)}/></label><button className="primary" disabled={!items.length} onClick={()=>{const groups=Array.from({length:Number(teams)},()=>[]);shuffle(items).forEach((v,i)=>groups[i%groups.length].push(v));setOutput(groups.map((g,i)=>`Team ${i+1}\n${g.join('\n')}`).join('\n\n'))}}>Split into teams</button><textarea rows="14" value={output} readOnly/></div>}

const hexToRgb=h=>{const x=h.replace('#','').trim();if(!/^[0-9a-f]{6}$/i.test(x))return null;return{x:parseInt(x.slice(0,2),16),y:parseInt(x.slice(2,4),16),z:parseInt(x.slice(4,6),16)}}
const rgbToHex=(r,g,b)=>'#'+[r,g,b].map(n=>clamp(Math.round(Number(n)||0),0,255).toString(16).padStart(2,'0')).join('').toUpperCase()
const rgbToHsl=(r,g,b)=>{r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),l=(max+min)/2;let h=0,s=0;if(max!==min){const d=max-min;s=l>.5?d/(2-max-min):d/(max+min);if(max===r)h=(g-b)/d+(g<b?6:0);else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;h/=6}return{h:Math.round(h*360),s:Math.round(s*100),l:Math.round(l*100)}}
export function ColorConverter(){const[hex,setHex]=useState('#2563EB'),[r,setR]=useState(37),[g,setG]=useState(99),[b,setB]=useState(235);function fromHex(){const v=hexToRgb(hex);if(v){setR(v.x);setG(v.y);setB(v.z)}}useEffect(fromHex,[]);const hsl=rgbToHsl(Number(r),Number(g),Number(b)),computed=rgbToHex(r,g,b);return <div className="stack"><div className="form-grid"><label>HEX<input value={hex} onChange={e=>setHex(e.target.value)} onBlur={fromHex}/></label><label>Preview<div className="color-preview" style={{background:computed}}/></label></div><div className="form-grid three"><label>R<input type="number" min="0" max="255" value={r} onChange={e=>setR(e.target.value)}/></label><label>G<input type="number" min="0" max="255" value={g} onChange={e=>setG(e.target.value)}/></label><label>B<input type="number" min="0" max="255" value={b} onChange={e=>setB(e.target.value)}/></label></div><div className="result-table"><div><span>HEX</span><strong>{computed}</strong></div><div><span>RGB</span><strong>rgb({r}, {g}, {b})</strong></div><div><span>HSL</span><strong>hsl({hsl.h}, {hsl.s}%, {hsl.l}%)</strong></div></div></div>}

export function CsvColumnTool(){const[file,setFile]=useState(null),[rows,setRows]=useState([]),[columns,setColumns]=useState([]),[selected,setSelected]=useState([]),[msg,setMsg]=useState('');async function load(f){try{const wb=XLSX.read(await f.arrayBuffer()),ws=wb.Sheets[wb.SheetNames[0]],data=XLSX.utils.sheet_to_json(ws,{defval:''}),cols=data[0]?Object.keys(data[0]):[];setFile(f);setRows(data);setColumns(cols);setSelected(cols);setMsg(`${data.length} rows and ${cols.length} columns loaded.`)}catch(e){setMsg(e.message)}}function save(){const data=rows.map(r=>Object.fromEntries(selected.map(c=>[c,r[c]]))),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data),'Cleaned');XLSX.writeFile(wb,`${safeBaseName(file.name)}-columns.xlsx`)}return <div className="stack"><FileDrop accept=".csv,.xlsx,.xls" onFiles={f=>load(f[0])}/>{columns.length>0&&<><div className="check-grid">{columns.map(c=><label key={c}><input type="checkbox" checked={selected.includes(c)} onChange={e=>setSelected(s=>e.target.checked?[...s,c]:s.filter(x=>x!==c))}/>{c}</label>)}</div><div className="button-row"><button className="secondary" onClick={()=>setSelected(columns)}>Select all</button><button className="secondary" onClick={()=>setSelected([])}>Clear</button><button className="primary" disabled={!selected.length} onClick={save}>Export selected columns</button></div></>}<Status>{msg}</Status></div>}

export function WifiQr(){const[ssid,setSsid]=useState(''),[password,setPassword]=useState(''),[security,setSecurity]=useState('WPA'),[hidden,setHidden]=useState(false),[url,setUrl]=useState(''),[msg,setMsg]=useState('');async function run(){try{const esc=s=>String(s).replace(/([\\;,:"])/g,'\\$1'),payload=`WIFI:T:${security};S:${esc(ssid)};P:${esc(password)};H:${hidden?'true':'false'};;`;setUrl(await QRCode.toDataURL(payload,{width:700,margin:2}));setMsg('Wi-Fi QR created. Test it before printing large batches.')}catch(e){setMsg(e.message)}}return <div className="stack"><div className="form-grid"><label>Wi-Fi name (SSID)<input value={ssid} onChange={e=>setSsid(e.target.value)}/></label><label>Security<select value={security} onChange={e=>setSecurity(e.target.value)}><option value="WPA">WPA/WPA2/WPA3</option><option value="WEP">WEP</option><option value="nopass">No password</option></select></label></div><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={hidden} onChange={e=>setHidden(e.target.checked)}/> Hidden network</label><button className="primary" disabled={!ssid} onClick={run}>Generate Wi-Fi QR</button>{url&&<div className="qr-preview"><img src={url} alt="Wi-Fi QR"/><a className="secondary" href={url} download="deskora-wifi-qr.png">Download PNG</a></div>}<Status>{msg}</Status></div>}

export function NumberToolkit(){const[text,setText]=useState('');const nums=(text.match(/-?\d+(?:\.\d+)?/g)||[]).map(Number).filter(Number.isFinite),sorted=[...nums].sort((a,b)=>a-b),sum=nums.reduce((a,b)=>a+b,0),avg=nums.length?sum/nums.length:0,median=sorted.length?(sorted.length%2?sorted[(sorted.length-1)/2]:(sorted[sorted.length/2-1]+sorted[sorted.length/2])/2):0;return <div className="stack"><label>Numbers<textarea rows="10" value={text} onChange={e=>setText(e.target.value)} placeholder="Paste numbers separated by spaces, commas, or lines…"/></label><div className="metric-grid"><div><strong>{nums.length}</strong><span>Count</span></div><div><strong>{sum.toLocaleString()}</strong><span>Sum</span></div><div><strong>{avg.toLocaleString(undefined,{maximumFractionDigits:4})}</strong><span>Average</span></div><div><strong>{median.toLocaleString(undefined,{maximumFractionDigits:4})}</strong><span>Median</span></div></div><div className="result-table"><div><span>Minimum</span><strong>{nums.length?Math.min(...nums):'—'}</strong></div><div><span>Maximum</span><strong>{nums.length?Math.max(...nums):'—'}</strong></div><div><span>Sorted</span><strong>{sorted.slice(0,100).join(', ')||'—'}</strong></div></div></div>}

export function TextExtractor(){const[text,setText]=useState(''),[type,setType]=useState('emails');const output=useMemo(()=>{let m=[];if(type==='emails')m=text.match(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g)||[];else if(type==='urls')m=text.match(/https?:\/\/[^\s<>"]+/gi)||[];else if(type==='phones')m=text.match(/(?:\+?\d[\d\s().-]{6,}\d)/g)||[];else m=text.match(/-?\d+(?:[.,]\d+)?/g)||[];return [...new Set(m.map(x=>x.trim()))]},[text,type]);return <div className="stack"><label>Extract<select value={type} onChange={e=>setType(e.target.value)}><option value="emails">Email addresses</option><option value="urls">URLs</option><option value="phones">Phone-like numbers</option><option value="numbers">Numbers</option></select></label><label>Source text<textarea rows="12" value={text} onChange={e=>setText(e.target.value)}/></label><div className="file-row"><span>{output.length} unique result{output.length===1?'':'s'}</span><button className="mini" disabled={!output.length} onClick={()=>navigator.clipboard.writeText(output.join('\n'))}>Copy</button></div><div className="code-result pre">{output.join('\n')||'Nothing found yet.'}</div></div>}
