import { useMemo, useState } from 'react'
import QRCode from 'qrcode'
import { downloadBlob } from '../lib'

const copy = async (text) => navigator.clipboard?.writeText(text)
const downloadText = (text,name,type='text/plain') => downloadBlob(new Blob([text],{type}),name)

function Output({children,copyText}){return <div className="it-output"><pre>{children}</pre>{copyText&&<button className="secondary" onClick={()=>copy(copyText)}>Copy</button>}</div>}
function Row({children}){return <div className="form-grid">{children}</div>}

const ipToInt=ip=>{const p=ip.trim().split('.').map(Number);if(p.length!==4||p.some(n=>!Number.isInteger(n)||n<0||n>255))throw new Error('Enter a valid IPv4 address.');return (((p[0]<<24)>>>0)+(p[1]<<16)+(p[2]<<8)+p[3])>>>0}
const intToIp=n=>[n>>>24,(n>>>16)&255,(n>>>8)&255,n&255].join('.')
const subnetInfo=(ip,prefix)=>{prefix=Number(prefix);if(prefix<0||prefix>32)throw new Error('Prefix must be 0–32.');const i=ipToInt(ip),mask=prefix===0?0:(0xffffffff<<(32-prefix))>>>0,network=(i&mask)>>>0,broadcast=(network|(~mask>>>0))>>>0,total=2**(32-prefix),usable=prefix>=31?total:Math.max(0,total-2);return {network,broadcast,total,usable,first:prefix>=31?network:network+1,last:prefix>=31?broadcast:broadcast-1,mask}}

export function IpRangePlanner(){const[ip,setIp]=useState('192.168.1.10'),[prefix,setPrefix]=useState(24),[reserved,setReserved]=useState(20);let r,e;try{r=subnetInfo(ip,prefix);const gw=r.first;const start=Math.min(r.last,gw+1+Number(reserved||0));return <div className="stack"><Row><label>IPv4<input value={ip} onChange={e=>setIp(e.target.value)}/></label><label>CIDR prefix<input type="number" min="0" max="32" value={prefix} onChange={e=>setPrefix(e.target.value)}/></label></Row><label>Addresses to reserve after gateway<input type="number" min="0" value={reserved} onChange={e=>setReserved(e.target.value)}/></label><div className="metric-grid"><div><strong>{intToIp(r.network)}</strong><span>Network</span></div><div><strong>{intToIp(r.broadcast)}</strong><span>Broadcast</span></div><div><strong>{r.usable}</strong><span>Usable hosts</span></div><div><strong>{intToIp(gw)}</strong><span>Suggested gateway</span></div></div><Output copyText={`Network: ${intToIp(r.network)}/${prefix}\nGateway: ${intToIp(gw)}\nReserved: ${intToIp(gw+1)} - ${intToIp(Math.max(gw+1,start-1))}\nSuggested DHCP: ${intToIp(start)} - ${intToIp(r.last)}`}>{`Suggested reserved block: ${intToIp(gw+1)} – ${intToIp(Math.max(gw+1,start-1))}\nSuggested DHCP pool: ${intToIp(start)} – ${intToIp(r.last)}`}</Output></div>}catch(x){e=x.message}return <Output>{e}</Output>}

export function DhcpPlanner(){const[ip,setIp]=useState('192.168.1.1'),[prefix,setPrefix]=useState(24),[low,setLow]=useState(50),[high,setHigh]=useState(200);let text='';try{const r=subnetInfo(ip,prefix),s=Math.min(r.last,r.network+Number(low)),en=Math.min(r.last,r.network+Number(high));text=`Scope: ${intToIp(r.network)}/${prefix}\nMask: ${intToIp(r.mask)}\nGateway suggestion: ${intToIp(r.first)}\nDHCP pool: ${intToIp(s)} - ${intToIp(en)}\nPool size: ${Math.max(0,en-s+1)}\nReserved/static suggestion: ${intToIp(r.first+1)} - ${intToIp(Math.max(r.first+1,s-1))}` }catch(e){text=e.message}return <div className="stack"><Row><label>Network IP<input value={ip} onChange={e=>setIp(e.target.value)}/></label><label>Prefix<input type="number" value={prefix} onChange={e=>setPrefix(e.target.value)}/></label></Row><Row><label>Pool start host number<input type="number" value={low} onChange={e=>setLow(e.target.value)}/></label><label>Pool end host number<input type="number" value={high} onChange={e=>setHigh(e.target.value)}/></label></Row><Output copyText={text}>{text}</Output></div>}

export function NetworkCommandBuilder(){const[target,setTarget]=useState('192.168.1.1'),[dns,setDns]=useState(true),[route,setRoute]=useState(true),[arp,setArp]=useState(true);const lines=[`ping -n 4 ${target}`,`tracert ${target}`,dns?`nslookup ${target}`:'',route?'route print':'',arp?'arp -a':'','ipconfig /all'].filter(Boolean);const text=lines.join('\r\n');return <div className="stack"><label>Target hostname or IP<input value={target} onChange={e=>setTarget(e.target.value)}/></label><div className="check-row"><label><input type="checkbox" checked={dns} onChange={e=>setDns(e.target.checked)}/> DNS lookup</label><label><input type="checkbox" checked={route} onChange={e=>setRoute(e.target.checked)}/> Routes</label><label><input type="checkbox" checked={arp} onChange={e=>setArp(e.target.checked)}/> ARP table</label></div><Output copyText={text}>{text}</Output></div>}

export function NetworkResetBuilder(){const[renew,setRenew]=useState(true),[winsock,setWinsock]=useState(true);const text=`@echo off\r\ntitle Deskora Network Repair\r\necho Running network repair as Administrator is recommended.\r\nipconfig /flushdns\r\n${renew?'ipconfig /release\r\nipconfig /renew\r\n':''}${winsock?'netsh winsock reset\r\nnetsh int ip reset\r\n':''}echo.\r\necho Repair commands completed. Restart Windows if Winsock/IP reset was used.\r\npause`;return <div className="stack"><div className="status warn">This script changes Windows networking. Review it first and run as Administrator only when needed.</div><div className="check-row"><label><input type="checkbox" checked={renew} onChange={e=>setRenew(e.target.checked)}/> Release/Renew DHCP</label><label><input type="checkbox" checked={winsock} onChange={e=>setWinsock(e.target.checked)}/> Reset Winsock/IP stack</label></div><Output copyText={text}>{text}</Output><button className="primary" onClick={()=>downloadText(text,'deskora-network-repair.bat')}>Download BAT</button></div>}

export function PrinterFixBuilder(){const[clear,setClear]=useState(true);const text=`@echo off\r\ntitle Deskora Printer Spooler Repair\r\nnet stop spooler\r\n${clear?'del /Q /F "%systemroot%\\System32\\spool\\PRINTERS\\*" 2>nul\r\n':''}net start spooler\r\necho Printer spooler repair completed.\r\npause`;return <div className="stack"><div className="status warn">Closing active print jobs may remove queued documents.</div><label className="check-row"><input type="checkbox" checked={clear} onChange={e=>setClear(e.target.checked)}/> Clear stuck print queue</label><Output copyText={text}>{text}</Output><button className="primary" onClick={()=>downloadText(text,'deskora-printer-spooler-fix.bat')}>Download BAT</button></div>}

export function MapDriveBuilder(){const[drive,setDrive]=useState('Z:'),[server,setServer]=useState('fileserver'),[share,setShare]=useState('shared'),[persistent,setPersistent]=useState(true);const unc=`\\\\${server.replace(/^\\+|\\+$/g,'')}\\${share.replace(/^\\+|\\+$/g,'')}`,cmd=`net use ${drive.toUpperCase()} "${unc}" /persistent:${persistent?'yes':'no'}`;return <div className="stack"><Row><label>Drive letter<input value={drive} onChange={e=>setDrive(e.target.value)}/></label><label>Server / IP<input value={server} onChange={e=>setServer(e.target.value)}/></label></Row><label>Share name<input value={share} onChange={e=>setShare(e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={persistent} onChange={e=>setPersistent(e.target.checked)}/> Reconnect at sign-in</label><Output copyText={cmd}>{cmd}</Output><button className="primary" onClick={()=>downloadText(`@echo off\r\n${cmd}\r\npause`,'map-network-drive.bat')}>Download BAT</button></div>}

export function RobocopyBuilder(){const[src,setSrc]=useState('C:\\Source'),[dst,setDst]=useState('D:\\Backup'),[mirror,setMirror]=useState(false),[threads,setThreads]=useState(8);const cmd=`robocopy "${src}" "${dst}" ${mirror?'/MIR':'/E'} /Z /R:2 /W:2 /COPY:DAT /DCOPY:T /MT:${threads} /TEE`;return <div className="stack"><Row><label>Source folder<input value={src} onChange={e=>setSrc(e.target.value)}/></label><label>Destination folder<input value={dst} onChange={e=>setDst(e.target.value)}/></label></Row><label>Threads<input type="number" min="1" max="128" value={threads} onChange={e=>setThreads(e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={mirror} onChange={e=>setMirror(e.target.checked)}/> Mirror destination (/MIR)</label>{mirror&&<div className="status warn">/MIR can delete destination files that no longer exist in the source. Verify both paths first.</div>}<Output copyText={cmd}>{cmd}</Output></div>}

export function RdpBuilder(){const[host,setHost]=useState('192.168.1.100'),[port,setPort]=useState(3389),[full,setFull]=useState(true),[admin,setAdmin]=useState(false);const cmd=`mstsc /v:${host}${Number(port)!==3389?`:${port}`:''}${full?' /f':''}${admin?' /admin':''}`;return <div className="stack"><Row><label>PC hostname / IP<input value={host} onChange={e=>setHost(e.target.value)}/></label><label>RDP port<input type="number" value={port} onChange={e=>setPort(e.target.value)}/></label></Row><div className="check-row"><label><input type="checkbox" checked={full} onChange={e=>setFull(e.target.checked)}/> Full screen</label><label><input type="checkbox" checked={admin} onChange={e=>setAdmin(e.target.checked)}/> Admin session</label></div><Output copyText={cmd}>{cmd}</Output></div>}

export function UncPathBuilder(){const[server,setServer]=useState('192.168.1.34'),[share,setShare]=useState('Shared'),[folder,setFolder]=useState('');const path=`\\\\${server.replace(/[\\/]+/g,'')}\\${share.replace(/^[\\/]+|[\\/]+$/g,'')}${folder?`\\${folder.replace(/^[\\/]+/,'').replace(/\//g,'\\')}`:''}`;return <div className="stack"><Row><label>Server/IP<input value={server} onChange={e=>setServer(e.target.value)}/></label><label>Share<input value={share} onChange={e=>setShare(e.target.value)}/></label></Row><label>Optional subfolder<input value={folder} onChange={e=>setFolder(e.target.value)}/></label><Output copyText={path}>{path}</Output></div>}

const ports=[['20/21','TCP','FTP data/control'],['22','TCP','SSH/SFTP'],['25','TCP','SMTP'],['53','TCP/UDP','DNS'],['67/68','UDP','DHCP'],['80','TCP','HTTP'],['110','TCP','POP3'],['123','UDP','NTP'],['135','TCP/UDP','Windows RPC'],['137-139','TCP/UDP','NetBIOS'],['143','TCP','IMAP'],['389','TCP/UDP','LDAP'],['443','TCP','HTTPS'],['445','TCP','SMB / Windows File Sharing'],['465','TCP','SMTPS'],['587','TCP','SMTP submission'],['636','TCP','LDAPS'],['993','TCP','IMAPS'],['995','TCP','POP3S'],['1433','TCP','Microsoft SQL Server'],['3306','TCP','MySQL'],['3389','TCP/UDP','Remote Desktop (RDP)'],['5432','TCP','PostgreSQL'],['5900','TCP','VNC'],['8080','TCP','Alternate HTTP / web apps']]
export function PortReference(){const[q,setQ]=useState('');const list=ports.filter(r=>r.join(' ').toLowerCase().includes(q.toLowerCase()));return <div className="stack"><label>Search port or service<input value={q} onChange={e=>setQ(e.target.value)} placeholder="SMB, 443, RDP…"/></label><div className="it-table">{list.map(r=><div key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span><span>{r[2]}</span></div>)}</div></div>}

export function PortRangeTool(){const[start,setStart]=useState(1),[end,setEnd]=useState(1024);const a=Math.max(0,Math.min(65535,Number(start))),b=Math.max(a,Math.min(65535,Number(end)));const classify=n=>n<=1023?'Well-known':n<=49151?'Registered':'Dynamic/Private';return <div className="stack"><Row><label>Start port<input type="number" min="0" max="65535" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End port<input type="number" min="0" max="65535" value={end} onChange={e=>setEnd(e.target.value)}/></label></Row><div className="metric-grid"><div><strong>{b-a+1}</strong><span>Ports</span></div><div><strong>{classify(a)}</strong><span>Start class</span></div><div><strong>{classify(b)}</strong><span>End class</span></div><div><strong>{a}–{b}</strong><span>Range</span></div></div></div>}

export function Ipv4Binary(){const[ip,setIp]=useState('192.168.1.34');let out='';try{const p=ip.split('.').map(Number);if(p.length!==4||p.some(n=>n<0||n>255||!Number.isInteger(n)))throw 0;out=p.map(n=>n.toString(2).padStart(8,'0')).join('.')}catch{out='Invalid IPv4 address'}return <div className="stack"><label>IPv4<input value={ip} onChange={e=>setIp(e.target.value)}/></label><Output copyText={out}>{out}</Output></div>}

export function IpConflictHelper(){const[ip,setIp]=useState('192.168.1.34');const text=`IP conflict checklist for ${ip}\n\n1. On the affected PC run: ipconfig /all\n2. Check the MAC address: getmac /v\n3. Inspect ARP cache: arp -a\n4. Ping ${ip}, then run arp -a again to see the responding MAC.\n5. Check the router/DHCP lease table for ${ip}.\n6. If the PC uses DHCP, run: ipconfig /release then ipconfig /renew\n7. If a static IP is required, reserve that address in DHCP or choose one outside the DHCP pool.\n8. Avoid assigning the same static address manually to multiple PCs.`;return <div className="stack"><label>Conflicting IP<input value={ip} onChange={e=>setIp(e.target.value)}/></label><Output copyText={text}>{text}</Output></div>}

export function SharedFolderHelper(){const[server,setServer]=useState('192.168.1.34'),[share,setShare]=useState('Shared');const unc=`\\\\${server}\\${share}`,text=`Shared folder troubleshooting: ${unc}\n\n1. Test basic reachability: ping ${server}\n2. Open File Explorer and try: ${unc}\n3. Check Windows Network Profile is Private on the LAN.\n4. Turn on Network Discovery and File and Printer Sharing for Private networks.\n5. Verify the folder is actually shared and the user/group has Share + NTFS permissions.\n6. Verify SMB TCP 445 is allowed through Windows Firewall.\n7. Check current sessions/mappings with: net use\n8. Clear a stale mapping if needed: net use ${unc} /delete\n9. Try by hostname and by IP to separate DNS/name-resolution issues from SMB issues.\n10. If subnets differ, verify routing/firewall rules between them.`;return <div className="stack"><Row><label>Server/IP<input value={server} onChange={e=>setServer(e.target.value)}/></label><label>Share<input value={share} onChange={e=>setShare(e.target.value)}/></label></Row><Output copyText={text}>{text}</Output></div>}

export function PcInfoScript(){const text=`@echo off\r\nset OUT=%USERPROFILE%\\Desktop\\Deskora-PC-Info.txt\r\necho DESKORA PC INFORMATION > "%OUT%"\r\necho Generated: %date% %time% >> "%OUT%"\r\necho. >> "%OUT%"\r\nhostname >> "%OUT%"\r\nwhoami >> "%OUT%"\r\nsysteminfo >> "%OUT%"\r\necho. >> "%OUT%"\r\nipconfig /all >> "%OUT%"\r\ngetmac /v >> "%OUT%"\r\nroute print >> "%OUT%"\r\narp -a >> "%OUT%"\r\nnet use >> "%OUT%"\r\ndriverquery >> "%OUT%"\r\necho Saved to %OUT%\r\npause`;return <div className="stack"><div className="status">Collects local Windows system/network information into a text file on the Desktop. It does not upload anything.</div><Output copyText={text}>{text}</Output><button className="primary" onClick={()=>downloadText(text,'deskora-pc-info.bat')}>Download BAT</button></div>}

export function WifiQrOffice(){const[ssid,setSsid]=useState('Office WiFi'),[pass,setPass]=useState(''),[sec,setSec]=useState('WPA'),[data,setData]=useState('');async function generate(){const payload=`WIFI:T:${sec};S:${ssid.replace(/([;,:\\])/g,'\\$1')};P:${pass.replace(/([;,:\\])/g,'\\$1')};;`;setData(await QRCode.toDataURL(payload,{width:420,margin:2}))}return <div className="stack"><Row><label>Wi-Fi name (SSID)<input value={ssid} onChange={e=>setSsid(e.target.value)}/></label><label>Security<select value={sec} onChange={e=>setSec(e.target.value)}><option>WPA</option><option>WEP</option><option value="nopass">Open</option></select></label></Row><label>Password<input type="password" value={pass} onChange={e=>setPass(e.target.value)}/></label><button className="primary" onClick={generate}>Generate Wi-Fi QR</button>{data&&<div className="qr-preview"><img src={data} alt="Wi-Fi QR"/><a className="secondary" href={data} download="office-wifi-qr.png">Download PNG</a></div>}</div>}

export function HostnameGenerator(){const[site,setSite]=useState('HQ'),[dept,setDept]=useState('IT'),[type,setType]=useState('PC'),[count,setCount]=useState(10);const names=useMemo(()=>Array.from({length:Math.min(200,Math.max(1,Number(count)||1))},(_,i)=>`${site}-${dept}-${type}${String(i+1).padStart(3,'0')}`.toUpperCase().replace(/[^A-Z0-9-]/g,'').slice(0,15)),[site,dept,type,count]);const text=names.join('\n');return <div className="stack"><Row><label>Site code<input value={site} onChange={e=>setSite(e.target.value)}/></label><label>Department<input value={dept} onChange={e=>setDept(e.target.value)}/></label></Row><Row><label>Device code<input value={type} onChange={e=>setType(e.target.value)}/></label><label>How many<input type="number" min="1" max="200" value={count} onChange={e=>setCount(e.target.value)}/></label></Row><Output copyText={text}>{text}</Output></div>}

export function RandomToken(){const[len,setLen]=useState(32),[out,setOut]=useState('');function makeHex(){const a=new Uint8Array(Math.ceil(len/2));crypto.getRandomValues(a);setOut(Array.from(a,b=>b.toString(16).padStart(2,'0')).join('').slice(0,len))}function pin(){const a=new Uint32Array(1);crypto.getRandomValues(a);setOut(String(a[0]%1000000).padStart(6,'0'))}return <div className="stack"><label>Hex token length<input type="number" min="8" max="128" value={len} onChange={e=>setLen(e.target.value)}/></label><div className="button-row"><button className="primary" onClick={makeHex}>Generate hex token</button><button className="secondary" onClick={()=>setOut(crypto.randomUUID())}>Generate UUID</button><button className="secondary" onClick={pin}>Generate 6-digit PIN</button></div>{out&&<Output copyText={out}>{out}</Output>}</div>}

export const itToolComponents={
  'ip-range-planner':IpRangePlanner,'dhcp-planner':DhcpPlanner,'network-command-builder':NetworkCommandBuilder,'network-reset-builder':NetworkResetBuilder,'printer-fix-builder':PrinterFixBuilder,'map-drive-builder':MapDriveBuilder,'robocopy-builder':RobocopyBuilder,'rdp-builder':RdpBuilder,'unc-path-builder':UncPathBuilder,'port-reference':PortReference,'port-range-tool':PortRangeTool,'ipv4-binary':Ipv4Binary,'ip-conflict-helper':IpConflictHelper,'shared-folder-helper':SharedFolderHelper,'pc-info-script':PcInfoScript,'wifi-qr-office':WifiQrOffice,'hostname-generator':HostnameGenerator,'random-token':RandomToken,
}
