import { useMemo, useState } from 'react'
import QRCode from 'qrcode'
import { downloadBlob } from '../lib'

const copyText=t=>navigator.clipboard?.writeText(String(t))
const downloadText=(t,n)=>downloadBlob(new Blob([t],{type:'text/plain'}),n)
const clean=s=>String(s??'').trim()
function Grid({children}){return <div className="form-grid">{children}</div>}
function Out({text,download}){return <div className="itv2-output"><pre>{text}</pre><div className="button-row compact"><button className="secondary" onClick={()=>copyText(text)}>Copy</button>{download&&<button className="primary" onClick={()=>downloadText(text,download)}>Download</button>}</div></div>}
function Notes({items}){return <ol className="itv2-notes">{items.map((x,i)=><li key={i}>{x}</li>)}</ol>}

const ipParts=ip=>{const p=clean(ip).split('.').map(Number);if(p.length!==4||p.some(n=>!Number.isInteger(n)||n<0||n>255))throw new Error('Enter a valid IPv4 address.');return p}
const ipInt=ip=>{const p=ipParts(ip);return (((p[0]<<24)>>>0)+(p[1]<<16)+(p[2]<<8)+p[3])>>>0}
const intIp=n=>[n>>>24,(n>>>16)&255,(n>>>8)&255,n&255].join('.')
const info=(ip,prefix)=>{prefix=Number(prefix);if(prefix<0||prefix>32)throw new Error('CIDR prefix must be 0–32.');const i=ipInt(ip),mask=prefix===0?0:(0xffffffff<<(32-prefix))>>>0,network=(i&mask)>>>0,broadcast=(network|(~mask>>>0))>>>0,total=2**(32-prefix),first=prefix>=31?network:network+1,last=prefix>=31?broadcast:broadcast-1;return{prefix,mask,network,broadcast,total,first,last,usable:prefix>=31?total:Math.max(0,total-2)}}
const maskToWildcard=m=>intIp((~m)>>>0)

function IpRangePlanner({dhcp=false}){const[ip,setIp]=useState('192.168.1.10'),[prefix,setPrefix]=useState(24),[start,setStart]=useState(50),[end,setEnd]=useState(200);let text='';try{const r=info(ip,prefix),gw=r.first,s=Math.min(r.last,r.network+Number(start)),e=Math.min(r.last,r.network+Number(end));text=`Network: ${intIp(r.network)}/${r.prefix}\nSubnet mask: ${intIp(r.mask)}\nGateway suggestion: ${intIp(gw)}\nBroadcast: ${intIp(r.broadcast)}\nUsable hosts: ${r.usable}${dhcp?`\nDHCP pool: ${intIp(s)} - ${intIp(e)}\nPool size: ${Math.max(0,e-s+1)}\nStatic/reserved suggestion: ${intIp(gw+1)} - ${intIp(Math.max(gw+1,s-1))}`:`\nUsable range: ${intIp(r.first)} - ${intIp(r.last)}`}`}catch(e){text=e.message}return <div className="stack"><Grid><label>IPv4 address<input value={ip} onChange={e=>setIp(e.target.value)}/></label><label>CIDR prefix<input type="number" min="0" max="32" value={prefix} onChange={e=>setPrefix(e.target.value)}/></label></Grid>{dhcp&&<Grid><label>Pool start host<input type="number" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Pool end host<input type="number" value={end} onChange={e=>setEnd(e.target.value)}/></label></Grid>}<Out text={text}/></div>}
function Wildcard(){const[prefix,setPrefix]=useState(24);let text='';try{const r=info('10.0.0.1',prefix);text=`/${prefix}\nSubnet mask: ${intIp(r.mask)}\nWildcard mask: ${maskToWildcard(r.mask)}\nAddresses: ${r.total.toLocaleString()}`}catch(e){text=e.message}return <div className="stack"><label>CIDR prefix<input type="number" min="0" max="32" value={prefix} onChange={e=>setPrefix(e.target.value)}/></label><Out text={text}/></div>}
function Ipv4Binary(){const[ip,setIp]=useState('192.168.1.34');let text='';try{text=ipParts(ip).map(n=>n.toString(2).padStart(8,'0')).join('.')}catch(e){text=e.message}return <div className="stack"><label>IPv4<input value={ip} onChange={e=>setIp(e.target.value)}/></label><Out text={text}/></div>}
function ReverseDns(){const[ip,setIp]=useState('192.168.1.34');let text='';try{text=ipParts(ip).reverse().join('.')+'.in-addr.arpa'}catch(e){text=e.message}return <div className="stack"><label>IPv4<input value={ip} onChange={e=>setIp(e.target.value)}/></label><Out text={text}/></div>}
function VlanPlanner(){const[id,setId]=useState(10),[name,setName]=useState('STAFF'),[subnet,setSubnet]=useState('192.168.10.0/24'),[gw,setGw]=useState('192.168.10.1'),[purpose,setPurpose]=useState('Office workstations');const text=`VLAN ${id} — ${name}\nSubnet: ${subnet}\nGateway: ${gw}\nPurpose: ${purpose}\nSuggested SSID/label: ${name}-${id}`;return <div className="stack"><Grid><label>VLAN ID<input type="number" min="1" max="4094" value={id} onChange={e=>setId(e.target.value)}/></label><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label></Grid><Grid><label>Subnet<input value={subnet} onChange={e=>setSubnet(e.target.value)}/></label><label>Gateway<input value={gw} onChange={e=>setGw(e.target.value)}/></label></Grid><label>Purpose<input value={purpose} onChange={e=>setPurpose(e.target.value)}/></label><Out text={text}/></div>}

function DnsRecord(){const[type,setType]=useState('A'),[host,setHost]=useState('app.example.com'),[value,setValue]=useState('192.0.2.10'),[ttl,setTtl]=useState(3600);const line=type==='MX'?`${host}. ${ttl} IN MX 10 ${value}.`:type==='SRV'?`_service._tcp.${host}. ${ttl} IN SRV 10 10 443 ${value}.`:`${host}. ${ttl} IN ${type} ${type==='TXT'?`"${value}"`:value}`;return <div className="stack"><Grid><label>Record type<select value={type} onChange={e=>setType(e.target.value)}><option>A</option><option>CNAME</option><option>MX</option><option>TXT</option><option>SRV</option><option>PTR</option></select></label><label>TTL<input type="number" value={ttl} onChange={e=>setTtl(e.target.value)}/></label></Grid><label>Host / name<input value={host} onChange={e=>setHost(e.target.value)}/></label><label>Value / target<input value={value} onChange={e=>setValue(e.target.value)}/></label><Out text={line}/></div>}
function DnsCommands(){const[target,setTarget]=useState('example.com'),[server,setServer]=useState('8.8.8.8');const text=`nslookup ${target}\nnslookup ${target} ${server}\nipconfig /displaydns\nipconfig /flushdns\nResolve-DnsName ${target}\nResolve-DnsName ${target} -Server ${server}`;return <div className="stack"><Grid><label>Host/domain<input value={target} onChange={e=>setTarget(e.target.value)}/></label><label>DNS server<input value={server} onChange={e=>setServer(e.target.value)}/></label></Grid><Out text={text}/></div>}
function NetworkCommands(){const[target,setTarget]=useState('192.168.1.1');const text=`ping -n 4 ${target}\ntracert ${target}\npathping ${target}\nnslookup ${target}\narp -a\nroute print\nipconfig /all\ngetmac /v`;return <div className="stack"><label>Target hostname/IP<input value={target} onChange={e=>setTarget(e.target.value)}/></label><Out text={text}/></div>}
function NetworkReset(){const text=`@echo off\ntitle Deskora Network Repair\necho Review before running as Administrator.\nipconfig /flushdns\nipconfig /release\nipconfig /renew\nnetsh winsock reset\nnetsh int ip reset\necho Completed. Restart Windows if needed.\npause`;return <div className="stack"><div className="status warn">This changes Windows networking. Review the script before running it as Administrator.</div><Out text={text} download="deskora-network-repair.bat"/></div>}
function FirewallRule(){const[name,setName]=useState('Deskora App'),[port,setPort]=useState(3000),[dir,setDir]=useState('in'),[protocol,setProtocol]=useState('TCP');const cmd=`netsh advfirewall firewall add rule name="${name}" dir=${dir} action=allow protocol=${protocol} localport=${port}`;return <div className="stack"><Grid><label>Rule name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Port<input type="number" min="1" max="65535" value={port} onChange={e=>setPort(e.target.value)}/></label></Grid><Grid><label>Direction<select value={dir} onChange={e=>setDir(e.target.value)}><option value="in">Inbound</option><option value="out">Outbound</option></select></label><label>Protocol<select value={protocol} onChange={e=>setProtocol(e.target.value)}><option>TCP</option><option>UDP</option></select></label></Grid><div className="status warn">Only create rules you understand. Restrict scope in Windows Firewall when possible.</div><Out text={cmd}/></div>}
function RouteBuilder(){const[dest,setDest]=useState('192.168.254.0'),[mask,setMask]=useState('255.255.255.0'),[gw,setGw]=useState('192.168.1.1'),[persistent,setPersistent]=useState(true);const cmd=`route ${persistent?'-p ':''}add ${dest} mask ${mask} ${gw}`;return <div className="stack"><Grid><label>Destination network<input value={dest} onChange={e=>setDest(e.target.value)}/></label><label>Mask<input value={mask} onChange={e=>setMask(e.target.value)}/></label></Grid><label>Gateway<input value={gw} onChange={e=>setGw(e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={persistent} onChange={e=>setPersistent(e.target.checked)}/> Persistent route</label><Out text={`${cmd}\nDelete later: route delete ${dest}`}/></div>}
function HostsBuilder(){const[ip,setIp]=useState('192.168.1.34'),[host,setHost]=useState('parcel-server'),[comment,setComment]=useState('Office server');return <div className="stack"><Grid><label>IP<input value={ip} onChange={e=>setIp(e.target.value)}/></label><label>Hostname<input value={host} onChange={e=>setHost(e.target.value)}/></label></Grid><label>Comment<input value={comment} onChange={e=>setComment(e.target.value)}/></label><Out text={`${ip}\t${host}${comment?`\t# ${comment}`:''}`}/></div>}

const ports=[['20/21','TCP','FTP'],['22','TCP','SSH/SFTP'],['25','TCP','SMTP'],['53','TCP/UDP','DNS'],['67/68','UDP','DHCP'],['80','TCP','HTTP'],['123','UDP','NTP'],['135','TCP/UDP','Windows RPC'],['137-139','TCP/UDP','NetBIOS'],['143','TCP','IMAP'],['389','TCP/UDP','LDAP'],['443','TCP','HTTPS'],['445','TCP','SMB'],['587','TCP','SMTP submission'],['636','TCP','LDAPS'],['993','TCP','IMAPS'],['1433','TCP','MS SQL'],['3306','TCP','MySQL'],['3389','TCP/UDP','RDP'],['5432','TCP','PostgreSQL'],['5900','TCP','VNC'],['8080','TCP','Alternate HTTP']]
function PortReference(){const[q,setQ]=useState('');const rows=ports.filter(r=>r.join(' ').toLowerCase().includes(q.toLowerCase()));return <div className="stack"><label>Search<input value={q} onChange={e=>setQ(e.target.value)} placeholder="SMB, 443, RDP…"/></label><div className="itv2-table">{rows.map(r=><div key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span><span>{r[2]}</span></div>)}</div></div>}
function PortRange(){const[a,setA]=useState(1),[b,setB]=useState(1024);const x=Math.max(0,Math.min(65535,Number(a))),y=Math.max(x,Math.min(65535,Number(b)));const c=n=>n<=1023?'Well-known':n<=49151?'Registered':'Dynamic/Private';return <div className="stack"><Grid><label>Start<input type="number" value={a} onChange={e=>setA(e.target.value)}/></label><label>End<input type="number" value={b} onChange={e=>setB(e.target.value)}/></label></Grid><Out text={`Range: ${x}-${y}\nCount: ${y-x+1}\nStart class: ${c(x)}\nEnd class: ${c(y)}`}/></div>}

function PrinterFix(){const text=`@echo off\ntitle Deskora Printer Spooler Repair\nnet stop spooler\ndel /Q /F "%systemroot%\\System32\\spool\\PRINTERS\\*" 2>nul\nnet start spooler\necho Completed.\npause`;return <div className="stack"><div className="status warn">Clearing the spool folder removes queued print jobs.</div><Out text={text} download="deskora-printer-fix.bat"/></div>}
function PrinterPlanner(){const[name,setName]=useState('OFFICE-PRN-01'),[ip,setIp]=useState('192.168.1.50'),[gw,setGw]=useState('192.168.1.1'),[mask,setMask]=useState('255.255.255.0'),[port,setPort]=useState(9100);const text=`Printer: ${name}\nIP: ${ip}\nMask: ${mask}\nGateway: ${gw}\nRAW print port: ${port}\nRecommendation: reserve ${ip} for the printer MAC in DHCP.`;return <div className="stack"><Grid><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>IP<input value={ip} onChange={e=>setIp(e.target.value)}/></label></Grid><Grid><label>Mask<input value={mask} onChange={e=>setMask(e.target.value)}/></label><label>Gateway<input value={gw} onChange={e=>setGw(e.target.value)}/></label></Grid><label>RAW port<input type="number" value={port} onChange={e=>setPort(e.target.value)}/></label><Out text={text}/></div>}
function SharedFolder(){const[server,setServer]=useState('192.168.1.34'),[share,setShare]=useState('Shared');return <div className="stack"><Out text={`\\\\${server}\\${share}\n\n1. ping ${server}\n2. Open \\\\${server}\\${share}\n3. Check Network Profile = Private.\n4. Enable Network Discovery and File & Printer Sharing.\n5. Verify Share + NTFS permissions.\n6. Verify TCP 445 is allowed.\n7. Run: net use\n8. Test by hostname and IP separately.\n9. If subnets differ, verify routing/firewall between them.`}/></div>}
function Unc(){const[s,setS]=useState('192.168.1.34'),[share,setShare]=useState('Shared'),[folder,setFolder]=useState('');const p=`\\\\${clean(s).replace(/[\\/]+/g,'')}\\${clean(share).replace(/[\\/]+/g,'')}${folder?`\\${clean(folder).replace(/\//g,'\\')}`:''}`;return <div className="stack"><Grid><label>Server/IP<input value={s} onChange={e=>setS(e.target.value)}/></label><label>Share<input value={share} onChange={e=>setShare(e.target.value)}/></label></Grid><label>Subfolder<input value={folder} onChange={e=>setFolder(e.target.value)}/></label><Out text={p}/></div>}
function MapDrive(){const[d,setD]=useState('Z:'),[s,setS]=useState('fileserver'),[share,setShare]=useState('Shared'),[persist,setPersist]=useState(true);const cmd=`net use ${d.toUpperCase()} "\\\\${s}\\${share}" /persistent:${persist?'yes':'no'}`;return <div className="stack"><Grid><label>Drive<input value={d} onChange={e=>setD(e.target.value)}/></label><label>Server<input value={s} onChange={e=>setS(e.target.value)}/></label></Grid><label>Share<input value={share} onChange={e=>setShare(e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={persist} onChange={e=>setPersist(e.target.checked)}/> Reconnect at sign-in</label><Out text={cmd} download="map-network-drive.bat"/></div>}
function Robocopy(){const[src,setSrc]=useState('C:\\Source'),[dst,setDst]=useState('D:\\Backup'),[mirror,setMirror]=useState(false);const cmd=`robocopy "${src}" "${dst}" ${mirror?'/MIR':'/E'} /Z /R:2 /W:2 /COPY:DAT /DCOPY:T /MT:8 /TEE`;return <div className="stack"><Grid><label>Source<input value={src} onChange={e=>setSrc(e.target.value)}/></label><label>Destination<input value={dst} onChange={e=>setDst(e.target.value)}/></label></Grid><label className="check-row"><input type="checkbox" checked={mirror} onChange={e=>setMirror(e.target.checked)}/> Mirror (/MIR)</label>{mirror&&<div className="status warn">/MIR can delete destination files not present in source.</div>}<Out text={cmd}/></div>}
function Rdp(){const[h,setH]=useState('192.168.1.100'),[p,setP]=useState(3389);return <div className="stack"><Grid><label>Host/IP<input value={h} onChange={e=>setH(e.target.value)}/></label><label>Port<input type="number" value={p} onChange={e=>setP(e.target.value)}/></label></Grid><Out text={`mstsc /v:${h}${Number(p)!==3389?`:${p}`:''} /f`}/></div>}

const remoteNotes=['Confirm the user has approved remote support.','Record PC name, username, IP and issue summary.','Check internet/LAN connection first.','Ask the user to save open work before restart or repair actions.','Use the least-privileged support method available.','Document commands/changes performed.','Verify the original problem is resolved before ending the session.']
function RemoteChecklist(){return <Notes items={remoteNotes}/>} 
function PcInfo(){const text=`@echo off\nset OUT=%USERPROFILE%\\Desktop\\Deskora-PC-Info.txt\necho COMPUTER > "%OUT%"\nhostname >> "%OUT%"\nwhoami >> "%OUT%"\nsysteminfo >> "%OUT%"\necho. >> "%OUT%"\nipconfig /all >> "%OUT%"\ngetmac /v >> "%OUT%"\nroute print >> "%OUT%"\nnet use >> "%OUT%"\necho Saved to %OUT%\npause`;return <Out text={text} download="deskora-pc-info.bat"/>}
function SystemRepair(){return <div className="stack"><div className="status warn">Run elevated commands only when appropriate. CHKDSK repairs may require restart.</div><Out text={`sfc /scannow\nDISM /Online /Cleanup-Image /ScanHealth\nDISM /Online /Cleanup-Image /RestoreHealth\nchkdsk C: /scan`}/></div>}
function DiskCleanup(){return <Out text={`cleanmgr\nstart %temp%\nstart C:\\Windows\\Temp\nPowerShell -NoProfile -Command "Get-ChildItem $env:TEMP | Measure-Object -Property Length -Sum"\n# Review temporary files before deletion.`}/>} 
const services=[['DHCP Client','DHCP address assignment'],['DNS Client','DNS caching/name resolution'],['Print Spooler','Printing'],['Server','SMB file/printer sharing'],['Workstation','SMB client connections'],['WLAN AutoConfig','Wi-Fi'],['Remote Desktop Services','RDP'],['Windows Update','Windows updates']]
function ServiceChecklist(){return <div className="itv2-table">{services.map(r=><div key={r[0]}><strong>{r[0]}</strong><span>Windows</span><span>{r[1]}</span></div>)}</div>}
function Startup(){return <Notes items={['Open Task Manager → Startup apps and sort by Startup impact.','Disable only non-essential startup apps, one group at a time.','Check free disk space and disk health.','Review Event Viewer → Windows Logs → System for boot errors.','Run a malware/security scan if startup behavior changed unexpectedly.','Check Windows Update and driver status.','Re-enable items if disabling them does not improve startup.']}/>} 
const devCodes=[['10','Device cannot start'],['12','Not enough free resources'],['19','Registry/configuration information damaged'],['22','Device disabled'],['28','Drivers not installed'],['31','Windows cannot load required drivers'],['43','Device reported a problem'],['45','Device is not connected']]
function DeviceCodes(){const[q,setQ]=useState('');return <div className="stack"><label>Search code/meaning<input value={q} onChange={e=>setQ(e.target.value)}/></label><div className="itv2-table">{devCodes.filter(r=>r.join(' ').toLowerCase().includes(q.toLowerCase())).map(r=><div key={r[0]}><strong>Code {r[0]}</strong><span>Device Manager</span><span>{r[1]}</span></div>)}</div></div>}
function EventViewer(){return <Notes items={['Application: app crashes, installer errors, application services.','System: drivers, network adapters, disks, services, boot and shutdown.','Security: sign-in/audit events when auditing is enabled.','Setup: Windows setup and servicing events.','Filter Current Log by Critical/Error/Warning and the time the issue happened.','Record Event ID, Source, timestamp and full message before changing settings.']}/>} 
function IpConflict(){const[ip,setIp]=useState('192.168.1.34');return <div className="stack"><label>Conflicting IP<input value={ip} onChange={e=>setIp(e.target.value)}/></label><Out text={`IP conflict checklist for ${ip}\n1. ipconfig /all\n2. getmac /v\n3. arp -a\n4. ping ${ip} then arp -a\n5. Check router/DHCP lease table.\n6. For DHCP client: ipconfig /release then ipconfig /renew\n7. Reserve static devices in DHCP or keep them outside the dynamic pool.`}/></div>}
function Hostname({asset=false}){const[site,setSite]=useState('MNL'),[dept,setDept]=useState('IT'),[type,setType]=useState(asset?'PC':'WS'),[seq,setSeq]=useState(1),[count,setCount]=useState(10);const rows=Array.from({length:Math.min(100,Math.max(1,Number(count)))},(_,i)=>`${site}-${dept}-${type}-${String(Number(seq)+i).padStart(3,'0')}`);return <div className="stack"><Grid><label>Site<input value={site} onChange={e=>setSite(e.target.value.toUpperCase())}/></label><label>Department<input value={dept} onChange={e=>setDept(e.target.value.toUpperCase())}/></label></Grid><Grid><label>Type<input value={type} onChange={e=>setType(e.target.value.toUpperCase())}/></label><label>Start sequence<input type="number" value={seq} onChange={e=>setSeq(e.target.value)}/></label></Grid><label>How many<input type="number" min="1" max="100" value={count} onChange={e=>setCount(e.target.value)}/></label><Out text={rows.join('\n')}/></div>}

function WifiQr(){const[ssid,setSsid]=useState('Office WiFi'),[pass,setPass]=useState(''),[sec,setSec]=useState('WPA'),[data,setData]=useState('');async function go(){const esc=s=>String(s).replace(/([\\;,:"])/g,'\\$1');setData(await QRCode.toDataURL(sec==='nopass'?`WIFI:T:nopass;S:${esc(ssid)};;`:`WIFI:T:${sec};S:${esc(ssid)};P:${esc(pass)};;`,{width:420,margin:2}))}return <div className="stack"><Grid><label>SSID<input value={ssid} onChange={e=>setSsid(e.target.value)}/></label><label>Security<select value={sec} onChange={e=>setSec(e.target.value)}><option>WPA</option><option>WEP</option><option value="nopass">Open</option></select></label></Grid><label>Password<input type="password" value={pass} onChange={e=>setPass(e.target.value)}/></label><button className="primary" onClick={go}>Generate Wi-Fi QR</button>{data&&<img className="itv2-qr" src={data} alt="Wi-Fi QR"/>}</div>}
function WifiSignal(){const[dbm,setDbm]=useState(-65);const n=Number(dbm);const q=n>=-50?'Excellent':n>=-60?'Very good':n>=-67?'Good for normal use':n>=-70?'Fair':n>=-80?'Weak':'Very weak';return <div className="stack"><label>RSSI (dBm)<input type="number" min="-100" max="-20" value={dbm} onChange={e=>setDbm(e.target.value)}/></label><Out text={`${dbm} dBm — ${q}\nCloser to 0 is stronger. -30 dBm is extremely strong; around -67 dBm is usually adequate for common office use.`}/></div>}
function WifiChannels(){const[count,setCount]=useState(3);const chans=[1,6,11];const rows=Array.from({length:Math.min(30,Math.max(1,Number(count)))},(_,i)=>`AP ${i+1}: Channel ${chans[i%3]}`);return <div className="stack"><label>Nearby 2.4 GHz APs<input type="number" min="1" max="30" value={count} onChange={e=>setCount(e.target.value)}/></label><Out text={`${rows.join('\n')}\n\nFor 20 MHz 2.4 GHz planning, channels 1, 6 and 11 are the common non-overlapping choices.`}/></div>}
function Ethernet(){return <div className="itv2-pinouts"><Out text={`T568A\n1 White/Green\n2 Green\n3 White/Orange\n4 Blue\n5 White/Blue\n6 Orange\n7 White/Brown\n8 Brown`}/><Out text={`T568B\n1 White/Orange\n2 Orange\n3 White/Green\n4 Blue\n5 White/Blue\n6 Green\n7 White/Brown\n8 Brown`}/></div>}
function TransferTime(){const[size,setSize]=useState(10),[unit,setUnit]=useState('GB'),[mbps,setMbps]=useState(100);const bytes=Number(size)*(unit==='GB'?1e9:unit==='MB'?1e6:1e12),sec=bytes*8/(Number(mbps)*1e6||1);return <div className="stack"><Grid><label>File size<input type="number" min="0" value={size} onChange={e=>setSize(e.target.value)}/></label><label>Unit<select value={unit} onChange={e=>setUnit(e.target.value)}><option>MB</option><option>GB</option><option>TB</option></select></label></Grid><label>Link speed (Mbps)<input type="number" min="0.1" value={mbps} onChange={e=>setMbps(e.target.value)}/></label><Out text={`Ideal transfer time: ${Math.floor(sec/3600)}h ${Math.floor(sec%3600/60)}m ${Math.round(sec%60)}s\nReal transfers are usually slower due to protocol, storage and network overhead.`}/></div>}
function Poe(){const[budget,setBudget]=useState(120),[devices,setDevices]=useState(8),[watts,setWatts]=useState(12);const used=Number(devices)*Number(watts);return <div className="stack"><Grid><label>Switch PoE budget (W)<input type="number" value={budget} onChange={e=>setBudget(e.target.value)}/></label><label>Devices<input type="number" value={devices} onChange={e=>setDevices(e.target.value)}/></label></Grid><label>Average watts/device<input type="number" value={watts} onChange={e=>setWatts(e.target.value)}/></label><Out text={`Estimated load: ${used.toFixed(1)} W\nRemaining budget: ${(Number(budget)-used).toFixed(1)} W\nUtilization: ${((used/Number(budget))*100||0).toFixed(1)}%`}/></div>}
function Ups(){const[wh,setWh]=useState(216),[load,setLoad]=useState(120),[eff,setEff]=useState(80);const mins=(Number(wh)*(Number(eff)/100)/(Number(load)||1))*60;return <div className="stack"><Grid><label>Battery energy (Wh)<input type="number" value={wh} onChange={e=>setWh(e.target.value)}/></label><label>Load (W)<input type="number" value={load} onChange={e=>setLoad(e.target.value)}/></label></Grid><label>Estimated efficiency %<input type="number" min="1" max="100" value={eff} onChange={e=>setEff(e.target.value)}/></label><Out text={`Approximate runtime: ${mins.toFixed(0)} minutes\nActual UPS runtime varies with battery age, inverter efficiency, temperature and load curve.`}/></div>}
function Raid(){const[drives,setDrives]=useState(4),[size,setSize]=useState(4),[raid,setRaid]=useState('5');const n=Number(drives),s=Number(size);let usable=0;if(raid==='0')usable=n*s;if(raid==='1')usable=n>=2?s:0;if(raid==='5')usable=n>=3?(n-1)*s:0;if(raid==='6')usable=n>=4?(n-2)*s:0;if(raid==='10')usable=n>=4&&n%2===0?(n/2)*s:0;return <div className="stack"><Grid><label>Drives<input type="number" min="1" value={drives} onChange={e=>setDrives(e.target.value)}/></label><label>Each drive (TB)<input type="number" min="0" value={size} onChange={e=>setSize(e.target.value)}/></label></Grid><label>RAID<select value={raid} onChange={e=>setRaid(e.target.value)}><option>0</option><option>1</option><option>5</option><option>6</option><option>10</option></select></label><Out text={`Estimated usable capacity: ${usable} TB\nRaw capacity: ${n*s} TB\nRAID is not a replacement for backups.`}/></div>}
function NumBase(){const[value,setValue]=useState('255'),[base,setBase]=useState(10);let n;try{n=parseInt(value,Number(base));if(!Number.isFinite(n))throw 0}catch{n=0}return <div className="stack"><Grid><label>Value<input value={value} onChange={e=>setValue(e.target.value)}/></label><label>Input base<select value={base} onChange={e=>setBase(e.target.value)}><option value="2">Binary</option><option value="10">Decimal</option><option value="16">Hex</option></select></label></Grid><Out text={`Binary: ${n.toString(2)}\nDecimal: ${n.toString(10)}\nHex: ${n.toString(16).toUpperCase()}`}/></div>}
function ChecksumCmd(){const[path,setPath]=useState('C:\\path\\file.iso'),[algo,setAlgo]=useState('SHA256');return <div className="stack"><Grid><label>File path<input value={path} onChange={e=>setPath(e.target.value)}/></label><label>Algorithm<select value={algo} onChange={e=>setAlgo(e.target.value)}><option>SHA256</option><option>SHA1</option><option>MD5</option></select></label></Grid><Out text={`PowerShell: Get-FileHash -Algorithm ${algo} "${path}"\ncertutil: certutil -hashfile "${path}" ${algo}`}/></div>}
const httpCodes=[['100','Continue'],['101','Switching Protocols'],['103','Early Hints'],['200','OK'],['201','Created'],['204','No Content'],['301','Moved Permanently'],['302','Found / Temporary redirect'],['304','Not Modified'],['400','Bad Request'],['401','Unauthorized'],['403','Forbidden'],['404','Not Found'],['405','Method Not Allowed'],['408','Request Timeout'],['409','Conflict'],['413','Content Too Large'],['429','Too Many Requests'],['500','Internal Server Error'],['502','Bad Gateway'],['503','Service Unavailable'],['504','Gateway Timeout']]
function HttpCodes(){const[q,setQ]=useState('');return <div className="stack"><label>Search code/meaning<input value={q} onChange={e=>setQ(e.target.value)}/></label><div className="itv2-table">{httpCodes.filter(r=>r.join(' ').toLowerCase().includes(q.toLowerCase())).map(r=><div key={r[0]}><strong>{r[0]}</strong><span>HTTP</span><span>{r[1]}</span></div>)}</div></div>}
function Ticket(){const[user,setUser]=useState(''),[pc,setPc]=useState(''),[issue,setIssue]=useState(''),[priority,setPriority]=useState('Normal');const text=`IT SUPPORT TICKET\nUser: ${user}\nPC/Device: ${pc}\nPriority: ${priority}\nIssue: ${issue}\n\nSymptoms:\n- \n\nTroubleshooting performed:\n- \n\nResolution / next action:\n- \n\nDate/Time: ${new Date().toLocaleString()}`;return <div className="stack"><Grid><label>User<input value={user} onChange={e=>setUser(e.target.value)}/></label><label>PC/Device<input value={pc} onChange={e=>setPc(e.target.value)}/></label></Grid><label>Issue<textarea value={issue} onChange={e=>setIssue(e.target.value)}/></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option>Low</option><option>Normal</option><option>High</option><option>Urgent</option></select></label><Out text={text}/></div>}
function Handover(){return <Notes items={['Document ISP/router/modem details and who to contact.','Document LAN subnets, DHCP ranges, gateways, Wi-Fi SSIDs and VLANs.','List servers/NAS/shared folders and backup locations.','List printers, static IPs and driver/setup notes.','List critical websites, domains and deployment ownership.','Document recurring IT tasks and schedules.','Document vendor contacts, warranties and asset inventory location.','Transfer credentials using an approved secure method; do not put passwords in the handover document.','List known issues and temporary workarounds.','Include common troubleshooting procedures and escalation contacts.']}/>} 
function PasswordPolicy(){const[p,setP]=useState('');const checks=[['12+ characters',p.length>=12],['Uppercase',/[A-Z]/.test(p)],['Lowercase',/[a-z]/.test(p)],['Number',/\d/.test(p)],['Symbol',/[^A-Za-z0-9]/.test(p)]];const score=checks.filter(x=>x[1]).length;return <div className="stack"><label>Password<input type="password" value={p} onChange={e=>setP(e.target.value)} autoComplete="new-password"/></label><div className="metric-grid"><div><strong>{score}/5</strong><span>Policy checks</span></div><div><strong>{p.length}</strong><span>Characters</span></div></div><ul>{checks.map(([n,ok])=><li key={n}>{ok?'✓':'○'} {n}</li>)}</ul></div>}
function RandomToken(){const[len,setLen]=useState(32),[out,setOut]=useState('');function gen(){const n=Math.max(4,Math.min(256,Number(len))),a=new Uint8Array(Math.ceil(n/2));crypto.getRandomValues(a);setOut([...a].map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,n))}return <div className="stack"><label>Hex characters<input type="number" min="4" max="256" value={len} onChange={e=>setLen(e.target.value)}/></label><button className="primary" onClick={gen}>Generate secure token</button>{out&&<Out text={out}/>}<button className="secondary" onClick={()=>setOut(crypto.randomUUID())}>Generate UUID</button></div>}

function Unknown({id}){return <Out text={`Deskora IT tool: ${id}\nThis utility belongs to Deskora IT & Security.`}/>}
export function ITToolEngine(){const id=decodeURIComponent(location.pathname.split('/').pop()||'');switch(id){case'ip-range-planner':return <IpRangePlanner/>;case'dhcp-planner':return <IpRangePlanner dhcp/>;case'vlan-planner':return <VlanPlanner/>;case'wildcard-mask':return <Wildcard/>;case'ipv4-binary':return <Ipv4Binary/>;case'reverse-dns-builder':return <ReverseDns/>;case'dns-record-builder':return <DnsRecord/>;case'dns-command-builder':return <DnsCommands/>;case'network-command-builder':return <NetworkCommands/>;case'network-reset-builder':return <NetworkReset/>;case'firewall-rule-builder':return <FirewallRule/>;case'route-builder':return <RouteBuilder/>;case'hosts-entry-builder':return <HostsBuilder/>;case'port-reference':return <PortReference/>;case'port-range-tool':return <PortRange/>;case'printer-fix-builder':return <PrinterFix/>;case'printer-ip-planner':return <PrinterPlanner/>;case'shared-folder-helper':return <SharedFolder/>;case'unc-path-builder':return <Unc/>;case'map-drive-builder':return <MapDrive/>;case'robocopy-builder':return <Robocopy/>;case'rdp-builder':return <Rdp/>;case'remote-support-checklist':return <RemoteChecklist/>;case'pc-info-script':return <PcInfo/>;case'system-repair-builder':return <SystemRepair/>;case'disk-cleanup-builder':return <DiskCleanup/>;case'service-checklist':return <ServiceChecklist/>;case'startup-troubleshooter':return <Startup/>;case'device-manager-codes':return <DeviceCodes/>;case'event-viewer-helper':return <EventViewer/>;case'ip-conflict-helper':return <IpConflict/>;case'hostname-generator':return <Hostname/>;case'asset-naming-planner':return <Hostname asset/>;case'wifi-qr-office':return <WifiQr/>;case'wifi-signal-guide':return <WifiSignal/>;case'wifi-channel-planner':return <WifiChannels/>;case'ethernet-pinout':return <Ethernet/>;case'bandwidth-calculator':return <TransferTime/>;case'poe-budget':return <Poe/>;case'ups-runtime':return <Ups/>;case'raid-capacity':return <Raid/>;case'binary-hex-tool':return <NumBase/>;case'checksum-command-builder':return <ChecksumCmd/>;case'http-status-reference':return <HttpCodes/>;case'ticket-template':return <Ticket/>;case'handover-checklist':return <Handover/>;case'password-policy-checker':return <PasswordPolicy/>;case'random-token':return <RandomToken/>;default:return <Unknown id={id}/>}}

export const itToolComponentsV2={}
