import { useEffect, useRef, useState } from 'react'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import * as pdfjsLib from 'pdfjs-dist'
import pdfWorker from 'pdfjs-dist/build/pdf.worker.min.mjs?url'
import FileDrop from '../components/FileDrop'
import Status from '../components/Status'
import { downloadBlob, safeBaseName } from '../lib'

pdfjsLib.GlobalWorkerOptions.workerSrc=pdfWorker

export function PdfEditorPro(){
 const[file,setFile]=useState(null),[doc,setDoc]=useState(null),[page,setPage]=useState(0),[count,setCount]=useState(0),[mode,setMode]=useState('text'),[text,setText]=useState('Approved'),[size,setSize]=useState(18),[anns,setAnns]=useState([]),[signature,setSignature]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),canvas=useRef(null),drag=useRef(null)
 async function open(f){setBusy(true);try{const d=await pdfjsLib.getDocument({data:await f.arrayBuffer()}).promise;setFile(f);setDoc(d);setCount(d.numPages);setPage(0);setAnns([]);setMsg('Choose an annotation type, then click or drag on the page.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function draw(){if(!doc||!canvas.current)return;const p=await doc.getPage(page+1),vp=p.getViewport({scale:1.35}),c=canvas.current;c.width=vp.width;c.height=vp.height;const x=c.getContext('2d');await p.render({canvasContext:x,viewport:vp}).promise;for(const a of anns.filter(v=>v.page===page)){const px=a.x*c.width,py=a.y*c.height;if(a.type==='text'){x.fillStyle='#111827';x.font=`${a.size}px sans-serif`;x.fillText(a.text,px,py)}else if(a.type==='check'){x.fillStyle='#0f766e';x.font='bold 30px sans-serif';x.fillText('✓',px,py)}else if(a.type==='highlight'){x.fillStyle='rgba(250,204,21,.38)';x.fillRect(px,py,a.w*c.width,a.h*c.height)}else if(a.type==='box'){x.strokeStyle='#dc2626';x.lineWidth=3;x.strokeRect(px,py,a.w*c.width,a.h*c.height)}else if(a.type==='image'&&a.url){const im=new Image();await new Promise(r=>{im.onload=r;im.src=a.url});x.drawImage(im,px,py,a.w*c.width,a.h*c.height)}}}
 useEffect(()=>{draw()},[doc,page,anns])
 const pos=e=>{const r=canvas.current.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}
 function down(e){const p=pos(e);if(mode==='highlight'||mode==='box')drag.current=p;else if(mode==='text')setAnns(a=>[...a,{page,type:'text',x:p.x,y:p.y,text,size:Number(size)}]);else if(mode==='check')setAnns(a=>[...a,{page,type:'check',x:p.x,y:p.y}]);else if(mode==='image'&&signature)setAnns(a=>[...a,{page,type:'image',x:p.x,y:p.y,w:.22,h:.1,url:signature}])}
 function up(e){if(!drag.current)return;const a=drag.current,b=pos(e);drag.current=null;setAnns(v=>[...v,{page,type:mode,x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(a.x-b.x),h:Math.abs(a.y-b.y)}])}
 function loadSig(f){if(!f)return;const u=URL.createObjectURL(f);setSignature(u);setMode('image')}
 async function exportPdf(){setBusy(true);try{const pdf=await PDFDocument.load(await file.arrayBuffer()),font=await pdf.embedFont(StandardFonts.Helvetica);for(const a of anns){const p=pdf.getPage(a.page),{width,height}=p.getSize(),x=a.x*width,y=height-a.y*height;if(a.type==='text')p.drawText(a.text,{x,y,size:a.size,font,color:rgb(.07,.09,.13)});else if(a.type==='check'){const c=rgb(.04,.45,.4);p.drawLine({start:{x,y:y-7},end:{x:x+7,y:y-15},thickness:3,color:c});p.drawLine({start:{x:x+7,y:y-15},end:{x:x+20,y:y+2},thickness:3,color:c})}else if(a.type==='highlight')p.drawRectangle({x,y:y-a.h*height,width:a.w*width,height:a.h*height,color:rgb(1,.84,.2),opacity:.32});else if(a.type==='box')p.drawRectangle({x,y:y-a.h*height,width:a.w*width,height:a.h*height,borderColor:rgb(.85,.12,.12),borderWidth:2});else if(a.type==='image'){const res=await fetch(a.url),bytes=await res.arrayBuffer();let img;try{img=await pdf.embedPng(bytes)}catch{img=await pdf.embedJpg(bytes)};p.drawImage(img,{x,y:y-a.h*height,width:a.w*width,height:a.h*height})}}downloadBlob(new Blob([await pdf.save()],{type:'application/pdf'}),`${safeBaseName(file.name)}-edited-pro.pdf`);setMsg('Edited PDF exported.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <div className="stack"><FileDrop accept="application/pdf" onFiles={f=>open(f[0])}/>{file&&<><div className="editor-pro-toolbar"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="text">Text</option><option value="check">Check mark</option><option value="highlight">Highlight</option><option value="box">Rectangle</option><option value="image">Signature / image</option></select>{mode==='text'&&<><input value={text} onChange={e=>setText(e.target.value)} placeholder="Text"/><input type="number" min="8" max="72" value={size} onChange={e=>setSize(e.target.value)}/></>}{mode==='image'&&<input type="file" accept="image/png,image/jpeg" onChange={e=>loadSig(e.target.files?.[0])}/>}<button className="mini" disabled={!anns.length} onClick={()=>setAnns(a=>a.slice(0,-1))}>Undo</button><button className="mini danger" onClick={()=>setAnns(a=>a.filter(x=>x.page!==page))}>Clear page</button></div><div className="pdf-pro-canvas"><canvas ref={canvas} onPointerDown={down} onPointerUp={up}/></div><div className="button-row"><button className="secondary" disabled={page<=0} onClick={()=>setPage(p=>p-1)}>← Previous</button><span className="page-chip">Page {page+1} / {count}</span><button className="secondary" disabled={page>=count-1} onClick={()=>setPage(p=>p+1)}>Next →</button></div><button className="primary" disabled={busy} onClick={exportPdf}>Export edited PDF</button></>}<Status>{msg}</Status></div>
}
