import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { PDFDocument, StandardFonts, degrees, rgb } from 'pdf-lib'
import * as pdfjsLib from 'pdfjs-dist'
import pdfWorker from 'pdfjs-dist/build/pdf.worker.min.mjs?url'
import { createWorker } from 'tesseract.js'
import * as XLSX from 'xlsx'
import JSZip from 'jszip'
import QRCode from 'qrcode'
import FileDrop from '../components/FileDrop'
import Status from '../components/Status'
import { downloadBlob, formatBytes, safeBaseName } from '../lib'
import { toolMap, tools } from '../data-tools'
import './productivity.css'

pdfjsLib.GlobalWorkerOptions.workerSrc = pdfWorker

const readJson=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}}
const saveJson=(k,v)=>localStorage.setItem(k,JSON.stringify(v))
const blobCanvas=(c,t='image/jpeg',q=.9)=>new Promise((r,j)=>c.toBlob(b=>b?r(b):j(new Error('Could not create image')),t,q))
const imageBitmap=async f=>createImageBitmap(f)
const history=(tool,input='',output='',meta={})=>{const list=readJson('deskora-processing-history',[]);list.unshift({id:crypto.randomUUID?.()||String(Date.now()),tool,input,output,meta,at:new Date().toISOString()});saveJson('deskora-processing-history',list.slice(0,50));window.dispatchEvent(new Event('deskora-history'))}

async function sha256(file){const d=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function pdfInfo(file){const pdf=await PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:true,updateMetadata:false});return {pages:pdf.getPageCount(),title:pdf.getTitle()||'',author:pdf.getAuthor()||'',subject:pdf.getSubject()||''}}
async function renderPdfPage(doc,index,scale=1.3){const p=await doc.getPage(index+1),vp=p.getViewport({scale}),c=document.createElement('canvas');c.width=Math.round(vp.width);c.height=Math.round(vp.height);await p.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;return c}
async function ocr(input,onProgress){const worker=await createWorker('eng',1,{logger:m=>m.progress&&onProgress?.(Math.round(m.progress*100))});try{return (await worker.recognize(input)).data.text||''}finally{await worker.terminate()}}

export function SmartDashboard(){
 const[favs,setFavs]=useState(()=>readJson('deskora-favorites',[])),[recent,setRecent]=useState(()=>readJson('deskora-recent',[])),[hist,setHist]=useState(()=>readJson('deskora-processing-history',[])),[shortcuts,setShortcuts]=useState(()=>readJson('deskora-shortcuts',['camera-scanner','edit-pdf','pdf-compressor','csv-cleaner']))
 useEffect(()=>{const fn=()=>{setFavs(readJson('deskora-favorites',[]));setRecent(readJson('deskora-recent',[]));setHist(readJson('deskora-processing-history',[]));setShortcuts(readJson('deskora-shortcuts',[]))};window.addEventListener('storage',fn);window.addEventListener('deskora-history',fn);return()=>{window.removeEventListener('storage',fn);window.removeEventListener('deskora-history',fn)}},[])
 const addShortcut=id=>{const n=[id,...shortcuts.filter(x=>x!==id)].slice(0,8);setShortcuts(n);saveJson('deskora-shortcuts',n)}
 return <div className="stack dashboard-suite">
   <div className="suite-hero"><div><span className="eyebrow">Local workspace</span><h2>Your Deskora dashboard</h2><p>Favorites, shortcuts, recent tools and processing history stay on this device.</p></div><Link className="primary" to="/tools/file-analyzer">Analyze a file</Link></div>
   <section><div className="suite-heading"><h3>Quick shortcuts</h3><span>{shortcuts.length}/8 pinned</span></div><div className="shortcut-grid">{shortcuts.map(id=>toolMap[id]&&<Link key={id} to={`/tools/${id}`}><strong>{toolMap[id].name}</strong><span>{toolMap[id].category}</span></Link>)}</div><label>Add shortcut<select value="" onChange={e=>e.target.value&&addShortcut(e.target.value)}><option value="">Choose a tool…</option>{tools.filter(t=>!shortcuts.includes(t.id)).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></section>
   <div className="suite-columns"><section><div className="suite-heading"><h3>Favorites</h3><span>{favs.length}</span></div><div className="dense-list">{favs.slice(0,8).map(id=>toolMap[id]&&<Link key={id} to={`/tools/${id}`}><strong>{toolMap[id].name}</strong><span>Open →</span></Link>)}{!favs.length&&<p className="muted">Star tools in the library to pin them here.</p>}</div></section><section><div className="suite-heading"><h3>Recent tools</h3><span>{recent.length}</span></div><div className="dense-list">{recent.slice(0,8).map(id=>toolMap[id]&&<Link key={id} to={`/tools/${id}`}><strong>{toolMap[id].name}</strong><span>{toolMap[id].category}</span></Link>)}</div></section></div>
   <section><div className="suite-heading"><h3>Processing history</h3><button className="mini" onClick={()=>{saveJson('deskora-processing-history',[]);setHist([])}}>Clear</button></div><div className="history-list">{hist.slice(0,12).map(x=><div key={x.id}><div><strong>{x.tool}</strong><span>{x.input}{x.output?` → ${x.output}`:''}</span></div><time>{new Date(x.at).toLocaleString()}</time></div>)}{!hist.length&&<p className="muted">New productivity tools will record completed operations here without saving your files.</p>}</div></section>
 </div>
}

function analyzerActions(file){const n=file.name.toLowerCase(),t=file.type;if(t==='application/pdf'||n.endsWith('.pdf'))return[['Edit PDF','edit-pdf'],['Target compression','target-compression'],['Batch PDF','batch-pdf'],['OCR text','ocr-workspace'],['Organize','pdf-organizer']];if(t.startsWith('image/'))return[['Target compression','target-compression'],['OCR','ocr-workspace'],['Scan document','camera-scanner'],['ID sheet','id-picture'],['To PDF','images-to-pdf']];if(t.startsWith('video/'))return[['Compress','video-compressor'],['Trim','video-trim'],['Resize','video-social-resize']];if(/\.(xlsx?|csv)$/.test(n))return[['Inventory helper','inventory-helper'],['Clean data','csv-cleaner'],['Compare','spreadsheet-compare']];return[['Hash','file-hash'],['Rename','smart-rename'],['Organize','bulk-organizer']]}
export function FileAnalyzer(){
 const[file,setFile]=useState(null),[info,setInfo]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 async function inspect(f){if(!f)return;setFile(f);setInfo(null);setBusy(true);try{const base={name:f.name,type:f.type||'Unknown',size:formatBytes(f.size),modified:new Date(f.lastModified).toLocaleString(),sha:(await sha256(f)).slice(0,24)+'…'};if(f.type.startsWith('image/')){const b=await imageBitmap(f);base.dimensions=`${b.width} × ${b.height}px`;base.megapixels=`${(b.width*b.height/1e6).toFixed(2)} MP`;b.close()}else if(f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf'))Object.assign(base,await pdfInfo(f));else if(f.type.startsWith('video/')||f.type.startsWith('audio/')){const url=URL.createObjectURL(f),m=document.createElement(f.type.startsWith('video/')?'video':'audio');await new Promise((r,j)=>{m.onloadedmetadata=r;m.onerror=j;m.src=url});base.duration=`${m.duration.toFixed(2)} sec`;if('videoWidth'in m)base.dimensions=`${m.videoWidth} × ${m.videoHeight}px`;URL.revokeObjectURL(url)}else if(/\.(xlsx?|csv)$/i.test(f.name)){const wb=XLSX.read(await f.arrayBuffer(),{type:'array'});base.sheets=wb.SheetNames.length;base.sheetNames=wb.SheetNames.join(', ');const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:''});base.rows=Math.max(0,rows.length-1);base.columns=rows[0]?.length||0}setInfo(base);history('File Analyzer',f.name,'Analyzed');setMsg('Analysis complete. Choose a compatible action below.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 const acts=file?analyzerActions(file):[]
 return <div className="stack"><FileDrop onFiles={f=>inspect(f[0])}/>{busy&&<Status>Analyzing file locally…</Status>}{info&&<><div className="analysis-grid">{Object.entries(info).map(([k,v])=><div key={k}><span>{k.replace(/([A-Z])/g,' $1')}</span><strong>{String(v||'—')}</strong></div>)}</div><div className="quick-actions">{acts.map(([label,id])=><Link className="secondary" to={`/tools/${id}`} key={id}>{label}</Link>)}</div></>}<Status>{msg}</Status></div>
}

async function compressImageToTarget(file,targetBytes,maxW=0){const bmp=await imageBitmap(file),scale=maxW&&bmp.width>maxW?maxW/bmp.width:1,c=document.createElement('canvas');c.width=Math.round(bmp.width*scale);c.height=Math.round(bmp.height*scale);c.getContext('2d').drawImage(bmp,0,0,c.width,c.height);bmp.close();let lo=.16,hi=.96,best=null;for(let i=0;i<9;i++){const q=(lo+hi)/2,b=await blobCanvas(c,'image/jpeg',q);if(b.size<=targetBytes){best=b;lo=q}else hi=q}return best||await blobCanvas(c,'image/jpeg',.12)}
async function compressPdfTarget(file,targetBytes,onProgress){const src=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;let quality=.72,scale=1.25,last=null;for(let pass=0;pass<4;pass++){const out=await PDFDocument.create();for(let i=0;i<src.numPages;i++){onProgress?.(`Pass ${pass+1}: page ${i+1}/${src.numPages}`);const c=await renderPdfPage(src,i,scale),jpg=await blobCanvas(c,'image/jpeg',quality),img=await out.embedJpg(await jpg.arrayBuffer()),p=out.addPage([img.width,img.height]);p.drawImage(img,{x:0,y:0,width:img.width,height:img.height})}last=new Blob([await out.save()],{type:'application/pdf'});if(last.size<=targetBytes)break;quality=Math.max(.28,quality-.14);scale=Math.max(.8,scale-.14)}return last}
export function TargetSizeCompressor(){
 const[file,setFile]=useState(null),[target,setTarget]=useState(500),[unit,setUnit]=useState('KB'),[busy,setBusy]=useState(false),[out,setOut]=useState(null),[msg,setMsg]=useState(''),[preview,setPreview]=useState('')
 useEffect(()=>()=>preview&&URL.revokeObjectURL(preview),[preview])
 async function run(){setBusy(true);setMsg('Searching for the best quality near your target…');try{const bytes=Number(target)*(unit==='MB'?1024*1024:1024);let blob;if(file.type.startsWith('image/'))blob=await compressImageToTarget(file,bytes);else if(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf'))blob=await compressPdfTarget(file,bytes,setMsg);else throw new Error('Target-size mode currently supports images and PDFs.');setOut(blob);if(preview)URL.revokeObjectURL(preview);setPreview(file.type.startsWith('image/')?URL.createObjectURL(blob):'');history('Target Size Compression',`${file.name} ${formatBytes(file.size)}`,formatBytes(blob.size),{target:`${target}${unit}`});setMsg(`Finished at ${formatBytes(blob.size)}. Exact target size depends on document/image complexity.`)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 const download=()=>out&&downloadBlob(out,`${safeBaseName(file.name)}-target${file.type==='application/pdf'?'.pdf':'.jpg'}`)
 return <div className="stack"><FileDrop accept="image/*,application/pdf" onFiles={f=>{setFile(f[0]);setOut(null);setPreview('')}}/><div className="form-grid"><label>Target size<input type="number" min="10" value={target} onChange={e=>setTarget(e.target.value)}/></label><label>Unit<select value={unit} onChange={e=>setUnit(e.target.value)}><option>KB</option><option>MB</option></select></label></div>{file&&out&&<div className="metric-grid"><div><strong>{formatBytes(file.size)}</strong><span>Before</span></div><div><strong>{formatBytes(out.size)}</strong><span>After</span></div><div><strong>{Math.max(0,Math.round((1-out.size/file.size)*100))}%</strong><span>Saved</span></div></div>}{preview&&<div className="before-after"><div><span>Original</span><img src={URL.createObjectURL(file)} alt="Original preview"/></div><div><span>Compressed</span><img src={preview} alt="Compressed preview"/></div></div>}<button className="primary" disabled={!file||busy} onClick={run}>{busy?'Compressing…':'Compress toward target size'}</button><button className="secondary" disabled={!out} onClick={download}>Download result</button><Status>{msg}</Status></div>
}

async function imagePipeline(file,steps){let bmp=await imageBitmap(file),canvas=document.createElement('canvas');canvas.width=bmp.width;canvas.height=bmp.height;canvas.getContext('2d').drawImage(bmp,0,0);bmp.close();let quality=.88,format='image/jpeg';for(const s of steps){if(s.type==='resize'&&Number(s.value)>0&&canvas.width>Number(s.value)){const n=document.createElement('canvas'),r=Number(s.value)/canvas.width;n.width=Number(s.value);n.height=Math.round(canvas.height*r);n.getContext('2d').drawImage(canvas,0,0,n.width,n.height);canvas=n}else if(s.type==='quality')quality=Number(s.value);else if(s.type==='format')format=s.value}return blobCanvas(canvas,format,quality)}
async function pdfPipeline(file,steps){const src=await PDFDocument.load(await file.arrayBuffer()),out=await PDFDocument.create(),font=await out.embedFont(StandardFonts.HelveticaBold),rotate=Number(steps.find(s=>s.type==='rotate')?.value||0),water=steps.find(s=>s.type==='watermark')?.value||'';for(const i of src.getPageIndices()){const[p]=await out.copyPages(src,[i]);if(rotate)p.setRotation(degrees((p.getRotation().angle+rotate)%360));if(water){const{width,height}=p.getSize();p.drawText(water,{x:width*.2,y:height*.5,size:Math.max(20,width/18),font,color:rgb(.2,.25,.35),opacity:.16,rotate:degrees(-28)})}out.addPage(p)}return new Blob([await out.save()],{type:'application/pdf'})}
export function PipelineCenter(){
 const[file,setFile]=useState(null),[steps,setSteps]=useState([{type:'resize',value:'1600'},{type:'quality',value:'.82'}]),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[msg,setMsg]=useState('')
 const isPdf=file&&(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf'));const add=()=>setSteps(s=>[...s,{type:isPdf?'watermark':'format',value:isPdf?'CONFIDENTIAL':'image/jpeg'}]);const change=(i,k,v)=>setSteps(s=>s.map((x,n)=>n===i?{...x,[k]:v}:x));
 async function run(){setBusy(true);try{const b=isPdf?await pdfPipeline(file,steps):file?.type.startsWith('image/')?await imagePipeline(file,steps):null;if(!b)throw new Error('True chained processing currently supports images and PDFs in one pass. Video chains remain individual to avoid exhausting browser memory.');setResult(b);history('Tool Chaining 2.0',file.name,formatBytes(b.size),{steps});setMsg('Pipeline finished without intermediate downloads.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <div className="stack"><FileDrop accept="image/*,application/pdf" onFiles={f=>{setFile(f[0]);setResult(null);const pdf=f[0]&&(f[0].type==='application/pdf'||f[0].name.toLowerCase().endsWith('.pdf'));setSteps(pdf?[{type:'rotate',value:'0'},{type:'watermark',value:''}]:[{type:'resize',value:'1600'},{type:'quality',value:'.82'},{type:'format',value:'image/jpeg'}])}}/><div className="pipeline-list">{steps.map((s,i)=><div key={i}><span>{i+1}</span><select value={s.type} onChange={e=>change(i,'type',e.target.value)}>{isPdf?<><option value="rotate">Rotate</option><option value="watermark">Watermark</option></>:<><option value="resize">Max width</option><option value="quality">JPEG quality</option><option value="format">Output format</option></>}</select>{s.type==='format'?<select value={s.value} onChange={e=>change(i,'value',e.target.value)}><option value="image/jpeg">JPG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select>:s.type==='rotate'?<select value={s.value} onChange={e=>change(i,'value',e.target.value)}><option value="0">0°</option><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select>:<input value={s.value} onChange={e=>change(i,'value',e.target.value)} placeholder={s.type==='watermark'?'Watermark text':'Value'}/>}<button className="mini danger" onClick={()=>setSteps(x=>x.filter((_,n)=>n!==i))}>×</button></div>)}</div><button className="secondary" disabled={!file} onClick={add}>+ Add step</button><button className="primary" disabled={!file||busy||!steps.length} onClick={run}>{busy?'Running pipeline…':'Run all steps once'}</button><button className="secondary" disabled={!result} onClick={()=>downloadBlob(result,`${safeBaseName(file?.name)}-pipeline${isPdf?'.pdf':'.jpg'}`)}>Download final output</button><Status>{msg}</Status></div>
}

export function BatchProcessingCenter(){
 const[files,setFiles]=useState([]),[mode,setMode]=useState('image-compress'),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 async function run(){setBusy(true);try{const zip=new JSZip();let done=0;for(const f of files){let b,name;if(mode==='image-compress'){if(!f.type.startsWith('image/'))continue;b=await compressImageToTarget(f,Math.max(80*1024,f.size*.55),2000);name=`images/${safeBaseName(f.name)}.jpg`}else if(mode==='pdf-rotate'){if(f.type!=='application/pdf'&&!f.name.toLowerCase().endsWith('.pdf'))continue;b=await pdfPipeline(f,[{type:'rotate',value:'90'}]);name=`pdf/${safeBaseName(f.name)}-rotated.pdf`}else{b=f;name=`original/${f.name}`}zip.file(name,b);done++;setMsg(`Processed ${done}/${files.length}…`)}const blob=await zip.generateAsync({type:'blob'});downloadBlob(blob,'deskora-batch-output.zip');history('Batch Processing',`${files.length} files`,`${done} processed`);setMsg(`Done — ${done} compatible files packaged.`)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <div className="stack"><FileDrop multiple onFiles={setFiles}/><label>Batch action<select value={mode} onChange={e=>setMode(e.target.value)}><option value="image-compress">Compress all images</option><option value="pdf-rotate">Rotate all PDFs 90°</option><option value="package">Package unchanged by type</option></select></label>{files.length>0&&<Status>{files.length} files selected • {formatBytes(files.reduce((a,f)=>a+f.size,0))}</Status>}<button className="primary" disabled={!files.length||busy} onClick={run}>{busy?'Processing batch…':'Run batch & download ZIP'}</button><Status>{msg}</Status></div>
}

export function OcrWorkspace(){
 const[file,setFile]=useState(null),[text,setText]=useState(''),[progress,setProgress]=useState(0),[busy,setBusy]=useState(false),[preview,setPreview]=useState(''),[msg,setMsg]=useState('')
 async function choose(f){setFile(f);setText('');if(preview)URL.revokeObjectURL(preview);if(f.type.startsWith('image/'))setPreview(URL.createObjectURL(f));else setPreview('')}
 async function run(){setBusy(true);setProgress(0);try{let out='';if(file.type==='application/pdf'){const doc=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;for(let i=0;i<doc.numPages;i++){const c=await renderPdfPage(doc,i,1.65);out+=`${i?'\n\n--- Page '+(i+1)+' ---\n\n':''}${await ocr(c,setProgress)}`}}else out=await ocr(file,setProgress);setText(out);history('OCR Workspace',file.name,`${out.length} characters`);setMsg('OCR complete. Correct the text side-by-side, then copy or export it.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <div className="stack"><FileDrop accept="image/*,application/pdf" onFiles={f=>choose(f[0])}/>{busy&&<div className="progress"><span style={{width:`${progress}%`}}/></div>}<button className="primary" disabled={!file||busy} onClick={run}>{busy?`Recognizing ${progress}%`:'Run OCR'}</button><div className="ocr-workspace">{preview?<div className="ocr-preview"><img src={preview} alt="Source document"/></div>:<div className="ocr-preview placeholder">PDF source loaded</div>}<label>Recognized & editable text<textarea value={text} onChange={e=>setText(e.target.value)} rows="18"/></label></div><div className="button-row"><button className="secondary" disabled={!text} onClick={()=>navigator.clipboard.writeText(text)}>Copy corrected text</button><button className="secondary" disabled={!text} onClick={()=>downloadBlob(new Blob([text],{type:'text/plain'}),`${safeBaseName(file?.name)}-ocr.txt`)}>TXT</button></div><Status>{msg}</Status></div>
}

function parseReceipt(text){const lines=text.split(/\n/).map(x=>x.trim()).filter(Boolean),money=lines.map(x=>({line:x,m:x.match(/(?:₱|PHP\s*)?([0-9][0-9,]*\.[0-9]{2})/i)})).filter(x=>x.m),total=money.findLast?.(x=>/total|amount due|grand/i.test(x.line))||money.at(-1);const date=text.match(/\b(?:20\d{2}[-/.]\d{1,2}[-/.]\d{1,2}|\d{1,2}[-/.]\d{1,2}[-/.]20\d{2})\b/)?.[0]||'';return {merchant:lines[0]||'',date,total:total?Number(total.m[1].replace(/,/g,'')):0,raw:text}}
export function ExpenseWorkspace(){
 const[files,setFiles]=useState([]),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[msg,setMsg]=useState('')
 async function run(){setBusy(true);try{const result=[];for(let i=0;i<files.length;i++){setMsg(`Reading receipt ${i+1}/${files.length}…`);const t=await ocr(files[i],setProgress);result.push({...parseReceipt(t),file:files[i].name})}setRows(result);history('Receipt Expense Workspace',`${files.length} receipts`,`${result.length} rows`);setMsg('Review extracted fields before exporting.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 const change=(i,k,v)=>setRows(r=>r.map((x,n)=>n===i?{...x,[k]:v}:x));function exportXlsx(){const ws=XLSX.utils.json_to_sheet(rows.map(({merchant,date,total,file})=>({Date:date,Merchant:merchant,Amount:Number(total)||0,Source:file}))),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Expenses');const out=XLSX.write(wb,{bookType:'xlsx',type:'array'});downloadBlob(new Blob([out]),'deskora-expenses.xlsx')}
 return <div className="stack"><FileDrop accept="image/*" multiple onFiles={setFiles}/>{busy&&<div className="progress"><span style={{width:`${progress}%`}}/></div>}<button className="primary" disabled={!files.length||busy} onClick={run}>Scan receipts into expense table</button>{rows.length>0&&<div className="expense-table"><div className="expense-head"><span>Date</span><span>Merchant</span><span>Amount</span><span>Source</span></div>{rows.map((r,i)=><div key={i}><input value={r.date} onChange={e=>change(i,'date',e.target.value)}/><input value={r.merchant} onChange={e=>change(i,'merchant',e.target.value)}/><input type="number" step=".01" value={r.total} onChange={e=>change(i,'total',e.target.value)}/><span>{r.file}</span></div>)}</div>}<button className="secondary" disabled={!rows.length} onClick={exportXlsx}>Export expense report XLSX</button><Status>{msg}</Status></div>
}

export function AssetLabelGenerator(){
 const[asset,setAsset]=useState('PC-IT-001'),[name,setName]=useState('Dell Workstation'),[dept,setDept]=useState('IT Department'),[serial,setSerial]=useState(''),[count,setCount]=useState(8),[url,setUrl]=useState(''),canvas=useRef(null),[msg,setMsg]=useState('')
 async function make(){try{const c=canvas.current;c.width=1200;c.height=1697;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);const cols=2,rows=Math.ceil(Number(count)/cols),gap=32,pad=50,w=(c.width-pad*2-gap)/2,h=Math.min(310,(c.height-pad*2-gap*(rows-1))/rows);for(let i=0;i<Number(count);i++){const col=i%2,row=Math.floor(i/2),ox=pad+col*(w+gap),oy=pad+row*(h+gap);x.strokeStyle='#cbd5e1';x.lineWidth=3;x.strokeRect(ox,oy,w,h);x.fillStyle='#0f172a';x.font='bold 34px sans-serif';x.fillText(asset,ox+24,oy+50);x.font='26px sans-serif';x.fillText(name,ox+24,oy+94);x.fillStyle='#64748b';x.font='22px sans-serif';x.fillText(dept,ox+24,oy+132);x.fillText(serial?`S/N: ${serial}`:'Asset label',ox+24,oy+168);const q=document.createElement('canvas');await QRCode.toCanvas(q,[asset,name,dept,serial].filter(Boolean).join(' | '),{width:120,margin:1});x.drawImage(q,ox+w-145,oy+20,120,120)}setUrl(c.toDataURL('image/png'));history('Asset Label Generator',asset,`${count} labels`);setMsg('A4 label sheet generated.')}catch(e){setMsg(e.message)}}
 return <div className="stack"><div className="form-grid"><label>Asset ID<input value={asset} onChange={e=>setAsset(e.target.value)}/></label><label>Device / item<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Department<input value={dept} onChange={e=>setDept(e.target.value)}/></label><label>Serial number<input value={serial} onChange={e=>setSerial(e.target.value)}/></label><label>Labels<input type="number" min="1" max="10" value={count} onChange={e=>setCount(e.target.value)}/></label></div><button className="primary" onClick={make}>Generate A4 labels</button><div className="canvas-wrap label-preview"><canvas ref={canvas}/></div><button className="secondary" disabled={!url} onClick={()=>canvas.current.toBlob(b=>downloadBlob(b,'deskora-asset-labels.png'))}>Download A4 PNG</button><Status>{msg}</Status></div>
}

export function InventoryHelper(){
 const[file,setFile]=useState(null),[rows,setRows]=useState([]),[idCol,setIdCol]=useState(''),[nameCol,setNameCol]=useState(''),[msg,setMsg]=useState('')
 async function load(f){try{setFile(f);const wb=XLSX.read(await f.arrayBuffer(),{type:'array'}),data=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});setRows(data);const keys=Object.keys(data[0]||{});setIdCol(keys[0]||'');setNameCol(keys[1]||keys[0]||'');setMsg(`${data.length} inventory rows loaded.`)}catch(e){setMsg(e.message)}}
 const keys=Object.keys(rows[0]||{});async function exportLabels(){const zip=new JSZip();for(let i=0;i<rows.length;i++){const q=document.createElement('canvas'),id=String(rows[i][idCol]||i+1),name=String(rows[i][nameCol]||'');await QRCode.toCanvas(q,JSON.stringify(rows[i]),{width:360,margin:2});const b=await blobCanvas(q,'image/png');zip.file(`${String(i+1).padStart(3,'0')}-${safeBaseName(id)}-${safeBaseName(name)}.png`,b)}downloadBlob(await zip.generateAsync({type:'blob'}),'deskora-inventory-qr.zip');history('Inventory CSV Helper',file?.name,`${rows.length} QR labels`)}
 return <div className="stack"><FileDrop accept=".csv,.xlsx,.xls" onFiles={f=>load(f[0])}/>{rows.length>0&&<><div className="form-grid"><label>Asset ID column<select value={idCol} onChange={e=>setIdCol(e.target.value)}>{keys.map(k=><option key={k}>{k}</option>)}</select></label><label>Name column<select value={nameCol} onChange={e=>setNameCol(e.target.value)}>{keys.map(k=><option key={k}>{k}</option>)}</select></label></div><div className="metric-grid"><div><strong>{rows.length}</strong><span>Inventory rows</span></div><div><strong>{keys.length}</strong><span>Columns</span></div></div><button className="primary" onClick={exportLabels}>Generate QR label ZIP</button></>}<Status>{msg}</Status></div>
}

const presets=[
 {name:'Email-ready PDF',desc:'Compress a PDF for smaller attachments.',tool:'target-compression',query:'?target=4&unit=MB'},
 {name:'2×2 ID photo',desc:'Open ID Picture Sheet for common 2×2 printing.',tool:'id-picture',query:'?preset=2x2'},
 {name:'Office scan',desc:'Camera scan with document cleanup workflow.',tool:'camera-scanner',query:'?mode=enhanced'},
 {name:'Instagram Reel',desc:'Open social video resize at 9:16.',tool:'video-social-resize',query:'?ratio=9:16'},
 {name:'Invoice OCR',desc:'Open the corrected-text OCR workspace.',tool:'ocr-workspace',query:'?type=invoice'},
 {name:'Confidential PDF',desc:'Batch watermark or redact office PDFs.',tool:'batch-pdf',query:'?mode=watermark'},
]
export function TemplateCenter(){return <div className="stack"><div className="template-grid">{presets.map(p=><Link key={p.name} to={`/tools/${p.tool}${p.query}`}><span className="badge">Preset</span><h3>{p.name}</h3><p>{p.desc}</p><strong>Open preset →</strong></Link>)}</div><Status>Preset URLs are bookmarkable and shareable. Deskora keeps the file itself on your device.</Status></div>}

export function BatchPdfOperations(){
 const[files,setFiles]=useState([]),[mode,setMode]=useState('watermark'),[text,setText]=useState('CONFIDENTIAL'),[angle,setAngle]=useState(90),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 async function run(){setBusy(true);try{const zip=new JSZip();let n=0;for(const f of files){const src=await PDFDocument.load(await f.arrayBuffer()),out=await PDFDocument.create(),font=await out.embedFont(StandardFonts.HelveticaBold);for(const i of src.getPageIndices()){const[p]=await out.copyPages(src,[i]);if(mode==='rotate')p.setRotation(degrees((p.getRotation().angle+Number(angle))%360));else{const{width,height}=p.getSize();p.drawText(text,{x:width*.18,y:height*.5,size:Math.max(24,width/14),font,color:rgb(.15,.18,.25),opacity:.16,rotate:degrees(-28)})}out.addPage(p)}zip.file(`${safeBaseName(f.name)}-${mode}.pdf`,await out.save());n++;setMsg(`Processed ${n}/${files.length} PDFs…`)}downloadBlob(await zip.generateAsync({type:'blob'}),'deskora-batch-pdf.zip');history('Batch PDF Operations',`${files.length} PDFs`,mode);setMsg('Batch PDF ZIP downloaded.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <div className="stack"><FileDrop accept="application/pdf" multiple onFiles={setFiles}/><label>Operation<select value={mode} onChange={e=>setMode(e.target.value)}><option value="watermark">Watermark every PDF</option><option value="rotate">Rotate every PDF</option></select></label>{mode==='watermark'?<label>Watermark text<input value={text} onChange={e=>setText(e.target.value)}/></label>:<label>Angle<select value={angle} onChange={e=>setAngle(e.target.value)}><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></label>}<button className="primary" disabled={!files.length||busy} onClick={run}>{busy?'Processing…':'Process PDFs & ZIP'}</button><Status>{msg}</Status></div>
}

export function MultiFileWorkspace(){
 const[files,setFiles]=useState([]),[active,setActive]=useState(0);const f=files[active];
 function add(list){setFiles(x=>[...x,...list]);setActive(files.length)}
 return <div className="stack"><FileDrop multiple onFiles={add} hint="Open several files as local workspace tabs. Files are held only in this browser tab."/><div className="workspace-tabs">{files.map((x,i)=><button key={`${x.name}-${i}`} className={i===active?'active':''} onClick={()=>setActive(i)}>{x.name}<span onClick={e=>{e.stopPropagation();setFiles(v=>v.filter((_,n)=>n!==i));setActive(0)}}>×</span></button>)}</div>{f&&<div className="workspace-inspector"><div><strong>{f.name}</strong><span>{f.type||'Unknown'} • {formatBytes(f.size)}</span></div><div className="quick-actions">{analyzerActions(f).map(([label,id])=><Link key={id} className="secondary" to={`/tools/${id}`}>{label}</Link>)}</div></div>}<Status>{files.length?`${files.length} local workspace tab${files.length===1?'':'s'} open.`:'Open files to start a desktop-like Deskora session.'}</Status></div>
}
