import { useMemo, useState } from 'react'
import JSZip from 'jszip'
import FileDrop from '../components/FileDrop'
import Status from '../components/Status'
import { downloadBlob, formatBytes } from '../lib'

export function ZipCreator(){const[files,setFiles]=useState([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');async function run(){try{setBusy(true);const z=new JSZip();files.forEach(f=>z.file(f.name,f));const blob=await z.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}});downloadBlob(blob,'deskora-files.zip');setMsg(`Created ZIP • ${formatBytes(blob.size)}`)}catch(e){setMsg(e.message)}finally{setBusy(false)}}return <div className="stack"><FileDrop multiple onFiles={setFiles}/>{files.length>0&&<Status>{files.length} files selected • {formatBytes(files.reduce((a,f)=>a+f.size,0))}</Status>}<button className="primary" disabled={!files.length||busy} onClick={run}>{busy?'Creating…':'Create ZIP'}</button><Status>{msg}</Status></div>}

export function ZipExtractor(){const[file,setFile]=useState(null),[entries,setEntries]=useState([]),[msg,setMsg]=useState('');async function load(f){setFile(f);try{const z=await JSZip.loadAsync(f);setEntries(Object.values(z.files).filter(x=>!x.dir).map(x=>({name:x.name,entry:x})));setMsg('Archive opened locally.')}catch(e){setMsg(e.message)}}async function dl(e){downloadBlob(await e.entry.async('blob'),e.name.split('/').pop())}return <div className="stack"><FileDrop accept=".zip,application/zip" onFiles={f=>load(f[0])}/>{file&&<Status>{file.name} • {entries.length} files</Status>}<div className="file-list">{entries.slice(0,100).map((e,i)=><div className="file-row" key={i}><span>{e.name}</span><button className="mini" onClick={()=>dl(e)}>Download</button></div>)}</div><Status>{msg}</Status></div>}

export function FileHash(){const[file,setFile]=useState(null),[hash,setHash]=useState(''),[msg,setMsg]=useState('');async function run(){try{const digest=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());setHash([...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join(''));setMsg('SHA-256 generated locally.')}catch(e){setMsg(e.message)}}return <div className="stack"><FileDrop onFiles={f=>setFile(f[0])}/>{file&&<Status>{file.name} • {formatBytes(file.size)}</Status>}<button className="primary" disabled={!file} onClick={run}>Generate SHA-256</button>{hash&&<div className="code-result">{hash}</div>}<Status>{msg}</Status></div>}

export function FileCompare(){const[a,setA]=useState(null),[b,setB]=useState(null),[result,setResult]=useState('');async function run(){if(a.size!==b.size){setResult('Different — file sizes do not match.');return}const[ab,bb]=await Promise.all([a.arrayBuffer(),b.arrayBuffer()]);const av=new Uint8Array(ab),bv=new Uint8Array(bb);let same=true;for(let i=0;i<av.length;i++){if(av[i]!==bv[i]){same=false;break}}setResult(same?'Identical — the files are byte-for-byte the same.':'Different — file contents do not match.')}return <div className="stack"><div className="compare-inputs"><div><strong>File A</strong><FileDrop onFiles={f=>setA(f[0])} label={a?a.name:'Choose first file'}/></div><div><strong>File B</strong><FileDrop onFiles={f=>setB(f[0])} label={b?b.name:'Choose second file'}/></div></div><button className="primary" disabled={!a||!b} onClick={run}>Compare files</button><Status type={result.startsWith('Identical')?'success':'info'}>{result}</Status></div>}

function intToIp(n){return[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255].join('.')}
function ipToInt(ip){const p=ip.split('.').map(Number);if(p.length!==4||p.some(n=>n<0||n>255||!Number.isInteger(n)))throw new Error('Enter a valid IPv4 address.');return (((p[0]<<24)>>>0)+(p[1]<<16)+(p[2]<<8)+p[3])>>>0}
export function SubnetCalculator(){const[ip,setIp]=useState('192.168.1.34'),[cidr,setCidr]=useState(24);const calc=useMemo(()=>{try{const c=Number(cidr);if(c<0||c>32)throw new Error('CIDR must be from 0 to 32.');const n=ipToInt(ip);const mask=c===0?0:(0xffffffff<<(32-c))>>>0;const network=(n&mask)>>>0;const broadcast=(network|(~mask>>>0))>>>0;const total=2**(32-c);return{result:{mask:intToIp(mask),network:intToIp(network),broadcast:intToIp(broadcast),first:c>=31?'N/A':intToIp((network+1)>>>0),last:c>=31?'N/A':intToIp((broadcast-1)>>>0),hosts:c===32?1:c===31?2:Math.max(0,total-2)},error:''}}catch(e){return{result:null,error:e.message}}},[ip,cidr]);return <div className="stack"><div className="form-grid"><label>IPv4 address<input value={ip} onChange={e=>setIp(e.target.value)}/></label><label>CIDR<input type="number" min="0" max="32" value={cidr} onChange={e=>setCidr(e.target.value)}/></label></div>{calc.error?<Status type="warn">{calc.error}</Status>:calc.result&&<div className="result-table"><div><span>Subnet mask</span><strong>{calc.result.mask}</strong></div><div><span>Network</span><strong>{calc.result.network}/{cidr}</strong></div><div><span>Broadcast</span><strong>{calc.result.broadcast}</strong></div><div><span>Usable range</span><strong>{calc.result.first} — {calc.result.last}</strong></div><div><span>Usable hosts</span><strong>{calc.result.hosts.toLocaleString()}</strong></div></div>}</div>}

export function PasswordGenerator(){const[len,setLen]=useState(18),[upper,setUpper]=useState(true),[numbers,setNumbers]=useState(true),[symbols,setSymbols]=useState(true),[value,setValue]=useState('');function gen(){let chars='abcdefghijklmnopqrstuvwxyz';if(upper)chars+='ABCDEFGHIJKLMNOPQRSTUVWXYZ';if(numbers)chars+='0123456789';if(symbols)chars+='!@#$%^&*_-+=';const rnd=new Uint32Array(Number(len));crypto.getRandomValues(rnd);setValue([...rnd].map(n=>chars[n%chars.length]).join(''))}return <div className="stack"><label>Length<input type="range" min="8" max="64" value={len} onChange={e=>setLen(e.target.value)}/><small>{len} characters</small></label><div className="check-row"><label><input type="checkbox" checked={upper} onChange={e=>setUpper(e.target.checked)}/> Uppercase</label><label><input type="checkbox" checked={numbers} onChange={e=>setNumbers(e.target.checked)}/> Numbers</label><label><input type="checkbox" checked={symbols} onChange={e=>setSymbols(e.target.checked)}/> Symbols</label></div><button className="primary" onClick={gen}>Generate password</button>{value&&<div className="password-result"><code>{value}</code><button className="mini" onClick={()=>navigator.clipboard.writeText(value)}>Copy</button></div>}</div>}

export function JsonTools(){const[text,setText]=useState('{\n  "deskora": true\n}'),[out,setOut]=useState(''),[msg,setMsg]=useState('');function act(min){try{const obj=JSON.parse(text);setOut(JSON.stringify(obj,null,min?0:2));setMsg('Valid JSON.')}catch(e){setMsg(`Invalid JSON: ${e.message}`)}}return <div className="stack"><label>JSON<textarea rows="10" value={text} onChange={e=>setText(e.target.value)}/></label><div className="button-row"><button className="primary" onClick={()=>act(false)}>Format</button><button className="secondary" onClick={()=>act(true)}>Minify</button></div>{out&&<pre className="code-result pre">{out}</pre>}<Status>{msg}</Status></div>}

function utf8ToBase64(value){const bytes=new TextEncoder().encode(value);let binary='';bytes.forEach(b=>binary+=String.fromCharCode(b));return btoa(binary)}
function base64ToUtf8(value){const binary=atob(value);const bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
export function Base64Tools(){const[text,setText]=useState(''),[out,setOut]=useState(''),[msg,setMsg]=useState('');function enc(){try{setOut(utf8ToBase64(text));setMsg('Encoded.')}catch(e){setMsg(e.message)}}function dec(){try{setOut(base64ToUtf8(text));setMsg('Decoded.')}catch(e){setMsg('Invalid Base64 input.')}}return <div className="stack"><label>Text / Base64<textarea rows="8" value={text} onChange={e=>setText(e.target.value)}/></label><div className="button-row"><button className="primary" onClick={enc}>Encode</button><button className="secondary" onClick={dec}>Decode</button></div>{out&&<pre className="code-result pre">{out}</pre>}<Status>{msg}</Status></div>}

export function DpiCalculator(){const[w,setW]=useState(8.5),[h,setH]=useState(11),[dpi,setDpi]=useState(300);return <div className="stack"><div className="form-grid three"><label>Width (in)<input type="number" step="0.01" value={w} onChange={e=>setW(e.target.value)}/></label><label>Height (in)<input type="number" step="0.01" value={h} onChange={e=>setH(e.target.value)}/></label><label>DPI<input type="number" value={dpi} onChange={e=>setDpi(e.target.value)}/></label></div><div className="hero-result"><small>Required image size</small><strong>{Math.round(w*dpi).toLocaleString()} × {Math.round(h*dpi).toLocaleString()} px</strong><span>{Number(w).toFixed(2)} × {Number(h).toFixed(2)} inches at {dpi} DPI</span></div></div>}

const paper=[['A3','297 × 420 mm','11.69 × 16.54 in'],['A4','210 × 297 mm','8.27 × 11.69 in'],['A5','148 × 210 mm','5.83 × 8.27 in'],['Letter','216 × 279 mm','8.5 × 11 in'],['Long Bond','216 × 330 mm','8.5 × 13 in'],['Legal','216 × 356 mm','8.5 × 14 in'],['Folio','216 × 330 mm','8.5 × 13 in']]
export function PaperSize(){return <div className="stack"><Status>Philippine office preset included: Long Bond 8.5 × 13 inches.</Status><div className="result-table">{paper.map(p=><div key={p[0]}><span>{p[0]}</span><strong>{p[1]}</strong><em>{p[2]}</em></div>)}</div></div>}
